// This file was autonomously generated by an AI agent at the user's request.

import type { Generation, MonotonicMs, OpaqueId } from "../core/actions.ts";

export type DiagnosticsSchemaVersion = 1;

export const DIAGNOSTICS_LIMITS = {
  maxBufferCapacity: 65_536,
  maxIdUtf8Bytes: 128,
  maxRawMidiBytes: 1_024,
  maxEvidenceReferences: 64,
} as const;

export type ClockDomainKind = "local-monotonic" | "host" | "ui" | "audio";
export type ClockUnit = "milliseconds" | "sample-frames";

export interface ClockDomain {
  readonly clockDomainId: OpaqueId;
  readonly kind: ClockDomainKind;
  readonly unit: ClockUnit;
  readonly mappingToLocal:
    | { readonly status: "local" }
    | {
        readonly status: "calibrated";
        readonly calibratedAtMs: MonotonicMs;
        readonly uncertaintyMs: number;
      }
    | { readonly status: "unmapped"; readonly reason: string };
}

export interface SourceTimestamp {
  readonly clockDomainId: OpaqueId;
  readonly value: number;
}

export interface DiagnosticHostContext {
  readonly hostInstanceId: OpaqueId;
  readonly connectionGeneration: Generation;
  readonly profileId: OpaqueId;
  readonly profileRevision: Generation;
  readonly capabilityRevision: Generation;
  readonly stateRevision: Generation;
}

export interface DiagnosticEventContext {
  readonly sessionId: OpaqueId;
  readonly correlationId: OpaqueId | null;
  readonly host: DiagnosticHostContext;
}

export interface DiagnosticEventBase {
  readonly schemaVersion: DiagnosticsSchemaVersion;
  readonly eventId: OpaqueId;
  readonly context: DiagnosticEventContext;
  readonly localClockDomainId: OpaqueId;
  readonly atMs: MonotonicMs;
  readonly capturedAtMs: MonotonicMs;
  readonly sourceTimestamp: SourceTimestamp | null;
}

export interface ArtifactReference {
  readonly artifactId: OpaqueId;
  readonly manifestRevision: Generation;
}

export interface RawRecordedEvent extends DiagnosticEventBase {
  readonly kind: "raw-recorded";
  readonly source: "ai-outbound-midi" | "physical-controller-midi" | "host-feedback-midi" | "unmapped-midi";
  readonly bytes: readonly number[];
  readonly artifact: ArtifactReference | null;
}

export interface CommandSentEvent extends DiagnosticEventBase {
  readonly kind: "command-sent";
  readonly actionId: OpaqueId;
  readonly attemptId: OpaqueId;
  readonly transportMessageIds: readonly OpaqueId[];
}

export interface HostObservedEvent extends DiagnosticEventBase {
  readonly kind: "host-observed";
  readonly observationId: OpaqueId;
  readonly observationStatus: "recorded" | "stale" | "uncertain" | "missing" | "unknown";
  readonly evidenceEventIds: readonly OpaqueId[];
}

export interface UiObservedEvent extends DiagnosticEventBase {
  readonly kind: "ui-observed";
  readonly surfaceId: OpaqueId;
  readonly renderRevision: Generation;
  readonly observationStatus: "reported" | "unavailable" | "uncertain";
  readonly artifact: ArtifactReference | null;
}

export interface AudioObservedEvent extends DiagnosticEventBase {
  readonly kind: "audio-observed";
  readonly sampleOffset: number;
  readonly observationStatus: "captured" | "unavailable" | "uncertain";
  readonly artifact: ArtifactReference | null;
}

export type DiagnosticEvent =
  | RawRecordedEvent
  | CommandSentEvent
  | HostObservedEvent
  | UiObservedEvent
  | AudioObservedEvent;

export interface ArtifactDraftMetadata {
  readonly contentType: string;
  readonly byteLength: number;
  readonly fileName: string | null;
  readonly note: string | null;
}

export interface RawArtifactManifestDraft {
  readonly schemaVersion: DiagnosticsSchemaVersion;
  readonly artifactId: OpaqueId;
  readonly revision: Generation;
  readonly kind: "raw-midi" | "audio-capture" | "ui-capture" | "timing-log";
  readonly recordedAtMs: MonotonicMs;
  readonly clockDomainId: OpaqueId;
  readonly opaqueLocalReference: OpaqueId;
  readonly absolutePath: string | null;
  readonly deviceIdentifier: string | null;
  readonly metadata: ArtifactDraftMetadata;
}

export interface RawArtifactManifest {
  readonly schemaVersion: DiagnosticsSchemaVersion;
  readonly artifactId: OpaqueId;
  readonly revision: Generation;
  readonly kind: RawArtifactManifestDraft["kind"];
  readonly recordedAtMs: MonotonicMs;
  readonly clockDomainId: OpaqueId;
  readonly opaqueLocalReference: OpaqueId;
  readonly metadata: {
    readonly contentType: string;
    readonly byteLength: number;
  };
  readonly redaction: {
    readonly removedFields: readonly ("absolute-path" | "device-identifier" | "file-name" | "note")[];
  };
}

export interface BufferedDiagnosticEvent {
  readonly captureSequence: number;
  readonly event: DiagnosticEvent;
}

export interface CaptureGapReport {
  readonly firstDroppedCaptureSequence: number;
  readonly lastDroppedCaptureSequence: number;
  readonly droppedEventCount: number;
  readonly contiguous: boolean;
}

export interface CaptureBufferStatus {
  readonly capacity: number;
  readonly queuedEventCount: number;
  readonly offeredEventCount: number;
  readonly acceptedEventCount: number;
  readonly droppedEventCount: number;
  readonly nextCaptureSequence: number;
  readonly pendingGap: CaptureGapReport | null;
}

export type CaptureOfferResult =
  | { readonly status: "accepted"; readonly captureSequence: number }
  | { readonly status: "dropped"; readonly captureSequence: number; readonly gap: CaptureGapReport };

export interface CaptureDrain {
  readonly events: readonly BufferedDiagnosticEvent[];
  readonly gaps: readonly CaptureGapReport[];
  readonly status: CaptureBufferStatus;
}

export class BoundedEventBuffer {
  readonly #capacity: number;
  #events: BufferedDiagnosticEvent[] = [];
  #nextCaptureSequence = 0;
  #offeredEventCount = 0;
  #acceptedEventCount = 0;
  #droppedEventCount = 0;
  #localClockDomainId: OpaqueId | null = null;
  #lastCapturedAtMs: number | null = null;
  #pendingGap: CaptureGapReport | null = null;

  constructor(capacity: number) {
    assertCapacity(capacity);
    this.#capacity = capacity;
  }

  offer(event: DiagnosticEvent): CaptureOfferResult {
    assertEvent(event);
    if (this.#localClockDomainId !== null && event.localClockDomainId !== this.#localClockDomainId) {
      throw new RangeError("localClockDomainId must remain stable within one capture buffer");
    }
    if (this.#lastCapturedAtMs !== null && event.capturedAtMs < this.#lastCapturedAtMs) {
      throw new RangeError("capturedAtMs must not move backwards within one capture buffer");
    }

    const copiedEvent = freezeDeep(structuredClone(event));

    const captureSequence = this.#nextCaptureSequence;
    this.#nextCaptureSequence += 1;
    this.#offeredEventCount += 1;
    this.#localClockDomainId ??= event.localClockDomainId;
    this.#lastCapturedAtMs = event.capturedAtMs;

    if (this.#events.length >= this.#capacity) {
      this.#droppedEventCount += 1;
      this.#pendingGap = extendGap(this.#pendingGap, captureSequence);
      return { status: "dropped", captureSequence, gap: this.#pendingGap };
    }

    this.#events.push(
      freezeDeep({
        captureSequence,
        event: copiedEvent,
      }),
    );
    this.#acceptedEventCount += 1;
    return { status: "accepted", captureSequence };
  }

  drain(maxEvents = this.#events.length): CaptureDrain {
    assertDrainLimit(maxEvents);
    const events = freezeDeep(this.#events.splice(0, maxEvents));
    const gaps = this.#pendingGap === null ? freezeDeep([] as CaptureGapReport[]) : freezeDeep([this.#pendingGap]);
    this.#pendingGap = null;
    return freezeDeep({ events, gaps, status: this.status() });
  }

  status(): CaptureBufferStatus {
    return freezeDeep({
      capacity: this.#capacity,
      queuedEventCount: this.#events.length,
      offeredEventCount: this.#offeredEventCount,
      acceptedEventCount: this.#acceptedEventCount,
      droppedEventCount: this.#droppedEventCount,
      nextCaptureSequence: this.#nextCaptureSequence,
      pendingGap: this.#pendingGap,
    });
  }
}

export function redactArtifactManifest(draft: RawArtifactManifestDraft): RawArtifactManifest {
  assertExactKeys(draft, ["schemaVersion", "artifactId", "revision", "kind", "recordedAtMs", "clockDomainId", "opaqueLocalReference", "absolutePath", "deviceIdentifier", "metadata"], "manifest");
  assertExactKeys(draft.metadata, ["contentType", "byteLength", "fileName", "note"], "metadata");
  if (draft.schemaVersion !== 1) throw new RangeError("unsupported manifest schemaVersion");
  assertOneOf(draft.kind, ["raw-midi", "audio-capture", "ui-capture", "timing-log"], "kind");
  assertId(draft.artifactId, "artifactId");
  assertNonNegativeGeneration(draft.revision, "revision");
  assertFiniteNonNegative(draft.recordedAtMs, "recordedAtMs");
  assertId(draft.clockDomainId, "clockDomainId");
  assertId(draft.opaqueLocalReference, "opaqueLocalReference");
  assertNonEmptyString(draft.metadata.contentType, "metadata.contentType");
  assertNonNegativeGeneration(draft.metadata.byteLength, "metadata.byteLength");

  const removedFields: ("absolute-path" | "device-identifier" | "file-name" | "note")[] = [];
  if (draft.absolutePath !== null) removedFields.push("absolute-path");
  if (draft.deviceIdentifier !== null) removedFields.push("device-identifier");
  if (draft.metadata.fileName !== null) removedFields.push("file-name");
  if (draft.metadata.note !== null) removedFields.push("note");

  return freezeDeep({
    schemaVersion: 1,
    artifactId: draft.artifactId,
    revision: draft.revision,
    kind: draft.kind,
    recordedAtMs: draft.recordedAtMs,
    clockDomainId: draft.clockDomainId,
    opaqueLocalReference: draft.opaqueLocalReference,
    metadata: {
      contentType: draft.metadata.contentType,
      byteLength: draft.metadata.byteLength,
    },
    redaction: { removedFields },
  });
}

function extendGap(previous: CaptureGapReport | null, captureSequence: number): CaptureGapReport {
  if (previous === null) {
    return freezeDeep({
      firstDroppedCaptureSequence: captureSequence,
      lastDroppedCaptureSequence: captureSequence,
      droppedEventCount: 1,
      contiguous: true,
    });
  }
  return freezeDeep({
    firstDroppedCaptureSequence: previous.firstDroppedCaptureSequence,
    lastDroppedCaptureSequence: captureSequence,
    droppedEventCount: previous.droppedEventCount + 1,
    contiguous: previous.contiguous && captureSequence === previous.lastDroppedCaptureSequence + 1,
  });
}

function assertEvent(event: DiagnosticEvent): void {
  const kindProperty = Object.getOwnPropertyDescriptor(event, "kind");
  if (!kindProperty || !("value" in kindProperty)) throw new TypeError("event kind must be a data property");
  assertExactKeys(event, [
    "schemaVersion", "eventId", "context", "localClockDomainId", "atMs", "capturedAtMs", "sourceTimestamp", "kind",
    ...eventPayloadKeys(kindProperty.value),
  ], "event");
  if (event.schemaVersion !== 1) throw new RangeError("unsupported diagnostics schemaVersion");
  assertId(event.eventId, "eventId");
  assertExactKeys(event.context, ["sessionId", "correlationId", "host"], "context");
  assertId(event.context.sessionId, "context.sessionId");
  assertNullableId(event.context.correlationId, "context.correlationId");
  assertId(event.localClockDomainId, "localClockDomainId");
  assertFiniteNonNegative(event.atMs, "atMs");
  assertFiniteNonNegative(event.capturedAtMs, "capturedAtMs");
  if (event.capturedAtMs < event.atMs) throw new RangeError("capturedAtMs must not precede atMs");
  assertSourceTimestamp(event.sourceTimestamp);
  assertExactKeys(event.context.host, [
    "hostInstanceId", "connectionGeneration", "profileId", "profileRevision", "capabilityRevision", "stateRevision",
  ], "context.host");
  assertId(event.context.host.hostInstanceId, "context.host.hostInstanceId");
  assertId(event.context.host.profileId, "context.host.profileId");
  assertNonNegativeGeneration(event.context.host.connectionGeneration, "context.host.connectionGeneration");
  assertNonNegativeGeneration(event.context.host.profileRevision, "context.host.profileRevision");
  assertNonNegativeGeneration(event.context.host.capabilityRevision, "context.host.capabilityRevision");
  assertNonNegativeGeneration(event.context.host.stateRevision, "context.host.stateRevision");

  switch (event.kind) {
    case "raw-recorded":
      assertOneOf(event.source, ["ai-outbound-midi", "physical-controller-midi", "host-feedback-midi", "unmapped-midi"], "source");
      assertMidiBytes(event.bytes);
      assertArtifactReference(event.artifact);
      return;
    case "command-sent":
      assertId(event.actionId, "actionId");
      assertId(event.attemptId, "attemptId");
      assertIdArray(event.transportMessageIds, "transportMessageIds");
      return;
    case "host-observed":
      assertId(event.observationId, "observationId");
      assertOneOf(event.observationStatus, ["recorded", "stale", "uncertain", "missing", "unknown"], "observationStatus");
      assertIdArray(event.evidenceEventIds, "evidenceEventIds");
      return;
    case "ui-observed":
      assertId(event.surfaceId, "surfaceId");
      assertNonNegativeGeneration(event.renderRevision, "renderRevision");
      assertOneOf(event.observationStatus, ["reported", "unavailable", "uncertain"], "observationStatus");
      assertArtifactReference(event.artifact);
      return;
    case "audio-observed":
      if (!Number.isSafeInteger(event.sampleOffset) || event.sampleOffset < 0) {
        throw new RangeError("sampleOffset must be a nonnegative safe integer");
      }
      assertOneOf(event.observationStatus, ["captured", "unavailable", "uncertain"], "observationStatus");
      assertArtifactReference(event.artifact);
      return;
    default:
      throw new RangeError("unknown diagnostic event kind");
  }
}

function eventPayloadKeys(kind: unknown): readonly string[] {
  switch (kind) {
    case "raw-recorded":
      return ["source", "bytes", "artifact"];
    case "command-sent":
      return ["actionId", "attemptId", "transportMessageIds"];
    case "host-observed":
      return ["observationId", "observationStatus", "evidenceEventIds"];
    case "ui-observed":
      return ["surfaceId", "renderRevision", "observationStatus", "artifact"];
    case "audio-observed":
      return ["sampleOffset", "observationStatus", "artifact"];
    default:
      throw new RangeError("unknown diagnostic event kind");
  }
}

function assertSourceTimestamp(value: SourceTimestamp | null): void {
  if (value === null) return;
  assertExactKeys(value, ["clockDomainId", "value"], "sourceTimestamp");
  assertId(value.clockDomainId, "sourceTimestamp.clockDomainId");
  if (!Number.isFinite(value.value) || Math.abs(value.value) > Number.MAX_SAFE_INTEGER) {
    throw new RangeError("sourceTimestamp.value must be finite and within the safe numeric range");
  }
}

function assertArtifactReference(value: ArtifactReference | null): void {
  if (value === null) return;
  assertExactKeys(value, ["artifactId", "manifestRevision"], "artifact");
  assertId(value.artifactId, "artifact.artifactId");
  assertNonNegativeGeneration(value.manifestRevision, "artifact.manifestRevision");
}

function assertMidiBytes(bytes: readonly number[]): void {
  assertExactArray(bytes, "bytes");
  if (bytes.length > DIAGNOSTICS_LIMITS.maxRawMidiBytes) {
    throw new RangeError(`bytes must contain at most ${DIAGNOSTICS_LIMITS.maxRawMidiBytes} values`);
  }
  for (const value of bytes) {
    if (!Number.isSafeInteger(value) || value < 0 || value > 255) {
      throw new RangeError("bytes must contain integer values from 0 to 255");
    }
  }
}

function assertIdArray(ids: readonly OpaqueId[], field: string): void {
  assertExactArray(ids, field);
  if (ids.length > DIAGNOSTICS_LIMITS.maxEvidenceReferences) {
    throw new RangeError(`${field} must contain at most ${DIAGNOSTICS_LIMITS.maxEvidenceReferences} IDs`);
  }
  for (const id of ids) assertId(id, field);
}

function assertNullableId(value: OpaqueId | null, field: string): void {
  if (value !== null) assertId(value, field);
}

function assertId(value: string, field: string): void {
  assertNonEmptyString(value, field);
  if (!/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}(?![\s\S])/.test(value)) {
    throw new RangeError(`${field} must be a bounded opaque ID`);
  }
  if (value.length > DIAGNOSTICS_LIMITS.maxIdUtf8Bytes) {
    throw new RangeError(`${field} exceeds ${DIAGNOSTICS_LIMITS.maxIdUtf8Bytes} UTF-8 bytes`);
  }
}

function assertOneOf(value: string, allowed: readonly string[], field: string): void {
  if (!allowed.includes(value)) throw new RangeError(`${field} is invalid`);
}

function assertExactKeys(value: object, expected: readonly string[], field: string): void {
  if (!isPlainObject(value)) throw new TypeError(`${field} must be a plain object`);
  const actual = Reflect.ownKeys(value);
  if (actual.length !== expected.length || actual.some((key) => typeof key !== "string" || !expected.includes(key))) {
    throw new RangeError(`${field} has unexpected or missing fields`);
  }
  for (const key of actual) {
    const property = Object.getOwnPropertyDescriptor(value, key);
    if (!property || !("value" in property) || !property.enumerable) throw new TypeError(`${field} requires enumerable data properties`);
  }
}

function assertExactArray(value: readonly unknown[], field: string): void {
  if (!Array.isArray(value)) throw new TypeError(`${field} must be an array`);
  if (value.length > DIAGNOSTICS_LIMITS.maxRawMidiBytes) throw new RangeError(`${field} exceeds the collection limit`);
  const keys = Reflect.ownKeys(value);
  if (keys.length !== value.length + 1 || keys.at(-1) !== "length" || keys.slice(0, -1).some((key, index) => key !== String(index))) {
    throw new RangeError(`${field} has unexpected properties`);
  }
  for (let index = 0; index < value.length; index += 1) {
    const property = Object.getOwnPropertyDescriptor(value, String(index));
    if (!property || !("value" in property) || !property.enumerable) throw new TypeError(`${field} requires enumerable data elements`);
  }
}

function isPlainObject(value: object): boolean {
  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

function assertCapacity(capacity: number): void {
  if (!Number.isSafeInteger(capacity) || capacity < 1 || capacity > DIAGNOSTICS_LIMITS.maxBufferCapacity) {
    throw new RangeError(`capacity must be a safe integer from 1 to ${DIAGNOSTICS_LIMITS.maxBufferCapacity}`);
  }
}

function assertDrainLimit(maxEvents: number): void {
  if (!Number.isSafeInteger(maxEvents) || maxEvents < 0) {
    throw new RangeError("maxEvents must be a nonnegative safe integer");
  }
}

function assertNonNegativeGeneration(value: number, field: string): void {
  if (!Number.isSafeInteger(value) || value < 0) throw new RangeError(`${field} must be a nonnegative safe integer`);
}

function assertFiniteNonNegative(value: number, field: string): void {
  if (!Number.isFinite(value) || value < 0 || value > Number.MAX_SAFE_INTEGER) {
    throw new RangeError(`${field} must be a finite nonnegative number`);
  }
}

function assertNonEmptyString(value: string, field: string): void {
  if (typeof value !== "string" || value.length === 0 || value.length > 256) throw new RangeError(`${field} must be a bounded nonempty string`);
}

function freezeDeep<T>(value: T, seen = new Set<object>()): T {
  if (value !== null && typeof value === "object") {
    if (seen.has(value)) return value;
    seen.add(value);
    for (const child of Object.values(value)) freezeDeep(child, seen);
    Object.freeze(value);
  }
  return value;
}

// End of autonomously AI-generated file.
