// This contract was autonomously generated by an AI agent at the user's request.

export type ActionSchemaVersion = 1;
export type OpaqueId = string;
export type Generation = number;
export type MonotonicMs = number;
export type PerformanceMode = "AIOnly" | "B2B" | "PlaylistOnly";

export const ACTION_LIMITS = {
  maxIdUtf8Bytes: 128,
  maxPreconditionDecks: 16,
  maxOwnershipClaims: 32,
  maxHostConditions: 32,
  maxTransportMessageIds: 32,
  maxDispatchHorizonMs: 60_000,
  maxObservationHorizonMs: 120_000,
  maxStateAgeMs: 5_000,
  maxMomentaryHoldMs: 10_000,
  maxRelativeJogBeats: 4,
} as const;

export interface TrackIdentity {
  readonly libraryId: OpaqueId;
  readonly trackId: OpaqueId;
}

export interface OccurrenceIdentity {
  readonly setId: OpaqueId;
  readonly occurrenceId: OpaqueId;
  readonly generation: Generation;
}

export type TrackBinding =
  | { readonly kind: "empty" }
  | {
      readonly kind: "loaded";
      readonly track: TrackIdentity;
      readonly occurrence: OccurrenceIdentity | null;
    };

export interface DeckPrecondition {
  readonly deckId: OpaqueId;
  readonly deckGeneration: Generation;
  readonly trackGeneration: Generation;
  readonly binding: TrackBinding;
}

export type DeckParameter = "volume" | "eq.low" | "eq.mid" | "eq.high";
export type MixerParameter = "crossfader";

export type ControlResource =
  | {
      readonly kind: "deck";
      readonly deckId: OpaqueId;
      readonly control: "transport" | "track" | "cue" | "jog";
    }
  | {
      readonly kind: "deck-parameter";
      readonly deckId: OpaqueId;
      readonly parameter: DeckParameter;
    }
  | { readonly kind: "mixer-parameter"; readonly parameter: MixerParameter };

export interface OwnershipClaim {
  readonly resource: ControlResource;
  readonly ownershipGeneration: Generation;
  readonly grantId: OpaqueId;
}

export interface TransitionIdentity {
  readonly transitionId: OpaqueId;
  readonly generation: Generation;
  readonly ordinal: number;
}

export interface ActionTiming {
  readonly clockId: OpaqueId;
  readonly requestedAtMs: MonotonicMs;
  readonly notBeforeMs: MonotonicMs;
  readonly dispatchByMs: MonotonicMs;
  readonly observeByMs: MonotonicMs;
}

export interface ActionIdentity {
  readonly sessionId: OpaqueId;
  readonly actionId: OpaqueId;
  readonly sequence: number;
}

export interface ActionFreshness {
  readonly hostInstanceId: OpaqueId;
  readonly connectionGeneration: Generation;
  readonly capabilityRevision: Generation;
  readonly snapshotId: OpaqueId;
  readonly stateRevision: Generation;
  readonly stateObservedAtMs: MonotonicMs;
  readonly maxStateAgeMs: number;
  readonly decks: readonly DeckPrecondition[];
  readonly conditions: readonly RequiredHostCondition[];
}

export type RequiredHostCondition =
  | {
      readonly kind: "deck-playing";
      readonly deckId: OpaqueId;
      readonly playing: boolean;
    }
  | { readonly kind: "deck-silent"; readonly deckId: OpaqueId }
  | {
      readonly kind: "cue-available";
      readonly deckId: OpaqueId;
      readonly marker: "main";
    };

export interface PerformanceAuthority {
  readonly kind: "performance";
  readonly mode: "AIOnly" | "B2B";
  readonly modeGeneration: Generation;
  readonly armingGeneration: Generation;
  readonly authorityRevision: Generation;
  readonly planId: OpaqueId;
  readonly planRevision: Generation;
  readonly cancellationGroupId: OpaqueId;
  readonly cancellationGeneration: Generation;
  readonly transition: TransitionIdentity | null;
  readonly ownership: readonly OwnershipClaim[];
}

export interface ReleaseLeaseIdentity {
  readonly obligationId: OpaqueId;
  readonly pressActionId: OpaqueId;
  readonly pressGeneration: Generation;
}

export interface ReleaseCleanupAuthority {
  readonly kind: "release-cleanup";
  readonly lease: ReleaseLeaseIdentity;
}

export interface SetPlayingOperation {
  readonly kind: "desired-state";
  readonly action: "deck.set_playing";
  readonly deckId: OpaqueId;
  readonly args: { readonly playing: boolean };
}

export interface SetDeckParameterOperation {
  readonly kind: "desired-state";
  readonly action: "deck.set_parameter";
  readonly deckId: OpaqueId;
  readonly args: {
    readonly parameter: DeckParameter;
    readonly normalizedValue: number;
  };
}

export interface SetMixerParameterOperation {
  readonly kind: "desired-state";
  readonly action: "mixer.set_parameter";
  readonly args: {
    readonly parameter: MixerParameter;
    readonly normalizedValue: number;
  };
}

export interface CueTriggerOperation {
  readonly kind: "trigger";
  readonly action: "deck.cue_goto";
  readonly deckId: OpaqueId;
  readonly args: { readonly marker: "main" };
}

export interface LoadTrackOperation {
  readonly kind: "trigger";
  readonly action: "deck.load_track";
  readonly deckId: OpaqueId;
  readonly args: {
    readonly track: TrackIdentity;
    readonly occurrence: OccurrenceIdentity;
  };
}

export interface CuePressOperation {
  readonly kind: "momentary";
  readonly action: "deck.cue_press";
  readonly deckId: OpaqueId;
  readonly args: {
    readonly marker: "main";
    readonly lease: ReleaseLeaseIdentity;
    readonly releaseByMs: MonotonicMs;
  };
}

export interface CueReleaseOperation {
  readonly kind: "momentary";
  readonly action: "deck.cue_release";
  readonly deckId: OpaqueId;
  readonly args: { readonly marker: "main"; readonly lease: ReleaseLeaseIdentity };
}

export interface RelativeJogOperation {
  readonly kind: "relative";
  readonly action: "deck.jog";
  readonly deckId: OpaqueId;
  readonly args: { readonly unit: "beats"; readonly delta: number };
}

export type PerformanceOperation =
  | SetPlayingOperation
  | SetDeckParameterOperation
  | SetMixerParameterOperation
  | CueTriggerOperation
  | LoadTrackOperation
  | CuePressOperation
  | RelativeJogOperation;

export type SemanticOperation = PerformanceOperation | CueReleaseOperation;
export type SemanticActionName = SemanticOperation["action"];

export interface ActionEnvelopeBase extends ActionIdentity {
  readonly schemaVersion: ActionSchemaVersion;
  readonly timing: ActionTiming;
  readonly preconditions: ActionFreshness;
}

export type SemanticAction = ActionEnvelopeBase &
  (
    | {
        readonly authority: PerformanceAuthority;
        readonly operation: PerformanceOperation;
      }
    | {
        readonly authority: ReleaseCleanupAuthority;
        readonly operation: CueReleaseOperation;
      }
  );

export interface MomentaryReleaseObligation extends ReleaseLeaseIdentity {
  readonly sessionId: OpaqueId;
  readonly hostInstanceId: OpaqueId;
  readonly connectionGeneration: Generation;
  readonly deck: DeckPrecondition;
  readonly control: "cue";
  readonly clockId: OpaqueId;
  readonly releaseByMs: MonotonicMs;
  readonly evidence:
    | { readonly kind: "sent-unconfirmed"; readonly attemptId: OpaqueId }
    | { readonly kind: "acknowledged-active"; readonly hostReceiptId: OpaqueId };
}

export interface OutcomeIdentity extends ActionIdentity {
  readonly schemaVersion: ActionSchemaVersion;
  readonly eventId: OpaqueId;
  readonly clockId: OpaqueId;
  readonly atMs: MonotonicMs;
}

export interface ObservationReference {
  readonly observationId: OpaqueId;
  readonly hostInstanceId: OpaqueId;
  readonly connectionGeneration: Generation;
  readonly stateRevision: Generation;
}

export type ActionAttribution =
  | { readonly actor: "unknown" }
  | {
      readonly actor: "ai" | "human";
      readonly sourceId: OpaqueId;
      readonly evidenceEventId: OpaqueId;
    };

export type ActionOutcome = OutcomeIdentity &
  (
    | { readonly status: "requested" }
    | {
        readonly status: "sent";
        readonly attemptId: OpaqueId;
        readonly transportMessageIds: readonly OpaqueId[];
      }
    | {
        readonly status: "accepted";
        readonly attemptId: OpaqueId;
        readonly hostReceiptId: OpaqueId;
      }
    | {
        readonly status: "observed";
        readonly observation: ObservationReference;
        readonly condition: "satisfied" | "not-satisfied";
        readonly correlation:
          | { readonly kind: "state-only" }
          | { readonly kind: "request-linked"; readonly hostReceiptId: OpaqueId };
        readonly attribution: ActionAttribution;
      }
    | {
        readonly status: "uncertain";
        readonly attemptId: OpaqueId | null;
        readonly reason:
          | "send-result-unknown"
          | "acceptance-missing"
          | "observation-timeout"
          | "feedback-lost"
          | "ambiguous-correlation"
          | "release-unconfirmed";
      }
    | {
        readonly status: "rejected";
        readonly stage: "validation" | "authority" | "host";
        readonly reason:
          | "invalid-data"
          | "unsupported-action"
          | "stale-context"
          | "precondition-failed"
          | "authority-denied"
          | "host-rejected";
      }
    | {
        readonly status: "cancelled";
        readonly reason:
          | "disarm"
          | "mode-changed"
          | "human-takeover"
          | "manual-stop"
          | "track-changed"
          | "plan-replaced"
          | "connection-lost"
          | "operator-cancelled";
      }
    | { readonly status: "expired"; readonly phase: "dispatch" | "observation" }
  );

// End of autonomously AI-generated contract.
