// This contract was autonomously generated by an AI agent at the user's request.

import type {
  DeckParameter,
  Generation,
  MixerParameter,
  MonotonicMs,
  OpaqueId,
  SemanticActionName,
} from "./actions.ts";

export type CapabilitySchemaVersion = 1;
export type CapabilityId = `mixxx.${string}`;
export type FeatureFamily =
  | "deck-transport" | "mixer" | "tempo-sync" | "eq-filter" | "effects"
  | "cues-loops" | "jog-scratch" | "samplers-preview" | "stems"
  | "microphone-auxiliary-vinyl" | "library-navigation" | "load-selected-track"
  | "autonomous-track-selection" | "track-metadata" | "beat-phrase-energy"
  | "autodj" | "recording" | "broadcasting" | "skin-waveform-display"
  | "sampler-bank-files" | "library-management" | "preferences-setup";

export interface HostProfile {
  readonly profileId: OpaqueId;
  readonly profileRevision: Generation;
  readonly host: "mixxx";
  readonly version: string;
  readonly buildId: OpaqueId;
  readonly platform: "macos" | "windows" | "linux";
  readonly skinId: OpaqueId;
  readonly skinRevision: OpaqueId;
  readonly configurationId: OpaqueId;
}

export interface CapabilityContext {
  readonly sessionId: OpaqueId;
  readonly hostInstanceId: OpaqueId;
  readonly connectionGeneration: Generation;
  readonly capabilityRevision: Generation;
  readonly profile: HostProfile;
}

export interface CapabilityInstance {
  readonly instanceId: OpaqueId;
  readonly generation: Generation;
  readonly kind:
    | "deck" | "sampler" | "preview-deck" | "stem" | "effect-unit"
    | "effect-slot" | "effect-parameter" | "input" | "service";
  readonly parent: { readonly instanceId: OpaqueId; readonly generation: Generation } | null;
  readonly definitionId: OpaqueId;
}

export interface CapabilityReference {
  readonly capabilityId: CapabilityId;
  readonly instance: CapabilityInstance | null;
}

export type CapabilityValueShape =
  | { readonly kind: "boolean" }
  | {
      readonly kind: "number";
      readonly unit: "normalized" | "beats" | "seconds" | "bpm" | "decibels" | "ratio";
      readonly minimum: number;
      readonly maximum: number;
      readonly step: number | null;
      readonly tolerance: number;
      readonly neutralValue: number | null;
      readonly mappingId: OpaqueId;
    }
  | { readonly kind: "enum"; readonly values: readonly OpaqueId[] }
  | { readonly kind: "track-identity" }
  | { readonly kind: "occurrence-identity" };

export type CapabilityReadSemantics =
  | { readonly kind: "unresolved"; readonly reason: string }
  | { readonly kind: "not-readable"; readonly reason: string }
  | {
      readonly kind: "state";
      readonly value: CapabilityValueShape;
      readonly delivery: "poll" | "change-events" | "poll-and-change-events";
      readonly maxAgeMs: number;
      readonly existence: "explicit-presence-required";
    };

export type ActionSelector =
  | { readonly action: "deck.set_parameter"; readonly parameter: DeckParameter }
  | { readonly action: "mixer.set_parameter"; readonly parameter: MixerParameter }
  | { readonly action: "deck.set_sync_enabled"; readonly schemaVersion: 2 }
  | { readonly action: Exclude<SemanticActionName, "deck.set_parameter" | "mixer.set_parameter" | "deck.set_sync_enabled"> };

export const SYNC_GUARD_CAPABILITIES = {
  syncEnabled: "mixxx.deck.sync-enabled",
  syncMode: "mixxx.deck.sync-mode",
  playing: "mixxx.deck.playing",
  audible: "mixxx.deck.audible",
  passthrough: "mixxx.deck.passthrough",
  vinylControl: "mixxx.deck.vinyl-control-enabled",
  quantize: "mixxx.deck.quantize-enabled",
  syncEligible: "mixxx.deck.sync-eligible",
  beatGridReady: "mixxx.deck.beatgrid-ready",
  fileBpm: "mixxx.deck.file-bpm",
  effectiveBpm: "mixxx.deck.effective-bpm",
  rateRatio: "mixxx.deck.rate-ratio",
  beatPhase: "mixxx.deck.beat-phase",
  leader: "mixxx.sync.leader",
  internalClockBpm: "mixxx.sync.internal-clock-bpm",
  pendingSyncChange: "mixxx.sync.pending-change",
} as const satisfies Readonly<Record<string, CapabilityId>>;

export type SyncLeaderValue = "none" | "internal-clock" |
  `participant-${1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16}`;

export interface SyncTopologyEvidence extends CapabilityContext {
  readonly schemaVersion: 1;
  readonly evidenceId: OpaqueId;
  readonly topologyRevision: Generation;
  readonly clockId: OpaqueId;
  readonly observedAtMs: MonotonicMs;
  readonly validUntilMs: MonotonicMs;
  readonly participants: readonly {
    readonly deckId: OpaqueId;
    readonly deckGeneration: Generation;
    readonly instance: CapabilityInstance;
  }[];
  readonly closureEvidenceIds: readonly OpaqueId[];
}

export type SyncGuardAvailability =
  | { readonly status: "unavailable"; readonly reason: "topology-unverified" | "telemetry-unavailable" | "effect-bound-unverified" | "stale-context" }
  | { readonly status: "available"; readonly topology: SyncTopologyEvidence };

export type CapabilityWriteSemantics =
  | { readonly kind: "unresolved"; readonly reason: string }
  | { readonly kind: "read-only"; readonly reason: string }
  | {
      readonly kind: "extension-needed";
      readonly operationSpecId: OpaqueId;
      readonly reason: string;
    }
  | {
      readonly kind: "action";
      readonly selector: ActionSelector;
      readonly behavior: "desired-state" | "trigger" | "momentary" | "relative";
      readonly acknowledgement: "none" | "request-linked";
      readonly deduplication: "none" | "action-and-attempt";
      readonly mappingId: OpaqueId;
    };

export interface CapabilityDefinition {
  readonly capabilityId: CapabilityId;
  readonly family: FeatureFamily;
  readonly label: string;
  readonly status: "candidate" | "unresolved" | "extension-needed" | "specified";
  readonly read: CapabilityReadSemantics;
  readonly write: CapabilityWriteSemantics;
  readonly instances:
    | { readonly kind: "singleton" }
    | {
        readonly kind: "dynamic";
        readonly inventoryRevision: Generation;
        readonly discovered: readonly CapabilityInstance[];
        readonly enumeration:
          | { readonly status: "complete"; readonly evidenceIds: readonly OpaqueId[] }
          | { readonly status: "incomplete"; readonly reason: string; readonly continuationId: OpaqueId };
      };
}

export interface CapabilityAlias {
  readonly aliasId: OpaqueId;
  readonly canonicalId: CapabilityId;
  readonly evidenceIds: readonly OpaqueId[];
}

export interface CapabilityEvidenceReference {
  readonly evidenceId: OpaqueId;
  readonly artifactId: OpaqueId;
  readonly runId: OpaqueId;
  readonly context: CapabilityContext;
  readonly target: CapabilityReference;
  readonly clockId: OpaqueId;
  readonly atMs: MonotonicMs;
}

export type EvidenceDimension<Kind extends string> =
  | { readonly status: "untested"; readonly reason: string }
  | { readonly status: "failed"; readonly evidence: readonly CapabilityEvidenceReference[]; readonly reason: string }
  | { readonly status: "not-applicable"; readonly rationale: string; readonly reviewEvidenceId: OpaqueId }
  | {
      readonly status: "passed";
      readonly kind: Kind;
      readonly evidence: readonly CapabilityEvidenceReference[];
    };

export interface CapabilityAssessment {
  readonly target: CapabilityReference;
  readonly availability:
    | { readonly status: "unknown"; readonly reason: string }
    | { readonly status: "absent"; readonly evidenceIds: readonly OpaqueId[] }
    | { readonly status: "present"; readonly evidenceIds: readonly OpaqueId[] };
  readonly command: EvidenceDimension<"actual-host-command">;
  readonly feedback: EvidenceDimension<"actual-host-feedback">;
  readonly nativeUi: EvidenceDimension<"native-ui-observation">;
  readonly runtime: EvidenceDimension<"actual-runtime-scenario">;
}

export interface CapabilityCatalog extends CapabilityContext {
  readonly schemaVersion: CapabilitySchemaVersion;
  readonly catalogId: OpaqueId;
  readonly definitions: readonly CapabilityDefinition[];
  readonly aliases: readonly CapabilityAlias[];
  readonly assessments: readonly CapabilityAssessment[];
  readonly inventory:
    | { readonly status: "open"; readonly unresolvedFamilies: readonly FeatureFamily[]; readonly continuationIds: readonly OpaqueId[] }
    | { readonly status: "closed"; readonly closureEvidenceIds: readonly OpaqueId[] };
}

// End of autonomously AI-generated contract.
