// This contract was autonomously generated by an AI agent at the user's request.

import type {
  ActionAttribution,
  ActionIdentity,
  DeckPrecondition,
  Generation,
  MonotonicMs,
  ObservationReference,
  OccurrenceIdentity,
  OpaqueId,
  SemanticOperation,
  TrackIdentity,
} from "./actions.ts";
import type { CapabilityContext, CapabilityReference } from "./capabilities.ts";

export type StateSchemaVersion = 1;

export interface StateContext extends CapabilityContext {
  readonly clockId: OpaqueId;
  readonly streamId: OpaqueId;
  readonly streamGeneration: Generation;
}

export interface ObservationEvidence extends ObservationReference {
  readonly clockId: OpaqueId;
  readonly observedAtMs: MonotonicMs;
  readonly receivedAtMs: MonotonicMs;
  readonly validUntilMs: MonotonicMs;
  readonly source:
    | { readonly kind: "host-read" | "host-feedback"; readonly eventId: OpaqueId }
    | { readonly kind: "host-reconciled"; readonly eventIds: readonly OpaqueId[] };
  readonly attribution: ActionAttribution;
}

export type Observation<T> =
  | { readonly status: "observed"; readonly value: T; readonly evidence: ObservationEvidence }
  | {
      readonly status: "stale";
      readonly lastKnown: { readonly value: T; readonly evidence: ObservationEvidence };
      readonly reason: "age-expired" | "connection-changed" | "identity-changed" | "profile-changed" | "stream-gap";
    }
  | {
      readonly status: "missing";
      readonly reason: "control-absent" | "instance-absent";
      readonly presenceEvidenceIds: readonly OpaqueId[];
    }
  | {
      readonly status: "unknown";
      readonly reason: "not-observed" | "existence-unverified" | "feedback-unavailable" | "identity-unresolved";
    }
  | {
      readonly status: "uncertain";
      readonly reason: "conflicting-feedback" | "ordering-gap" | "clock-unmapped" | "binding-ambiguous";
      readonly evidenceIds: readonly OpaqueId[];
    };

export type CapabilityObservedValue =
  | { readonly kind: "boolean"; readonly value: boolean }
  | {
      readonly kind: "number";
      readonly value: number;
      readonly unit: "normalized" | "beats" | "seconds" | "bpm" | "decibels" | "ratio";
    }
  | { readonly kind: "enum"; readonly value: OpaqueId }
  | { readonly kind: "track-identity"; readonly value: TrackIdentity }
  | { readonly kind: "occurrence-identity"; readonly value: OccurrenceIdentity };

export interface CapabilityReading {
  readonly target: CapabilityReference;
  readonly deck:
    | { readonly kind: "known"; readonly precondition: DeckPrecondition }
    | { readonly kind: "unknown"; readonly deckId: OpaqueId; readonly deckGeneration: Generation }
    | null;
  readonly observation: Observation<CapabilityObservedValue>;
}

export interface DeckObservation {
  readonly deckId: OpaqueId;
  readonly deckGeneration: Generation;
  readonly current: Observation<DeckPrecondition>;
}

export interface StateEnvelope extends StateContext {
  readonly schemaVersion: StateSchemaVersion;
  readonly messageId: OpaqueId;
  readonly sequence: number;
  readonly producedAtMs: MonotonicMs;
  readonly stateRevision: Generation;
}

export interface StateSnapshot extends StateEnvelope {
  readonly kind: "snapshot";
  readonly snapshotId: OpaqueId;
  readonly replacement: "entire-context";
  readonly decks: readonly DeckObservation[];
  readonly readings: readonly CapabilityReading[];
}

export type StateChange =
  | { readonly kind: "replace-deck"; readonly deck: DeckObservation }
  | {
      readonly kind: "remove-deck";
      readonly deckId: OpaqueId;
      readonly deckGeneration: Generation;
      readonly evidenceIds: readonly OpaqueId[];
    }
  | { readonly kind: "replace-reading"; readonly reading: CapabilityReading }
  | {
      readonly kind: "remove-reading";
      readonly target: CapabilityReference;
      readonly evidenceIds: readonly OpaqueId[];
    };

export interface StateDelta extends StateEnvelope {
  readonly kind: "delta";
  readonly snapshotId: OpaqueId;
  readonly baseRevision: Generation;
  readonly previousSequence: number;
  readonly changes: readonly StateChange[];
}

export type ObservedStateMessage = StateSnapshot | StateDelta;

export interface StateContinuityGap extends StateContext {
  readonly kind: "state-gap";
  readonly eventId: OpaqueId;
  readonly atMs: MonotonicMs;
  readonly snapshotId: OpaqueId | null;
  readonly lastAcceptedRevision: Generation | null;
  readonly lastAcceptedSequence: number | null;
  readonly receivedMessageId: OpaqueId | null;
  readonly reason:
    | "sequence-gap" | "base-mismatch" | "snapshot-missing"
    | "context-changed" | "conflicting-duplicate" | "feedback-lost";
  readonly recovery: "fresh-snapshot-required";
}

export interface RequestedState extends ActionIdentity {
  readonly kind: "requested-state";
  readonly operation: SemanticOperation;
}

export interface InferredIntent {
  readonly kind: "inferred-intent";
  readonly inferenceId: OpaqueId;
  readonly sessionId: OpaqueId;
  readonly observationIds: readonly OpaqueId[];
  readonly sourceEventIds: readonly OpaqueId[];
  readonly inferredActor: "human" | "ai" | "unknown";
  readonly interpretation: "manual-adjustment" | "manual-stop" | "manual-track-replacement" | "unresolved";
  readonly confidence: number;
}

// End of autonomously AI-generated contract.
