// This validator was autonomously generated by an AI agent at the user's request.
// It is a data-admission boundary; it neither sends actions nor reconciles state.

import { ACTION_LIMITS, type ActionOutcome, type MomentaryReleaseObligation, type SemanticAction } from "./actions.ts";
import type { CapabilityReference } from "./capabilities.ts";
import type { ObservedStateMessage } from "./state.ts";

export const VALIDATION_LIMITS = {
  maxTransportBytes: 65_536,
  maxDepth: 32,
  maxNodes: 4_096,
  maxStringUtf8Bytes: 4_096,
  maxStateEntries: 256,
  maxEvidenceIds: 64,
  maxObjectKeys: 64,
} as const;

export interface ValidationError {
  readonly path: string;
  readonly code: string;
  readonly message: string;
}

export type ValidationResult<T> =
  | { readonly ok: true; readonly value: T }
  | { readonly ok: false; readonly errors: readonly ValidationError[] };

/** Rules resolved from the active, immutable capability catalog. */
export interface CapabilityReferenceRules {
  readonly value:
    | { readonly kind: "boolean" }
    | { readonly kind: "number"; readonly unit: string; readonly minimum: number; readonly maximum: number }
    | { readonly kind: "enum"; readonly values: readonly string[] }
    | { readonly kind: "track-identity" }
    | { readonly kind: "occurrence-identity" };
  readonly instanceIds?: readonly string[];
  readonly maxAgeMs: number;
}

export interface StateValidationReferences {
  /** Must resolve the exact canonical target in the message's profile/revision. */
  readonly resolveCapability: (target: CapabilityReference) => CapabilityReferenceRules | undefined;
  /** A caller-owned immutable baseline. This validator reads it but never applies a delta. */
  readonly baseline?: {
    readonly snapshotId: string;
    readonly stateRevision: number;
    readonly sequence: number;
    readonly sessionId: string;
    readonly hostInstanceId: string;
    readonly connectionGeneration: number;
    readonly capabilityRevision: number;
    readonly clockId: string;
    readonly streamId: string;
    readonly streamGeneration: number;
  };
}

class Invalid extends Error {
  readonly detail: ValidationError;
  constructor(detail: ValidationError) {
    super(detail.message);
    this.detail = detail;
  }
}

type JsonObject = Record<string, unknown>;
const opaqueId = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}(?![\s\S])/;
const deckParameters = new Set(["volume", "eq.low", "eq.mid", "eq.high"]);
const stateReasons = new Set(["age-expired", "connection-changed", "identity-changed", "profile-changed", "stream-gap"]);
const unknownReasons = new Set(["not-observed", "existence-unverified", "feedback-unavailable", "identity-unresolved"]);
const uncertainReasons = new Set(["conflicting-feedback", "ordering-gap", "clock-unmapped", "binding-ambiguous"]);
const featureKinds = new Set(["deck", "sampler", "preview-deck", "stem", "effect-unit", "effect-slot", "effect-parameter", "input", "service"]);

function issue(path: string, code: string, message: string): never {
  throw new Invalid({ path, code, message });
}

function bytes(value: string): number {
  return new TextEncoder().encode(value).byteLength;
}

function preflight(value: unknown, path = "$", depth = 0, seen = new Set<object>(), count = { value: 0 }): void {
  if (depth > VALIDATION_LIMITS.maxDepth) issue(path, "too-deep", "Input exceeds the nesting limit");
  count.value += 1;
  if (count.value > VALIDATION_LIMITS.maxNodes) issue(path, "too-many-nodes", "Input exceeds the node limit");
  if (value === null || typeof value === "boolean" || typeof value === "number") {
    if (typeof value === "number" && !Number.isFinite(value)) issue(path, "non-finite", "Numbers must be finite JSON numbers");
    return;
  }
  if (typeof value === "string") {
    if (bytes(value) > VALIDATION_LIMITS.maxStringUtf8Bytes) issue(path, "string-too-large", "String exceeds the byte limit");
    return;
  }
  if (typeof value !== "object") issue(path, "non-json", "Input contains a non-JSON value");
  if (seen.has(value)) issue(path, "recursive", "Input must not contain recursive objects");
  const keys = Reflect.ownKeys(value);
  const keyLimit = Array.isArray(value) ? VALIDATION_LIMITS.maxStateEntries + 1 : VALIDATION_LIMITS.maxObjectKeys;
  if (keys.length > keyLimit) issue(path, "too-many-keys", "Record exceeds its key limit");
  for (const key of keys) {
    if (typeof key !== "string") issue(path, "non-json", "Symbol keys are not JSON");
    if (bytes(key) > ACTION_LIMITS.maxIdUtf8Bytes) issue(path, "key-too-large", "Key exceeds its byte limit");
    const descriptor = Object.getOwnPropertyDescriptor(value, key);
    if (!descriptor || !("value" in descriptor) || (!descriptor.enumerable && !(Array.isArray(value) && key === "length"))) {
      issue(path, "non-json", "Accessors and hidden properties are not JSON");
    }
  }
  seen.add(value);
  if (Array.isArray(value)) {
    if (value.length > VALIDATION_LIMITS.maxStateEntries) issue(path, "array-too-large", "Array exceeds the collection limit");
    for (const key of Object.keys(value)) if (!/^(0|[1-9][0-9]*)$/.test(key)) issue(`${path}.${key}`, "non-json", "Arrays cannot carry named properties");
    for (let index = 0; index < value.length; index += 1) {
      const descriptor = Object.getOwnPropertyDescriptor(value, String(index));
      if (!descriptor || !("value" in descriptor)) issue(`${path}[${index}]`, "non-json", "Arrays cannot contain holes or accessors");
      preflight(descriptor.value, `${path}[${index}]`, depth + 1, seen, count);
    }
  } else {
    const prototype = Object.getPrototypeOf(value);
    if (prototype !== Object.prototype && prototype !== null) issue(path, "not-plain-object", "Records must be plain JSON objects");
    for (const key of Object.keys(value)) {
      const descriptor = Object.getOwnPropertyDescriptor(value, key);
      if (!descriptor || !("value" in descriptor)) issue(`${path}.${key}`, "non-json", "Records cannot contain accessors");
      preflight(descriptor.value, `${path}.${key}`, depth + 1, seen, count);
    }
  }
  seen.delete(value);
}

function external(value: unknown): unknown {
  if (typeof value === "string") {
    if (value.length > VALIDATION_LIMITS.maxTransportBytes) issue("$", "payload-too-large", "Transport payload exceeds its byte limit");
    if (bytes(value) > VALIDATION_LIMITS.maxTransportBytes) issue("$", "payload-too-large", "Transport payload exceeds 65536 UTF-8 bytes");
    let nesting = 0;
    let quoted = false;
    let escaped = false;
    for (const character of value) {
      if (quoted) {
        if (escaped) escaped = false;
        else if (character === "\\") escaped = true;
        else if (character === '"') quoted = false;
      } else if (character === '"') quoted = true;
      else if (character === "{" || character === "[") {
        nesting += 1;
        if (nesting > VALIDATION_LIMITS.maxDepth) issue("$", "too-deep", "JSON nesting exceeds the pre-parse limit");
      } else if (character === "}" || character === "]") nesting -= 1;
    }
    try {
      const parsed: unknown = JSON.parse(value);
      preflight(parsed);
      return parsed;
    } catch (error) {
      if (error instanceof Invalid) throw error;
      issue("$", "invalid-json", "Input is not valid JSON");
    }
  }
  preflight(value);
  let serialized: string;
  try {
    serialized = JSON.stringify(value);
  } catch {
    issue("$", "non-json", "Input cannot be serialized as JSON");
  }
  if (bytes(serialized) > VALIDATION_LIMITS.maxTransportBytes) issue("$", "payload-too-large", "Transport payload exceeds 65536 UTF-8 bytes");
  return value;
}

function object(value: unknown, path: string, fields: readonly string[]): JsonObject {
  if (value === null || typeof value !== "object" || Array.isArray(value)) issue(path, "expected-object", "Expected a JSON object");
  const record = value as JsonObject;
  const allowed = new Set(fields);
  for (const key of Object.keys(record)) if (!allowed.has(key)) issue(`${path}.${key}`, "unknown-field", "Unknown field");
  for (const key of fields) if (!Object.hasOwn(record, key)) issue(`${path}.${key}`, "missing-field", "Required field is absent");
  return record;
}

function string(value: unknown, path: string): string {
  if (typeof value !== "string") issue(path, "expected-string", "Expected a string");
  return value;
}

function id(value: unknown, path: string): string {
  const result = string(value, path);
  if (!opaqueId.test(result) || bytes(result) > ACTION_LIMITS.maxIdUtf8Bytes) issue(path, "invalid-id", "Expected a bounded opaque ID");
  return result;
}

function literal<T extends string | number | boolean>(value: unknown, expected: T, path: string): T {
  if (value !== expected) issue(path, "invalid-literal", `Expected ${String(expected)}`);
  return expected;
}

function oneOf(value: unknown, allowed: ReadonlySet<string>, path: string): string {
  const result = string(value, path);
  if (!allowed.has(result)) issue(path, "invalid-enum", "Unknown enum value");
  return result;
}

function safeInteger(value: unknown, path: string): number {
  if (typeof value !== "number" || !Number.isSafeInteger(value) || value < 0) issue(path, "invalid-generation", "Expected a nonnegative safe integer");
  return value;
}

function time(value: unknown, path: string): number {
  if (typeof value !== "number" || !Number.isFinite(value) || value < 0 || value > Number.MAX_SAFE_INTEGER) issue(path, "invalid-time", "Expected a finite monotonic millisecond value");
  return value;
}

function number(value: unknown, path: string): number {
  if (typeof value !== "number" || !Number.isFinite(value)) issue(path, "invalid-number", "Expected a finite number");
  return value;
}

function bool(value: unknown, path: string): boolean {
  if (typeof value !== "boolean") issue(path, "expected-boolean", "Expected a boolean");
  return value;
}

function array(value: unknown, path: string, maximum: number = VALIDATION_LIMITS.maxStateEntries): unknown[] {
  if (!Array.isArray(value)) issue(path, "expected-array", "Expected an array");
  if (value.length > maximum) issue(path, "array-too-large", "Array exceeds its contract limit");
  return value;
}

function nonemptyIds(value: unknown, path: string, maximum: number = VALIDATION_LIMITS.maxEvidenceIds): string[] {
  const values = array(value, path, maximum).map((entry, index) => id(entry, `${path}[${index}]`));
  if (values.length === 0) issue(path, "empty-array", "At least one ID is required");
  if (new Set(values).size !== values.length) issue(path, "duplicate", "IDs must be distinct");
  return values;
}

function track(value: unknown, path: string): void {
  const record = object(value, path, ["libraryId", "trackId"]);
  id(record.libraryId, `${path}.libraryId`); id(record.trackId, `${path}.trackId`);
}

function occurrence(value: unknown, path: string): void {
  const record = object(value, path, ["setId", "occurrenceId", "generation"]);
  id(record.setId, `${path}.setId`); id(record.occurrenceId, `${path}.occurrenceId`); safeInteger(record.generation, `${path}.generation`);
}

function binding(value: unknown, path: string): "empty" | "loaded" {
  if (value === null || typeof value !== "object" || Array.isArray(value)) issue(path, "expected-object", "Expected a track binding");
  const kind = (value as JsonObject).kind;
  if (kind === "empty") { object(value, path, ["kind"]); return "empty"; }
  if (kind !== "loaded") issue(`${path}.kind`, "invalid-binding", "Unknown track binding kind");
  const record = object(value, path, ["kind", "track", "occurrence"]);
  track(record.track, `${path}.track`);
  if (record.occurrence !== null) occurrence(record.occurrence, `${path}.occurrence`);
  return "loaded";
}

function deckPrecondition(value: unknown, path: string): { deckId: string; deckGeneration: number; trackGeneration: number; binding: "empty" | "loaded" } {
  const record = object(value, path, ["deckId", "deckGeneration", "trackGeneration", "binding"]);
  return { deckId: id(record.deckId, `${path}.deckId`), deckGeneration: safeInteger(record.deckGeneration, `${path}.deckGeneration`), trackGeneration: safeInteger(record.trackGeneration, `${path}.trackGeneration`), binding: binding(record.binding, `${path}.binding`) };
}

function attribution(value: unknown, path: string): void {
  if (value === null || typeof value !== "object" || Array.isArray(value)) issue(path, "expected-object", "Expected attribution");
  const actor = (value as JsonObject).actor;
  if (actor === "unknown") { object(value, path, ["actor"]); return; }
  if (actor !== "ai" && actor !== "human") issue(`${path}.actor`, "invalid-actor", "Unknown actor");
  const record = object(value, path, ["actor", "sourceId", "evidenceEventId"]);
  id(record.sourceId, `${path}.sourceId`); id(record.evidenceEventId, `${path}.evidenceEventId`);
}

function lease(value: unknown, path: string): { obligationId: string; pressActionId: string; pressGeneration: number } {
  const record = object(value, path, ["obligationId", "pressActionId", "pressGeneration"]);
  return { obligationId: id(record.obligationId, `${path}.obligationId`), pressActionId: id(record.pressActionId, `${path}.pressActionId`), pressGeneration: safeInteger(record.pressGeneration, `${path}.pressGeneration`) };
}

function conditions(value: unknown, path: string, deckIds?: ReadonlySet<string>): Map<string, Set<string>> {
  const result = new Map<string, Set<string>>();
  const playing = new Map<string, boolean>();
  for (const [index, entry] of array(value, path, ACTION_LIMITS.maxHostConditions).entries()) {
    if (entry === null || typeof entry !== "object" || Array.isArray(entry)) issue(`${path}[${index}]`, "expected-object", "Expected host condition");
    const kind = (entry as JsonObject).kind;
    let deckId: string;
    if (kind === "deck-playing") { const r = object(entry, `${path}[${index}]`, ["kind", "deckId", "playing"]); deckId = id(r.deckId, `${path}[${index}].deckId`); bool(r.playing, `${path}[${index}].playing`); }
    else if (kind === "deck-silent") { const r = object(entry, `${path}[${index}]`, ["kind", "deckId"]); deckId = id(r.deckId, `${path}[${index}].deckId`); }
    else if (kind === "cue-available") { const r = object(entry, `${path}[${index}]`, ["kind", "deckId", "marker"]); deckId = id(r.deckId, `${path}[${index}].deckId`); literal(r.marker, "main", `${path}[${index}].marker`); }
    else issue(`${path}[${index}].kind`, "invalid-condition", "Unknown host condition");
    if (deckIds && !deckIds.has(deckId)) issue(`${path}[${index}].deckId`, "dangling-condition-deck", "Conditions require a declared deck precondition");
    if (kind === "deck-playing") {
      const value = (entry as JsonObject).playing as boolean;
      const prior = playing.get(deckId);
      if (prior !== undefined && prior !== value) issue(`${path}[${index}]`, "conflicting-condition", "Deck playing conditions cannot conflict");
      playing.set(deckId, value);
    }
    const key = kind === "deck-playing" ? `deck-playing:${deckId}:${String((entry as JsonObject).playing)}`
      : kind === "deck-silent" ? `deck-silent:${deckId}`
        : `cue-available:${deckId}:main`;
    if (result.get(deckId)?.has(key)) issue(`${path}[${index}]`, "duplicate-condition", "Duplicate host condition");
    (result.get(deckId) ?? result.set(deckId, new Set()).get(deckId)!).add(key);
  }
  return result;
}

function controlResource(value: unknown, path: string): string {
  if (value === null || typeof value !== "object" || Array.isArray(value)) issue(path, "expected-object", "Expected control resource");
  const kind = (value as JsonObject).kind;
  if (kind === "deck") { const r = object(value, path, ["kind", "deckId", "control"]); const deck = id(r.deckId, `${path}.deckId`); oneOf(r.control, new Set(["transport", "track", "cue", "jog"]), `${path}.control`); return `${kind}:${deck}:${String(r.control)}`; }
  if (kind === "deck-parameter") { const r = object(value, path, ["kind", "deckId", "parameter"]); const deck = id(r.deckId, `${path}.deckId`); oneOf(r.parameter, deckParameters, `${path}.parameter`); return `${kind}:${deck}:${String(r.parameter)}`; }
  if (kind === "mixer-parameter") { const r = object(value, path, ["kind", "parameter"]); literal(r.parameter, "crossfader", `${path}.parameter`); return "mixer-parameter:crossfader"; }
  issue(`${path}.kind`, "invalid-resource", "Unknown control resource");
}

function authority(value: unknown, path: string): { kind: "performance" | "release-cleanup"; ownership: Set<string>; cleanupLease?: { obligationId: string; pressActionId: string; pressGeneration: number } } {
  if (value === null || typeof value !== "object" || Array.isArray(value)) issue(path, "expected-object", "Expected authority");
  if ((value as JsonObject).kind === "release-cleanup") { const r = object(value, path, ["kind", "lease"]); return { kind: "release-cleanup", ownership: new Set(), cleanupLease: lease(r.lease, `${path}.lease`) }; }
  const r = object(value, path, ["kind", "mode", "modeGeneration", "armingGeneration", "authorityRevision", "planId", "planRevision", "cancellationGroupId", "cancellationGeneration", "transition", "ownership"]);
  literal(r.kind, "performance", `${path}.kind`); oneOf(r.mode, new Set(["AIOnly", "B2B"]), `${path}.mode`);
  for (const key of ["modeGeneration", "armingGeneration", "authorityRevision", "planRevision", "cancellationGeneration"] as const) safeInteger(r[key], `${path}.${key}`);
  id(r.planId, `${path}.planId`); id(r.cancellationGroupId, `${path}.cancellationGroupId`);
  if (r.transition !== null) { const t = object(r.transition, `${path}.transition`, ["transitionId", "generation", "ordinal"]); id(t.transitionId, `${path}.transition.transitionId`); safeInteger(t.generation, `${path}.transition.generation`); safeInteger(t.ordinal, `${path}.transition.ordinal`); }
  const ownership = new Set<string>();
  for (const [index, claim] of array(r.ownership, `${path}.ownership`, ACTION_LIMITS.maxOwnershipClaims).entries()) {
    const c = object(claim, `${path}.ownership[${index}]`, ["resource", "ownershipGeneration", "grantId"]);
    const resource = controlResource(c.resource, `${path}.ownership[${index}].resource`); safeInteger(c.ownershipGeneration, `${path}.ownership[${index}].ownershipGeneration`); id(c.grantId, `${path}.ownership[${index}].grantId`);
    if (ownership.has(resource)) issue(`${path}.ownership[${index}]`, "duplicate-ownership", "Ownership claims must be unique per resource");
    ownership.add(resource);
  }
  return { kind: "performance", ownership };
}

function freshness(value: unknown, path: string): Map<string, { binding: "empty" | "loaded" }> {
  const r = object(value, path, ["hostInstanceId", "connectionGeneration", "capabilityRevision", "snapshotId", "stateRevision", "stateObservedAtMs", "maxStateAgeMs", "decks", "conditions"]);
  for (const key of ["hostInstanceId", "snapshotId"] as const) id(r[key], `${path}.${key}`);
  for (const key of ["connectionGeneration", "capabilityRevision", "stateRevision"] as const) safeInteger(r[key], `${path}.${key}`);
  const observed = time(r.stateObservedAtMs, `${path}.stateObservedAtMs`);
  const age = number(r.maxStateAgeMs, `${path}.maxStateAgeMs`);
  if (age <= 0 || age > ACTION_LIMITS.maxStateAgeMs) issue(`${path}.maxStateAgeMs`, "invalid-age", "State age must be positive and bounded");
  const decks = new Map<string, { binding: "empty" | "loaded" }>();
  for (const [index, entry] of array(r.decks, `${path}.decks`, ACTION_LIMITS.maxPreconditionDecks).entries()) {
    const current = deckPrecondition(entry, `${path}.decks[${index}]`);
    if (decks.has(current.deckId)) issue(`${path}.decks[${index}].deckId`, "duplicate-deck", "Deck preconditions must be distinct");
    decks.set(current.deckId, { binding: current.binding });
  }
  conditions(r.conditions, `${path}.conditions`, new Set(decks.keys()));
  return decks;
}

function operation(value: unknown, path: string, decks: Map<string, { binding: "empty" | "loaded" }>, conditionsByDeck: Map<string, Set<string>>, ownership: Set<string>, actionId: string, authorityKind: "performance" | "release-cleanup", cleanupLease: { obligationId: string; pressActionId: string; pressGeneration: number } | undefined, timing: { notBefore: number; dispatchBy: number; observeBy: number }): void {
  if (value === null || typeof value !== "object" || Array.isArray(value)) issue(path, "expected-object", "Expected operation");
  const raw = value as JsonObject;
  const action = string(raw.action, `${path}.action`);
  const target = (deckId: string, required: readonly string[], loaded: boolean) => {
    const deck = decks.get(deckId);
    if (!deck) issue(`${path}.deckId`, "missing-deck-precondition", "Operation requires its target deck precondition");
    if (loaded && deck.binding !== "loaded") issue(`${path}.deckId`, "unknown-or-empty-binding", "Operation requires a known loaded track binding");
    for (const resource of required) if (!ownership.has(resource)) issue(`${path}`, "missing-ownership", "Operation lacks required ownership claim");
  };
  const needs = (deckId: string, kind: string) => conditionsByDeck.get(deckId)?.has(kind) ?? false;
  if (action === "deck.set_playing") { const r = object(value, path, ["kind", "action", "deckId", "args"]); literal(r.kind, "desired-state", `${path}.kind`); const deckId = id(r.deckId, `${path}.deckId`); const a = object(r.args, `${path}.args`, ["playing"]); bool(a.playing, `${path}.args.playing`); target(deckId, [`deck:${deckId}:transport`], true); }
  else if (action === "deck.set_parameter") { const r = object(value, path, ["kind", "action", "deckId", "args"]); literal(r.kind, "desired-state", `${path}.kind`); const deckId = id(r.deckId, `${path}.deckId`); const a = object(r.args, `${path}.args`, ["parameter", "normalizedValue"]); const parameter = oneOf(a.parameter, deckParameters, `${path}.args.parameter`); const v = number(a.normalizedValue, `${path}.args.normalizedValue`); if (v < 0 || v > 1) issue(`${path}.args.normalizedValue`, "out-of-range", "Normalized value must be in [0, 1]"); target(deckId, [`deck-parameter:${deckId}:${parameter}`], false); }
  else if (action === "mixer.set_parameter") { const r = object(value, path, ["kind", "action", "args"]); literal(r.kind, "desired-state", `${path}.kind`); const a = object(r.args, `${path}.args`, ["parameter", "normalizedValue"]); literal(a.parameter, "crossfader", `${path}.args.parameter`); const v = number(a.normalizedValue, `${path}.args.normalizedValue`); if (v < 0 || v > 1) issue(`${path}.args.normalizedValue`, "out-of-range", "Normalized value must be in [0, 1]"); if (!ownership.has("mixer-parameter:crossfader")) issue(path, "missing-ownership", "Operation lacks required ownership claim"); }
  else if (action === "deck.cue_goto") { const r = object(value, path, ["kind", "action", "deckId", "args"]); literal(r.kind, "trigger", `${path}.kind`); const deckId = id(r.deckId, `${path}.deckId`); const a = object(r.args, `${path}.args`, ["marker"]); literal(a.marker, "main", `${path}.args.marker`); target(deckId, [`deck:${deckId}:cue`, `deck:${deckId}:jog`, `deck:${deckId}:transport`], true); if (!needs(deckId, `cue-available:${deckId}:main`)) issue(path, "missing-cue-condition", "Cue action requires a main-cue condition"); }
  else if (action === "deck.load_track") { const r = object(value, path, ["kind", "action", "deckId", "args"]); literal(r.kind, "trigger", `${path}.kind`); const deckId = id(r.deckId, `${path}.deckId`); const a = object(r.args, `${path}.args`, ["track", "occurrence"]); track(a.track, `${path}.args.track`); occurrence(a.occurrence, `${path}.args.occurrence`); target(deckId, [`deck:${deckId}:track`, `deck:${deckId}:transport`, `deck:${deckId}:cue`, `deck:${deckId}:jog`], false); if (!needs(deckId, `deck-silent:${deckId}`)) issue(path, "missing-silent-condition", "Load requires a deck-silent condition"); }
  else if (action === "deck.cue_press") { const r = object(value, path, ["kind", "action", "deckId", "args"]); literal(r.kind, "momentary", `${path}.kind`); const deckId = id(r.deckId, `${path}.deckId`); const a = object(r.args, `${path}.args`, ["marker", "lease", "releaseByMs"]); literal(a.marker, "main", `${path}.args.marker`); const leaseId = lease(a.lease, `${path}.args.lease`).pressActionId; if (leaseId !== actionId) issue(`${path}.args.lease.pressActionId`, "lease-mismatch", "Press lease must bind the envelope action ID"); const releaseBy = time(a.releaseByMs, `${path}.args.releaseByMs`); if (releaseBy <= timing.dispatchBy || releaseBy > timing.observeBy || releaseBy - timing.notBefore > ACTION_LIMITS.maxMomentaryHoldMs) issue(`${path}.args.releaseByMs`, "invalid-release-deadline", "Release deadline violates the momentary bounds"); target(deckId, [`deck:${deckId}:cue`, `deck:${deckId}:jog`, `deck:${deckId}:transport`], true); if (!needs(deckId, `cue-available:${deckId}:main`)) issue(path, "missing-cue-condition", "Cue action requires a main-cue condition"); }
  else if (action === "deck.cue_release") { const r = object(value, path, ["kind", "action", "deckId", "args"]); literal(r.kind, "momentary", `${path}.kind`); if (authorityKind !== "release-cleanup" || !cleanupLease) issue(path, "invalid-authority-combination", "Cue release requires cleanup authority"); const deckId = id(r.deckId, `${path}.deckId`); const current = decks.get(deckId); if (!current || current.binding !== "loaded") issue(`${path}.deckId`, "missing-deck-precondition", "Cue release requires its current loaded deck precondition"); const a = object(r.args, `${path}.args`, ["marker", "lease"]); literal(a.marker, "main", `${path}.args.marker`); const operationLease = lease(a.lease, `${path}.args.lease`); if (operationLease.obligationId !== cleanupLease.obligationId || operationLease.pressActionId !== cleanupLease.pressActionId || operationLease.pressGeneration !== cleanupLease.pressGeneration) issue(`${path}.args.lease`, "lease-mismatch", "Cue release must exactly match cleanup authority lease"); }
  else if (action === "deck.jog") { const r = object(value, path, ["kind", "action", "deckId", "args"]); literal(r.kind, "relative", `${path}.kind`); const deckId = id(r.deckId, `${path}.deckId`); const a = object(r.args, `${path}.args`, ["unit", "delta"]); literal(a.unit, "beats", `${path}.args.unit`); const delta = number(a.delta, `${path}.args.delta`); if (delta === 0 || delta < -ACTION_LIMITS.maxRelativeJogBeats || delta > ACTION_LIMITS.maxRelativeJogBeats) issue(`${path}.args.delta`, "out-of-range", "Jog delta must be nonzero and bounded"); target(deckId, [`deck:${deckId}:jog`, `deck:${deckId}:transport`], true); }
  else issue(`${path}.action`, "unsupported-action", "Unknown semantic action");
  if (authorityKind === "release-cleanup" && action !== "deck.cue_release") issue(path, "invalid-authority-combination", "Cleanup authority can only release a cue lease");
}

/** Parses one closed F06 semantic action without reading or mutating external state. */
export function validateSemanticAction(input: unknown): ValidationResult<SemanticAction> {
  try {
    const r = object(external(input), "$", ["sessionId", "actionId", "sequence", "schemaVersion", "timing", "preconditions", "authority", "operation"]);
    id(r.sessionId, "$.sessionId"); const actionId = id(r.actionId, "$.actionId"); safeInteger(r.sequence, "$.sequence"); literal(r.schemaVersion, 1, "$.schemaVersion");
    const timingRecord = object(r.timing, "$.timing", ["clockId", "requestedAtMs", "notBeforeMs", "dispatchByMs", "observeByMs"]);
    id(timingRecord.clockId, "$.timing.clockId"); const requestedAt = time(timingRecord.requestedAtMs, "$.timing.requestedAtMs"); const notBefore = time(timingRecord.notBeforeMs, "$.timing.notBeforeMs"); const dispatchBy = time(timingRecord.dispatchByMs, "$.timing.dispatchByMs"); const observeBy = time(timingRecord.observeByMs, "$.timing.observeByMs");
    if (requestedAt > notBefore || notBefore > dispatchBy || dispatchBy > observeBy || dispatchBy - requestedAt > ACTION_LIMITS.maxDispatchHorizonMs || observeBy - requestedAt > ACTION_LIMITS.maxObservationHorizonMs) issue("$.timing", "invalid-timing-order", "Timing order or horizon is invalid");
    const decks = freshness(r.preconditions, "$.preconditions");
    const freshnessRecord = r.preconditions as JsonObject;
    if (time(freshnessRecord.stateObservedAtMs, "$.preconditions.stateObservedAtMs") > requestedAt) issue("$.preconditions.stateObservedAtMs", "invalid-state-time", "State observation cannot follow the request");
    const conditionMap = conditions(freshnessRecord.conditions, "$.preconditions.conditions", new Set(decks.keys()));
    const auth = authority(r.authority, "$.authority");
    operation(r.operation, "$.operation", decks, conditionMap, auth.ownership, actionId, auth.kind, auth.cleanupLease, { notBefore, dispatchBy, observeBy });
    return accepted(r as unknown as SemanticAction);
  } catch (error) { return rejected(error); }
}

function context(value: JsonObject, path: string): void {
  for (const key of ["sessionId", "hostInstanceId"] as const) id(value[key], `${path}.${key}`);
  for (const key of ["connectionGeneration", "capabilityRevision", "streamGeneration"] as const) safeInteger(value[key], `${path}.${key}`);
  id(value.clockId, `${path}.clockId`); id(value.streamId, `${path}.streamId`);
  const p = object(value.profile, `${path}.profile`, ["profileId", "profileRevision", "host", "version", "buildId", "platform", "skinId", "skinRevision", "configurationId"]);
  for (const key of ["profileId", "buildId", "skinId", "skinRevision", "configurationId"] as const) id(p[key], `${path}.profile.${key}`);
  safeInteger(p.profileRevision, `${path}.profile.profileRevision`); literal(p.host, "mixxx", `${path}.profile.host`); string(p.version, `${path}.profile.version`); oneOf(p.platform, new Set(["macos", "windows", "linux"]), `${path}.profile.platform`);
}

function evidence(value: unknown, path: string, state: JsonObject): { observedAtMs: number; validUntilMs: number } {
  const r = object(value, path, ["observationId", "hostInstanceId", "connectionGeneration", "stateRevision", "clockId", "observedAtMs", "receivedAtMs", "validUntilMs", "source", "attribution"]);
  for (const key of ["observationId", "hostInstanceId", "clockId"] as const) id(r[key], `${path}.${key}`);
  safeInteger(r.connectionGeneration, `${path}.connectionGeneration`); const revision = safeInteger(r.stateRevision, `${path}.stateRevision`); if (revision > Number(state.stateRevision)) issue(`${path}.stateRevision`, "future-revision", "Evidence revision cannot exceed message revision");
  if (r.hostInstanceId !== state.hostInstanceId || r.connectionGeneration !== state.connectionGeneration || r.clockId !== state.clockId) issue(path, "context-mismatch", "Current observation evidence must match state context");
  const observed = time(r.observedAtMs, `${path}.observedAtMs`); const received = time(r.receivedAtMs, `${path}.receivedAtMs`); const valid = time(r.validUntilMs, `${path}.validUntilMs`); if (observed > received || received > Number(state.producedAtMs) || observed >= valid) issue(path, "invalid-evidence-times", "Evidence timestamps are inconsistent");
  if (r.source === null || typeof r.source !== "object" || Array.isArray(r.source)) issue(`${path}.source`, "expected-object", "Expected evidence source");
  if ((r.source as JsonObject).kind === "host-reconciled") { const source = object(r.source, `${path}.source`, ["kind", "eventIds"]); nonemptyIds(source.eventIds, `${path}.source.eventIds`); }
  else { const source = object(r.source, `${path}.source`, ["kind", "eventId"]); oneOf(source.kind, new Set(["host-read", "host-feedback"]), `${path}.source.kind`); id(source.eventId, `${path}.source.eventId`); }
  attribution(r.attribution, `${path}.attribution`);
  return { observedAtMs: observed, validUntilMs: valid };
}

function observedValue(value: unknown, path: string): { kind: string; unit?: string } {
  if (value === null || typeof value !== "object" || Array.isArray(value)) issue(path, "expected-object", "Expected observed value");
  const kind = (value as JsonObject).kind;
  if (kind === "boolean") { const r = object(value, path, ["kind", "value"]); bool(r.value, `${path}.value`); return { kind }; }
  if (kind === "number") { const r = object(value, path, ["kind", "value", "unit"]); number(r.value, `${path}.value`); const unit = oneOf(r.unit, new Set(["normalized", "beats", "seconds", "bpm", "decibels", "ratio"]), `${path}.unit`); return { kind, unit }; }
  if (kind === "enum") { const r = object(value, path, ["kind", "value"]); id(r.value, `${path}.value`); return { kind }; }
  if (kind === "track-identity") { const r = object(value, path, ["kind", "value"]); track(r.value, `${path}.value`); return { kind }; }
  if (kind === "occurrence-identity") { const r = object(value, path, ["kind", "value"]); occurrence(r.value, `${path}.value`); return { kind }; }
  issue(`${path}.kind`, "invalid-value-kind", "Unknown observed value kind");
}

function observation(value: unknown, path: string, state: JsonObject, rules?: CapabilityReferenceRules): void {
  if (value === null || typeof value !== "object" || Array.isArray(value)) issue(path, "expected-object", "Expected observation");
  const status = (value as JsonObject).status;
  if (status === "observed") { const r = object(value, path, ["status", "value", "evidence"]); const actual = observedValue(r.value, `${path}.value`); const times = evidence(r.evidence, `${path}.evidence`, state); if (rules) { validateValueRules(r.value, actual, rules, `${path}.value`); if (!Number.isFinite(rules.maxAgeMs) || rules.maxAgeMs <= 0 || times.validUntilMs - times.observedAtMs > rules.maxAgeMs) issue(`${path}.evidence.validUntilMs`, "catalog-age-mismatch", "Observation lifetime exceeds the catalog maximum age"); } return; }
  if (status === "stale") { const r = object(value, path, ["status", "lastKnown", "reason"]); const last = object(r.lastKnown, `${path}.lastKnown`, ["value", "evidence"]); const actual = observedValue(last.value, `${path}.lastKnown.value`); const times = evidence(last.evidence, `${path}.lastKnown.evidence`, state); if (rules) { validateValueRules(last.value, actual, rules, `${path}.lastKnown.value`); if (!Number.isFinite(rules.maxAgeMs) || rules.maxAgeMs <= 0 || times.validUntilMs - times.observedAtMs > rules.maxAgeMs) issue(`${path}.lastKnown.evidence.validUntilMs`, "catalog-age-mismatch", "Observation lifetime exceeds the catalog maximum age"); } oneOf(r.reason, stateReasons, `${path}.reason`); return; }
  if (status === "missing") { const r = object(value, path, ["status", "reason", "presenceEvidenceIds"]); oneOf(r.reason, new Set(["control-absent", "instance-absent"]), `${path}.reason`); nonemptyIds(r.presenceEvidenceIds, `${path}.presenceEvidenceIds`); return; }
  if (status === "unknown") { const r = object(value, path, ["status", "reason"]); oneOf(r.reason, unknownReasons, `${path}.reason`); return; }
  if (status === "uncertain") { const r = object(value, path, ["status", "reason", "evidenceIds"]); oneOf(r.reason, uncertainReasons, `${path}.reason`); nonemptyIds(r.evidenceIds, `${path}.evidenceIds`); return; }
  issue(`${path}.status`, "invalid-observation", "Unknown observation status");
}

function validateValueRules(raw: unknown, actual: { kind: string; unit?: string }, rules: CapabilityReferenceRules, path: string): void {
  if (actual.kind !== rules.value.kind) issue(path, "catalog-value-kind-mismatch", "Reading does not match the resolved capability value kind");
  if (rules.value.kind === "number") { if (actual.unit !== rules.value.unit) issue(`${path}.unit`, "catalog-unit-mismatch", "Reading unit does not match the catalog"); const v = Number((raw as JsonObject).value); if (v < rules.value.minimum || v > rules.value.maximum) issue(`${path}.value`, "catalog-range-mismatch", "Reading is outside the catalog range"); }
  if (rules.value.kind === "enum" && !rules.value.values.includes(String((raw as JsonObject).value))) issue(`${path}.value`, "catalog-enum-mismatch", "Reading is not a catalog enum value");
}

function target(value: unknown, path: string): CapabilityReference {
  const r = object(value, path, ["capabilityId", "instance"]);
  const capabilityId = id(r.capabilityId, `${path}.capabilityId`);
  if (!capabilityId.startsWith("mixxx.")) issue(`${path}.capabilityId`, "invalid-capability-id", "Capability IDs must start with mixxx.");
  if (r.instance === null) return { capabilityId: capabilityId as `mixxx.${string}`, instance: null };
  const i = object(r.instance, `${path}.instance`, ["instanceId", "generation", "kind", "parent", "definitionId"]);
  id(i.instanceId, `${path}.instance.instanceId`); safeInteger(i.generation, `${path}.instance.generation`); oneOf(i.kind, featureKinds, `${path}.instance.kind`); id(i.definitionId, `${path}.instance.definitionId`);
  if (i.parent !== null) { const p = object(i.parent, `${path}.instance.parent`, ["instanceId", "generation"]); id(p.instanceId, `${path}.instance.parent.instanceId`); safeInteger(p.generation, `${path}.instance.parent.generation`); }
  return r as unknown as CapabilityReference;
}

function reading(value: unknown, path: string, state: JsonObject, refs: StateValidationReferences | undefined): void {
  const r = object(value, path, ["target", "deck", "observation"]); const cap = target(r.target, `${path}.target`); const rules = refs?.resolveCapability(cap);
  if (!rules) issue(`${path}.target`, "unresolved-capability-reference", "State reading requires an explicit current catalog resolution");
  if (r.deck !== null) {
    if ((r.deck as JsonObject).kind === "known") { const d = object(r.deck, `${path}.deck`, ["kind", "precondition"]); const pre = deckPrecondition(d.precondition, `${path}.deck.precondition`); if (pre.binding !== "loaded" && (r.observation as JsonObject).status === "observed") issue(`${path}.deck`, "invalid-deck-binding", "Observed deck reading requires a known loaded binding"); }
    else { const d = object(r.deck, `${path}.deck`, ["kind", "deckId", "deckGeneration"]); literal(d.kind, "unknown", `${path}.deck.kind`); id(d.deckId, `${path}.deck.deckId`); safeInteger(d.deckGeneration, `${path}.deck.deckGeneration`); if ((r.observation as JsonObject).status === "observed") issue(`${path}.observation`, "unknown-deck-observed", "Unknown deck context cannot carry an observed value"); }
  }
  observation(r.observation, `${path}.observation`, state, rules);
}

function deckObservation(value: unknown, path: string, state: JsonObject): { deckId: string; deckGeneration: number } {
  const r = object(value, path, ["deckId", "deckGeneration", "current"]); const deckId = id(r.deckId, `${path}.deckId`); const generation = safeInteger(r.deckGeneration, `${path}.deckGeneration`); observation(r.current, `${path}.current`, state);
  if ((r.current as JsonObject).status === "observed") { const pre = ((r.current as JsonObject).value) as JsonObject; if (pre.deckId !== deckId || pre.deckGeneration !== generation) issue(`${path}.current.value`, "deck-context-mismatch", "Observed deck precondition must match its enclosing deck"); deckPrecondition(pre, `${path}.current.value`); }
  return { deckId, deckGeneration: generation };
}

/** Parses one F07 snapshot or delta. It deliberately does not apply, order, or reconcile it. */
export function validateObservedStateMessage(input: unknown, references?: StateValidationReferences): ValidationResult<ObservedStateMessage> {
  try {
    const raw = external(input);
    if (raw === null || typeof raw !== "object" || Array.isArray(raw)) issue("$", "expected-object", "Expected a state message");
    const kind = (raw as JsonObject).kind;
    const fields = kind === "snapshot"
      ? ["sessionId", "hostInstanceId", "connectionGeneration", "capabilityRevision", "profile", "clockId", "streamId", "streamGeneration", "schemaVersion", "messageId", "sequence", "producedAtMs", "stateRevision", "kind", "snapshotId", "replacement", "decks", "readings"]
      : kind === "delta"
        ? ["sessionId", "hostInstanceId", "connectionGeneration", "capabilityRevision", "profile", "clockId", "streamId", "streamGeneration", "schemaVersion", "messageId", "sequence", "producedAtMs", "stateRevision", "kind", "snapshotId", "baseRevision", "previousSequence", "changes"]
        : issue("$.kind", "invalid-state-kind", "State message must be snapshot or delta");
    const r = object(raw, "$", fields); context(r, "$"); literal(r.schemaVersion, 1, "$.schemaVersion"); id(r.messageId, "$.messageId"); safeInteger(r.sequence, "$.sequence"); time(r.producedAtMs, "$.producedAtMs"); safeInteger(r.stateRevision, "$.stateRevision"); id(r.snapshotId, "$.snapshotId");
    if (kind === "snapshot") {
      literal(r.replacement, "entire-context", "$.replacement"); const deckKeys = new Set<string>(); for (const [index, entry] of array(r.decks, "$.decks").entries()) { const deck = deckObservation(entry, `$.decks[${index}]`, r); const key = `${deck.deckId}:${deck.deckGeneration}`; if (deckKeys.has(key)) issue(`$.decks[${index}]`, "duplicate-deck", "Snapshot decks must be unique"); deckKeys.add(key); }
      const readingKeys = new Set<string>(); for (const [index, entry] of array(r.readings, "$.readings").entries()) { const record = object(entry, `$.readings[${index}]`, ["target", "deck", "observation"]); const cap = target(record.target, `$.readings[${index}].target`); const key = `${cap.capabilityId}:${JSON.stringify(cap.instance)}`; if (readingKeys.has(key)) issue(`$.readings[${index}]`, "duplicate-reading", "Snapshot readings must be unique"); readingKeys.add(key); reading(entry, `$.readings[${index}]`, r, references); }
    } else {
      const base = safeInteger(r.baseRevision, "$.baseRevision"); const previous = safeInteger(r.previousSequence, "$.previousSequence"); if (r.sequence !== previous + 1 || r.stateRevision !== base + 1) issue("$", "invalid-delta-lineage", "Delta requires immediate sequence and revision lineage");
      const baseline = references?.baseline;
      if (!baseline) issue("$", "baseline-required", "Delta admission requires an explicit current immutable baseline");
      if (baseline.snapshotId !== r.snapshotId || baseline.stateRevision !== base || baseline.sequence !== previous
        || baseline.sessionId !== r.sessionId || baseline.hostInstanceId !== r.hostInstanceId
        || baseline.connectionGeneration !== r.connectionGeneration || baseline.capabilityRevision !== r.capabilityRevision
        || baseline.clockId !== r.clockId || baseline.streamId !== r.streamId || baseline.streamGeneration !== r.streamGeneration) {
        issue("$", "baseline-mismatch", "Delta context or lineage does not match the supplied baseline");
      }
      const changed = new Set<string>(); for (const [index, entry] of array(r.changes, "$.changes").entries()) { stateChange(entry, `$.changes[${index}]`, r, references, changed); }
    }
    return accepted(r as unknown as ObservedStateMessage);
  } catch (error) { return rejected(error); }
}

function stateChange(value: unknown, path: string, state: JsonObject, refs: StateValidationReferences | undefined, changed: Set<string>): void {
  if (value === null || typeof value !== "object" || Array.isArray(value)) issue(path, "expected-object", "Expected state change");
  const kind = (value as JsonObject).kind;
  let key: string;
  if (kind === "replace-deck") { const r = object(value, path, ["kind", "deck"]); const deck = deckObservation(r.deck, `${path}.deck`, state); key = `deck:${deck.deckId}:${deck.deckGeneration}`; }
  else if (kind === "remove-deck") { const r = object(value, path, ["kind", "deckId", "deckGeneration", "evidenceIds"]); key = `deck:${id(r.deckId, `${path}.deckId`)}:${safeInteger(r.deckGeneration, `${path}.deckGeneration`)}`; nonemptyIds(r.evidenceIds, `${path}.evidenceIds`); }
  else if (kind === "replace-reading") { const r = object(value, path, ["kind", "reading"]); const read = object(r.reading, `${path}.reading`, ["target", "deck", "observation"]); const cap = target(read.target, `${path}.reading.target`); key = `reading:${cap.capabilityId}:${JSON.stringify(cap.instance)}`; reading(r.reading, `${path}.reading`, state, refs); }
  else if (kind === "remove-reading") { const r = object(value, path, ["kind", "target", "evidenceIds"]); const cap = target(r.target, `${path}.target`); key = `reading:${cap.capabilityId}:${JSON.stringify(cap.instance)}`; nonemptyIds(r.evidenceIds, `${path}.evidenceIds`); }
  else issue(`${path}.kind`, "invalid-change", "Unknown state change");
  if (changed.has(key)) issue(path, "duplicate-change", "A delta cannot change one key twice"); changed.add(key);
}

function accepted<T>(value: T): ValidationResult<T> { return { ok: true, value: freezeCopy(value) }; }
function rejected(error: unknown): ValidationResult<never> { return { ok: false, errors: [error instanceof Invalid ? error.detail : { path: "$", code: "validation-error", message: "Validation failed" }] }; }
function freezeCopy<T>(value: T): T { return deepFreeze(structuredClone(value)); }
function deepFreeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value as Record<string, unknown>)) deepFreeze(child); } return value; }

export function validateActionOutcome(input: unknown): ValidationResult<ActionOutcome> {
  try {
    const raw = external(input);
    if (raw === null || typeof raw !== "object" || Array.isArray(raw)) issue("$", "expected-object", "Expected an action outcome");
    const status = string((raw as JsonObject).status, "$.status");
    const base = ["sessionId", "actionId", "sequence", "schemaVersion", "eventId", "clockId", "atMs", "status"];
    const r = object(raw, "$", status === "requested" ? base
      : status === "sent" ? [...base, "attemptId", "transportMessageIds"]
        : status === "accepted" ? [...base, "attemptId", "hostReceiptId"]
          : status === "observed" ? [...base, "observation", "condition", "correlation", "attribution"]
            : status === "uncertain" ? [...base, "attemptId", "reason"]
              : status === "rejected" ? [...base, "stage", "reason"]
                : status === "cancelled" ? [...base, "reason"]
                  : status === "expired" ? [...base, "phase"]
                    : issue("$.status", "invalid-outcome-status", "Unknown action outcome status"));
    for (const key of ["sessionId", "actionId", "eventId", "clockId"] as const) id(r[key], `$.${key}`); safeInteger(r.sequence, "$.sequence"); literal(r.schemaVersion, 1, "$.schemaVersion"); time(r.atMs, "$.atMs");
    if (status === "sent") { id(r.attemptId, "$.attemptId"); nonemptyIds(r.transportMessageIds, "$.transportMessageIds", ACTION_LIMITS.maxTransportMessageIds); }
    else if (status === "accepted") { id(r.attemptId, "$.attemptId"); id(r.hostReceiptId, "$.hostReceiptId"); }
    else if (status === "observed") { const o = object(r.observation, "$.observation", ["observationId", "hostInstanceId", "connectionGeneration", "stateRevision"]); id(o.observationId, "$.observation.observationId"); id(o.hostInstanceId, "$.observation.hostInstanceId"); safeInteger(o.connectionGeneration, "$.observation.connectionGeneration"); safeInteger(o.stateRevision, "$.observation.stateRevision"); oneOf(r.condition, new Set(["satisfied", "not-satisfied"]), "$.condition"); if ((r.correlation as JsonObject).kind === "state-only") object(r.correlation, "$.correlation", ["kind"]); else { const c = object(r.correlation, "$.correlation", ["kind", "hostReceiptId"]); literal(c.kind, "request-linked", "$.correlation.kind"); id(c.hostReceiptId, "$.correlation.hostReceiptId"); } attribution(r.attribution, "$.attribution"); }
    else if (status === "uncertain") { if (r.attemptId !== null) id(r.attemptId, "$.attemptId"); oneOf(r.reason, new Set(["send-result-unknown", "acceptance-missing", "observation-timeout", "feedback-lost", "ambiguous-correlation", "release-unconfirmed"]), "$.reason"); }
    else if (status === "rejected") { oneOf(r.stage, new Set(["validation", "authority", "host"]), "$.stage"); oneOf(r.reason, new Set(["invalid-data", "unsupported-action", "stale-context", "precondition-failed", "authority-denied", "host-rejected"]), "$.reason"); }
    else if (status === "cancelled") oneOf(r.reason, new Set(["disarm", "mode-changed", "human-takeover", "manual-stop", "track-changed", "plan-replaced", "connection-lost", "operator-cancelled"]), "$.reason");
    else if (status === "expired") oneOf(r.phase, new Set(["dispatch", "observation"]), "$.phase");
    return accepted(r as unknown as ActionOutcome);
  } catch (error) { return rejected(error); }
}

/** Validates a stored press cleanup record without emitting a release. */
export function validateMomentaryReleaseObligation(input: unknown): ValidationResult<MomentaryReleaseObligation> {
  try {
    const r = object(external(input), "$", ["obligationId", "pressActionId", "pressGeneration", "sessionId", "hostInstanceId", "connectionGeneration", "deck", "control", "clockId", "releaseByMs", "evidence"]);
    for (const key of ["obligationId", "pressActionId", "sessionId", "hostInstanceId", "clockId"] as const) id(r[key], `$.${key}`); safeInteger(r.pressGeneration, "$.pressGeneration"); safeInteger(r.connectionGeneration, "$.connectionGeneration"); if (deckPrecondition(r.deck, "$.deck").binding !== "loaded") issue("$.deck", "invalid-release-binding", "A release obligation requires the pressed loaded track"); literal(r.control, "cue", "$.control"); time(r.releaseByMs, "$.releaseByMs");
    if ((r.evidence as JsonObject).kind === "sent-unconfirmed") { const e = object(r.evidence, "$.evidence", ["kind", "attemptId"]); id(e.attemptId, "$.evidence.attemptId"); } else { const e = object(r.evidence, "$.evidence", ["kind", "hostReceiptId"]); literal(e.kind, "acknowledged-active", "$.evidence.kind"); id(e.hostReceiptId, "$.evidence.hostReceiptId"); }
    return accepted(r as unknown as MomentaryReleaseObligation);
  } catch (error) { return rejected(error); }
}

// End of autonomously AI-generated validator.
