// This validator was autonomously generated by an AI agent at the user's request.
// It is a data-admission boundary; it neither sends actions nor reconciles state.

import { ACTION_LIMITS, type ActionOutcome, type MomentaryReleaseObligation, type SemanticAction } from "./actions.ts";
import type { CapabilityContext, CapabilityInstance, CapabilityReadSemantics, CapabilityReference } from "./capabilities.ts";
import type { ObservedStateMessage, StateSnapshot } from "./state.ts";

export const VALIDATION_LIMITS = {
  maxTransportBytes: 65_536,
  maxDepth: 32,
  maxNodes: 4_096,
  maxStringUtf8Bytes: 4_096,
  maxStateEntries: 256,
  maxEvidenceIds: 64,
  maxObjectKeys: 64,
} as const;

export interface ValidationError {
  readonly path: string;
  readonly code: string;
  readonly message: string;
}

export type ValidationResult<T> =
  | { readonly ok: true; readonly value: T }
  | { readonly ok: false; readonly errors: readonly ValidationError[] };

/** A trusted catalog projection, supplied as data, never a callable resolver. */
export type StatePresence =
  | { readonly status: "present" | "absent"; readonly evidenceIds: readonly string[] }
  | { readonly status: "unknown"; readonly reason: string };

export interface CapabilityReferenceRules {
  readonly target: CapabilityReference;
  readonly read: CapabilityReadSemantics;
  readonly availability: StatePresence;
  readonly applicableDeck: { readonly deckId: string; readonly deckGeneration: number } | null;
}

export interface StateCatalogReference extends CapabilityContext {
  readonly schemaVersion: 1;
  readonly catalogId: string;
  readonly instances: readonly CapabilityInstance[];
  readonly entries: readonly CapabilityReferenceRules[];
  readonly decks: readonly {
    readonly deckId: string;
    readonly deckGeneration: number;
    readonly availability: StatePresence;
    readonly maxAgeMs: number;
  }[];
  readonly retainedEvidenceIds: readonly string[];
}

export interface StateValidationReferences {
  readonly catalog: StateCatalogReference;
  /** Complete last accepted projection, with its latest sequence/message/revision. */
  readonly baseline?: StateSnapshot;
  /** Required when a replacement snapshot moves to a different catalog context. */
  readonly baselineCatalog?: StateCatalogReference;
}

class Invalid extends Error {
  readonly detail: ValidationError;
  constructor(detail: ValidationError) {
    super(detail.message);
    this.detail = detail;
  }
}

type JsonObject = Record<string, unknown>;
const opaqueId = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}(?![\s\S])/;
const deckParameters = new Set(["volume", "eq.low", "eq.mid", "eq.high"]);
const stateReasons = new Set(["age-expired", "connection-changed", "identity-changed", "profile-changed", "stream-gap"]);
const unknownReasons = new Set(["not-observed", "existence-unverified", "feedback-unavailable", "identity-unresolved"]);
const uncertainReasons = new Set(["conflicting-feedback", "ordering-gap", "clock-unmapped", "binding-ambiguous"]);
const featureKinds = new Set(["deck", "sampler", "preview-deck", "stem", "effect-unit", "effect-slot", "effect-parameter", "input", "service"]);

function issue(path: string, code: string, message: string): never {
  throw new Invalid({ path, code, message });
}

function bytes(value: string): number {
  return new TextEncoder().encode(value).byteLength;
}

function preflight(value: unknown, path = "$", depth = 0, seen = new Set<object>(), count = { value: 0 }): void {
  if (depth > VALIDATION_LIMITS.maxDepth) issue(path, "too-deep", "Input exceeds the nesting limit");
  count.value += 1;
  if (count.value > VALIDATION_LIMITS.maxNodes) issue(path, "too-many-nodes", "Input exceeds the node limit");
  if (value === null || typeof value === "boolean" || typeof value === "number") {
    if (typeof value === "number" && !Number.isFinite(value)) issue(path, "non-finite", "Numbers must be finite JSON numbers");
    return;
  }
  if (typeof value === "string") {
    if (bytes(value) > VALIDATION_LIMITS.maxStringUtf8Bytes) issue(path, "string-too-large", "String exceeds the byte limit");
    return;
  }
  if (typeof value !== "object") issue(path, "non-json", "Input contains a non-JSON value");
  if (seen.has(value)) issue(path, "recursive", "Input must not contain recursive objects");
  const keys = Reflect.ownKeys(value);
  const keyLimit = Array.isArray(value) ? VALIDATION_LIMITS.maxStateEntries + 1 : VALIDATION_LIMITS.maxObjectKeys;
  if (keys.length > keyLimit) issue(path, "too-many-keys", "Record exceeds its key limit");
  for (const key of keys) {
    if (typeof key !== "string") issue(path, "non-json", "Symbol keys are not JSON");
    if (bytes(key) > ACTION_LIMITS.maxIdUtf8Bytes) issue(path, "key-too-large", "Key exceeds its byte limit");
    const descriptor = Object.getOwnPropertyDescriptor(value, key);
    if (!descriptor || !("value" in descriptor) || (!descriptor.enumerable && !(Array.isArray(value) && key === "length"))) {
      issue(path, "non-json", "Accessors and hidden properties are not JSON");
    }
  }
  seen.add(value);
  if (Array.isArray(value)) {
    if (Object.getPrototypeOf(value) !== Array.prototype) issue(path, "non-json", "Arrays must use the ordinary JSON array prototype");
    if (value.length > VALIDATION_LIMITS.maxStateEntries) issue(path, "array-too-large", "Array exceeds the collection limit");
    for (const key of Object.keys(value)) if (!/^(0|[1-9][0-9]*)$/.test(key)) issue(`${path}.${key}`, "non-json", "Arrays cannot carry named properties");
    for (let index = 0; index < value.length; index += 1) {
      const descriptor = Object.getOwnPropertyDescriptor(value, String(index));
      if (!descriptor || !("value" in descriptor)) issue(`${path}[${index}]`, "non-json", "Arrays cannot contain holes or accessors");
      preflight(descriptor.value, `${path}[${index}]`, depth + 1, seen, count);
    }
  } else {
    const prototype = Object.getPrototypeOf(value);
    if (prototype !== Object.prototype && prototype !== null) issue(path, "not-plain-object", "Records must be plain JSON objects");
    for (const key of Object.keys(value)) {
      const descriptor = Object.getOwnPropertyDescriptor(value, key);
      if (!descriptor || !("value" in descriptor)) issue(`${path}.${key}`, "non-json", "Records cannot contain accessors");
      preflight(descriptor.value, `${path}.${key}`, depth + 1, seen, count);
    }
  }
  seen.delete(value);
}

function external(value: unknown): unknown {
  if (typeof value === "string") {
    if (value.length > VALIDATION_LIMITS.maxTransportBytes) issue("$", "payload-too-large", "Transport payload exceeds its byte limit");
    if (bytes(value) > VALIDATION_LIMITS.maxTransportBytes) issue("$", "payload-too-large", "Transport payload exceeds 65536 UTF-8 bytes");
    let nesting = 0;
    let quoted = false;
    let escaped = false;
    let stringStart = 0;
    const objectKeys: Array<Set<string> | null> = [];
    for (let index = 0; index < value.length; index += 1) {
      const character = value[index];
      if (quoted) {
        if (escaped) escaped = false;
        else if (character === "\\") escaped = true;
        else if (character === '"') {
          quoted = false;
          let next = index + 1;
          while (next < value.length && /\s/.test(value[next]!)) next += 1;
          const keys = objectKeys.at(-1);
          if (value[next] === ":" && keys) {
            let key: unknown;
            try { key = JSON.parse(value.slice(stringStart, index + 1)); }
            catch { issue("$", "invalid-json", "Input has an invalid JSON property name"); }
            if (typeof key !== "string") issue("$", "invalid-json", "Expected a string property name");
            if (keys.has(key)) issue("$", "duplicate-json-key", "JSON object keys must be unique after unescaping");
            keys.add(key);
            if (keys.size > VALIDATION_LIMITS.maxObjectKeys) issue("$", "too-many-keys", "JSON record exceeds its key limit");
          }
        }
      } else if (character === '"') { quoted = true; stringStart = index; }
      else if (character === "{" || character === "[") {
        nesting += 1;
        objectKeys.push(character === "{" ? new Set<string>() : null);
        if (nesting > VALIDATION_LIMITS.maxDepth) issue("$", "too-deep", "JSON nesting exceeds the pre-parse limit");
      } else if (character === "}" || character === "]") { nesting -= 1; objectKeys.pop(); }
    }
    try {
      const parsed: unknown = JSON.parse(value);
      preflight(parsed);
      return parsed;
    } catch (error) {
      if (error instanceof Invalid) throw error;
      issue("$", "invalid-json", "Input is not valid JSON");
    }
  }
  preflight(value);
  let serialized: string;
  try {
    serialized = JSON.stringify(value);
  } catch {
    issue("$", "non-json", "Input cannot be serialized as JSON");
  }
  if (bytes(serialized) > VALIDATION_LIMITS.maxTransportBytes) issue("$", "payload-too-large", "Transport payload exceeds 65536 UTF-8 bytes");
  return value;
}

function referenceBundle(value: unknown): JsonObject {
  if (!value || typeof value !== "object" || Array.isArray(value)) issue("$references", "expected-object", "Expected a reference bundle");
  const prototype = Object.getPrototypeOf(value);
  if (prototype !== Object.prototype && prototype !== null) issue("$references", "not-plain-object", "Reference bundle must be a plain object");
  const allowed = new Set(["catalog", "baseline", "baselineCatalog"]);
  const keys = Reflect.ownKeys(value);
  if (keys.length > allowed.size) issue("$references", "too-many-keys", "Reference bundle has at most three components");
  const result: JsonObject = {};
  for (const key of keys) {
    if (typeof key !== "string") issue("$references", "non-json", "Reference bundle cannot have symbol keys");
    const descriptor = Object.getOwnPropertyDescriptor(value, key);
    if (!descriptor || !("value" in descriptor) || !descriptor.enumerable) issue("$references", "non-json", "Reference bundle cannot have accessors or hidden fields");
    if (!allowed.has(key)) issue(`$references.${key}`, "unknown-field", "Unknown reference component");
    result[key] = freezeCopy(external(descriptor.value));
  }
  if (!Object.hasOwn(result, "catalog")) issue("$references.catalog", "missing-field", "Current catalog is required");
  return Object.freeze(result);
}

function object(value: unknown, path: string, fields: readonly string[]): JsonObject {
  if (value === null || typeof value !== "object" || Array.isArray(value)) issue(path, "expected-object", "Expected a JSON object");
  const record = value as JsonObject;
  const allowed = new Set(fields);
  for (const key of Object.keys(record)) if (!allowed.has(key)) issue(`${path}.${key}`, "unknown-field", "Unknown field");
  for (const key of fields) if (!Object.hasOwn(record, key)) issue(`${path}.${key}`, "missing-field", "Required field is absent");
  return record;
}

function string(value: unknown, path: string): string {
  if (typeof value !== "string") issue(path, "expected-string", "Expected a string");
  return value;
}

function id(value: unknown, path: string): string {
  const result = string(value, path);
  if (!opaqueId.test(result) || bytes(result) > ACTION_LIMITS.maxIdUtf8Bytes) issue(path, "invalid-id", "Expected a bounded opaque ID");
  return result;
}

function literal<T extends string | number | boolean>(value: unknown, expected: T, path: string): T {
  if (value !== expected) issue(path, "invalid-literal", `Expected ${String(expected)}`);
  return expected;
}

function oneOf(value: unknown, allowed: ReadonlySet<string>, path: string): string {
  const result = string(value, path);
  if (!allowed.has(result)) issue(path, "invalid-enum", "Unknown enum value");
  return result;
}

function safeInteger(value: unknown, path: string): number {
  if (typeof value !== "number" || !Number.isSafeInteger(value) || value < 0) issue(path, "invalid-generation", "Expected a nonnegative safe integer");
  return value;
}

function time(value: unknown, path: string): number {
  if (typeof value !== "number" || !Number.isFinite(value) || value < 0 || value > Number.MAX_SAFE_INTEGER) issue(path, "invalid-time", "Expected a finite monotonic millisecond value");
  return value;
}

function number(value: unknown, path: string): number {
  if (typeof value !== "number" || !Number.isFinite(value)) issue(path, "invalid-number", "Expected a finite number");
  return value;
}

function bool(value: unknown, path: string): boolean {
  if (typeof value !== "boolean") issue(path, "expected-boolean", "Expected a boolean");
  return value;
}

function array(value: unknown, path: string, maximum: number = VALIDATION_LIMITS.maxStateEntries): unknown[] {
  if (!Array.isArray(value)) issue(path, "expected-array", "Expected an array");
  if (value.length > maximum) issue(path, "array-too-large", "Array exceeds its contract limit");
  return value;
}

function nonemptyIds(value: unknown, path: string, maximum: number = VALIDATION_LIMITS.maxEvidenceIds): string[] {
  const values = array(value, path, maximum).map((entry, index) => id(entry, `${path}[${index}]`));
  if (values.length === 0) issue(path, "empty-array", "At least one ID is required");
  if (new Set(values).size !== values.length) issue(path, "duplicate", "IDs must be distinct");
  return values;
}

function track(value: unknown, path: string): void {
  const record = object(value, path, ["libraryId", "trackId"]);
  id(record.libraryId, `${path}.libraryId`); id(record.trackId, `${path}.trackId`);
}

function occurrence(value: unknown, path: string): void {
  const record = object(value, path, ["setId", "occurrenceId", "generation"]);
  id(record.setId, `${path}.setId`); id(record.occurrenceId, `${path}.occurrenceId`); safeInteger(record.generation, `${path}.generation`);
}

function binding(value: unknown, path: string): "empty" | "loaded" {
  if (value === null || typeof value !== "object" || Array.isArray(value)) issue(path, "expected-object", "Expected a track binding");
  const kind = (value as JsonObject).kind;
  if (kind === "empty") { object(value, path, ["kind"]); return "empty"; }
  if (kind !== "loaded") issue(`${path}.kind`, "invalid-binding", "Unknown track binding kind");
  const record = object(value, path, ["kind", "track", "occurrence"]);
  track(record.track, `${path}.track`);
  if (record.occurrence !== null) occurrence(record.occurrence, `${path}.occurrence`);
  return "loaded";
}

function deckPrecondition(value: unknown, path: string): { deckId: string; deckGeneration: number; trackGeneration: number; binding: "empty" | "loaded" } {
  const record = object(value, path, ["deckId", "deckGeneration", "trackGeneration", "binding"]);
  return { deckId: id(record.deckId, `${path}.deckId`), deckGeneration: safeInteger(record.deckGeneration, `${path}.deckGeneration`), trackGeneration: safeInteger(record.trackGeneration, `${path}.trackGeneration`), binding: binding(record.binding, `${path}.binding`) };
}

function attribution(value: unknown, path: string): void {
  if (value === null || typeof value !== "object" || Array.isArray(value)) issue(path, "expected-object", "Expected attribution");
  const actor = (value as JsonObject).actor;
  if (actor === "unknown") { object(value, path, ["actor"]); return; }
  if (actor !== "ai" && actor !== "human") issue(`${path}.actor`, "invalid-actor", "Unknown actor");
  const record = object(value, path, ["actor", "sourceId", "evidenceEventId"]);
  id(record.sourceId, `${path}.sourceId`); id(record.evidenceEventId, `${path}.evidenceEventId`);
}

function lease(value: unknown, path: string): { obligationId: string; pressActionId: string; pressGeneration: number } {
  const record = object(value, path, ["obligationId", "pressActionId", "pressGeneration"]);
  return { obligationId: id(record.obligationId, `${path}.obligationId`), pressActionId: id(record.pressActionId, `${path}.pressActionId`), pressGeneration: safeInteger(record.pressGeneration, `${path}.pressGeneration`) };
}

function conditions(value: unknown, path: string, deckIds?: ReadonlySet<string>): Map<string, Set<string>> {
  const result = new Map<string, Set<string>>();
  const playing = new Map<string, boolean>();
  for (const [index, entry] of array(value, path, ACTION_LIMITS.maxHostConditions).entries()) {
    if (entry === null || typeof entry !== "object" || Array.isArray(entry)) issue(`${path}[${index}]`, "expected-object", "Expected host condition");
    const kind = (entry as JsonObject).kind;
    let deckId: string;
    if (kind === "deck-playing") { const r = object(entry, `${path}[${index}]`, ["kind", "deckId", "playing"]); deckId = id(r.deckId, `${path}[${index}].deckId`); bool(r.playing, `${path}[${index}].playing`); }
    else if (kind === "deck-silent") { const r = object(entry, `${path}[${index}]`, ["kind", "deckId"]); deckId = id(r.deckId, `${path}[${index}].deckId`); }
    else if (kind === "cue-available") { const r = object(entry, `${path}[${index}]`, ["kind", "deckId", "marker"]); deckId = id(r.deckId, `${path}[${index}].deckId`); literal(r.marker, "main", `${path}[${index}].marker`); }
    else issue(`${path}[${index}].kind`, "invalid-condition", "Unknown host condition");
    if (deckIds && !deckIds.has(deckId)) issue(`${path}[${index}].deckId`, "dangling-condition-deck", "Conditions require a declared deck precondition");
    if (kind === "deck-playing") {
      const value = (entry as JsonObject).playing as boolean;
      const prior = playing.get(deckId);
      if (prior !== undefined && prior !== value) issue(`${path}[${index}]`, "conflicting-condition", "Deck playing conditions cannot conflict");
      playing.set(deckId, value);
    }
    const key = kind === "deck-playing" ? `deck-playing:${deckId}:${String((entry as JsonObject).playing)}`
      : kind === "deck-silent" ? `deck-silent:${deckId}`
        : `cue-available:${deckId}:main`;
    if (result.get(deckId)?.has(key)) issue(`${path}[${index}]`, "duplicate-condition", "Duplicate host condition");
    (result.get(deckId) ?? result.set(deckId, new Set()).get(deckId)!).add(key);
  }
  return result;
}

function controlResource(value: unknown, path: string): string {
  if (value === null || typeof value !== "object" || Array.isArray(value)) issue(path, "expected-object", "Expected control resource");
  const kind = (value as JsonObject).kind;
  if (kind === "deck") { const r = object(value, path, ["kind", "deckId", "control"]); const deck = id(r.deckId, `${path}.deckId`); oneOf(r.control, new Set(["transport", "track", "cue", "jog"]), `${path}.control`); return `${kind}:${deck}:${String(r.control)}`; }
  if (kind === "deck-parameter") { const r = object(value, path, ["kind", "deckId", "parameter"]); const deck = id(r.deckId, `${path}.deckId`); oneOf(r.parameter, deckParameters, `${path}.parameter`); return `${kind}:${deck}:${String(r.parameter)}`; }
  if (kind === "mixer-parameter") { const r = object(value, path, ["kind", "parameter"]); literal(r.parameter, "crossfader", `${path}.parameter`); return "mixer-parameter:crossfader"; }
  issue(`${path}.kind`, "invalid-resource", "Unknown control resource");
}

function authority(value: unknown, path: string): { kind: "performance" | "release-cleanup"; ownership: Set<string>; cleanupLease?: { obligationId: string; pressActionId: string; pressGeneration: number } } {
  if (value === null || typeof value !== "object" || Array.isArray(value)) issue(path, "expected-object", "Expected authority");
  if ((value as JsonObject).kind === "release-cleanup") { const r = object(value, path, ["kind", "lease"]); return { kind: "release-cleanup", ownership: new Set(), cleanupLease: lease(r.lease, `${path}.lease`) }; }
  const r = object(value, path, ["kind", "mode", "modeGeneration", "armingGeneration", "authorityRevision", "planId", "planRevision", "cancellationGroupId", "cancellationGeneration", "transition", "ownership"]);
  literal(r.kind, "performance", `${path}.kind`); oneOf(r.mode, new Set(["AIOnly", "B2B"]), `${path}.mode`);
  for (const key of ["modeGeneration", "armingGeneration", "authorityRevision", "planRevision", "cancellationGeneration"] as const) safeInteger(r[key], `${path}.${key}`);
  id(r.planId, `${path}.planId`); id(r.cancellationGroupId, `${path}.cancellationGroupId`);
  if (r.transition !== null) { const t = object(r.transition, `${path}.transition`, ["transitionId", "generation", "ordinal"]); id(t.transitionId, `${path}.transition.transitionId`); safeInteger(t.generation, `${path}.transition.generation`); safeInteger(t.ordinal, `${path}.transition.ordinal`); }
  const ownership = new Set<string>();
  for (const [index, claim] of array(r.ownership, `${path}.ownership`, ACTION_LIMITS.maxOwnershipClaims).entries()) {
    const c = object(claim, `${path}.ownership[${index}]`, ["resource", "ownershipGeneration", "grantId"]);
    const resource = controlResource(c.resource, `${path}.ownership[${index}].resource`); safeInteger(c.ownershipGeneration, `${path}.ownership[${index}].ownershipGeneration`); id(c.grantId, `${path}.ownership[${index}].grantId`);
    if (ownership.has(resource)) issue(`${path}.ownership[${index}]`, "duplicate-ownership", "Ownership claims must be unique per resource");
    ownership.add(resource);
  }
  return { kind: "performance", ownership };
}

function freshness(value: unknown, path: string): Map<string, { binding: "empty" | "loaded" }> {
  const r = object(value, path, ["hostInstanceId", "connectionGeneration", "capabilityRevision", "snapshotId", "stateRevision", "stateObservedAtMs", "maxStateAgeMs", "decks", "conditions"]);
  for (const key of ["hostInstanceId", "snapshotId"] as const) id(r[key], `${path}.${key}`);
  for (const key of ["connectionGeneration", "capabilityRevision", "stateRevision"] as const) safeInteger(r[key], `${path}.${key}`);
  const observed = time(r.stateObservedAtMs, `${path}.stateObservedAtMs`);
  const age = number(r.maxStateAgeMs, `${path}.maxStateAgeMs`);
  if (age <= 0 || age > ACTION_LIMITS.maxStateAgeMs) issue(`${path}.maxStateAgeMs`, "invalid-age", "State age must be positive and bounded");
  const decks = new Map<string, { binding: "empty" | "loaded" }>();
  for (const [index, entry] of array(r.decks, `${path}.decks`, ACTION_LIMITS.maxPreconditionDecks).entries()) {
    const current = deckPrecondition(entry, `${path}.decks[${index}]`);
    if (decks.has(current.deckId)) issue(`${path}.decks[${index}].deckId`, "duplicate-deck", "Deck preconditions must be distinct");
    decks.set(current.deckId, { binding: current.binding });
  }
  conditions(r.conditions, `${path}.conditions`, new Set(decks.keys()));
  return decks;
}

function operation(value: unknown, path: string, decks: Map<string, { binding: "empty" | "loaded" }>, conditionsByDeck: Map<string, Set<string>>, ownership: Set<string>, actionId: string, authorityKind: "performance" | "release-cleanup", cleanupLease: { obligationId: string; pressActionId: string; pressGeneration: number } | undefined, timing: { notBefore: number; dispatchBy: number; observeBy: number }): void {
  if (value === null || typeof value !== "object" || Array.isArray(value)) issue(path, "expected-object", "Expected operation");
  const raw = value as JsonObject;
  const action = string(raw.action, `${path}.action`);
  const target = (deckId: string, required: readonly string[], loaded: boolean) => {
    const deck = decks.get(deckId);
    if (!deck) issue(`${path}.deckId`, "missing-deck-precondition", "Operation requires its target deck precondition");
    if (loaded && deck.binding !== "loaded") issue(`${path}.deckId`, "unknown-or-empty-binding", "Operation requires a known loaded track binding");
    for (const resource of required) if (!ownership.has(resource)) issue(`${path}`, "missing-ownership", "Operation lacks required ownership claim");
  };
  const needs = (deckId: string, kind: string) => conditionsByDeck.get(deckId)?.has(kind) ?? false;
  if (action === "deck.set_playing") { const r = object(value, path, ["kind", "action", "deckId", "args"]); literal(r.kind, "desired-state", `${path}.kind`); const deckId = id(r.deckId, `${path}.deckId`); const a = object(r.args, `${path}.args`, ["playing"]); bool(a.playing, `${path}.args.playing`); target(deckId, [`deck:${deckId}:transport`], true); }
  else if (action === "deck.set_parameter") { const r = object(value, path, ["kind", "action", "deckId", "args"]); literal(r.kind, "desired-state", `${path}.kind`); const deckId = id(r.deckId, `${path}.deckId`); const a = object(r.args, `${path}.args`, ["parameter", "normalizedValue"]); const parameter = oneOf(a.parameter, deckParameters, `${path}.args.parameter`); const v = number(a.normalizedValue, `${path}.args.normalizedValue`); if (v < 0 || v > 1) issue(`${path}.args.normalizedValue`, "out-of-range", "Normalized value must be in [0, 1]"); target(deckId, [`deck-parameter:${deckId}:${parameter}`], false); }
  else if (action === "mixer.set_parameter") { const r = object(value, path, ["kind", "action", "args"]); literal(r.kind, "desired-state", `${path}.kind`); const a = object(r.args, `${path}.args`, ["parameter", "normalizedValue"]); literal(a.parameter, "crossfader", `${path}.args.parameter`); const v = number(a.normalizedValue, `${path}.args.normalizedValue`); if (v < 0 || v > 1) issue(`${path}.args.normalizedValue`, "out-of-range", "Normalized value must be in [0, 1]"); if (!ownership.has("mixer-parameter:crossfader")) issue(path, "missing-ownership", "Operation lacks required ownership claim"); }
  else if (action === "deck.cue_goto") { const r = object(value, path, ["kind", "action", "deckId", "args"]); literal(r.kind, "trigger", `${path}.kind`); const deckId = id(r.deckId, `${path}.deckId`); const a = object(r.args, `${path}.args`, ["marker"]); literal(a.marker, "main", `${path}.args.marker`); target(deckId, [`deck:${deckId}:cue`, `deck:${deckId}:jog`, `deck:${deckId}:transport`], true); if (!needs(deckId, `cue-available:${deckId}:main`)) issue(path, "missing-cue-condition", "Cue action requires a main-cue condition"); }
  else if (action === "deck.load_track") { const r = object(value, path, ["kind", "action", "deckId", "args"]); literal(r.kind, "trigger", `${path}.kind`); const deckId = id(r.deckId, `${path}.deckId`); const a = object(r.args, `${path}.args`, ["track", "occurrence"]); track(a.track, `${path}.args.track`); occurrence(a.occurrence, `${path}.args.occurrence`); target(deckId, [`deck:${deckId}:track`, `deck:${deckId}:transport`, `deck:${deckId}:cue`, `deck:${deckId}:jog`], false); if (!needs(deckId, `deck-silent:${deckId}`)) issue(path, "missing-silent-condition", "Load requires a deck-silent condition"); }
  else if (action === "deck.cue_press") { const r = object(value, path, ["kind", "action", "deckId", "args"]); literal(r.kind, "momentary", `${path}.kind`); const deckId = id(r.deckId, `${path}.deckId`); const a = object(r.args, `${path}.args`, ["marker", "lease", "releaseByMs"]); literal(a.marker, "main", `${path}.args.marker`); const leaseId = lease(a.lease, `${path}.args.lease`).pressActionId; if (leaseId !== actionId) issue(`${path}.args.lease.pressActionId`, "lease-mismatch", "Press lease must bind the envelope action ID"); const releaseBy = time(a.releaseByMs, `${path}.args.releaseByMs`); if (releaseBy <= timing.dispatchBy || releaseBy > timing.observeBy || releaseBy - timing.notBefore > ACTION_LIMITS.maxMomentaryHoldMs) issue(`${path}.args.releaseByMs`, "invalid-release-deadline", "Release deadline violates the momentary bounds"); target(deckId, [`deck:${deckId}:cue`, `deck:${deckId}:jog`, `deck:${deckId}:transport`], true); if (!needs(deckId, `cue-available:${deckId}:main`)) issue(path, "missing-cue-condition", "Cue action requires a main-cue condition"); }
  else if (action === "deck.cue_release") { const r = object(value, path, ["kind", "action", "deckId", "args"]); literal(r.kind, "momentary", `${path}.kind`); if (authorityKind !== "release-cleanup" || !cleanupLease) issue(path, "invalid-authority-combination", "Cue release requires cleanup authority"); const deckId = id(r.deckId, `${path}.deckId`); const current = decks.get(deckId); if (!current || current.binding !== "loaded") issue(`${path}.deckId`, "missing-deck-precondition", "Cue release requires its current loaded deck precondition"); const a = object(r.args, `${path}.args`, ["marker", "lease"]); literal(a.marker, "main", `${path}.args.marker`); const operationLease = lease(a.lease, `${path}.args.lease`); if (operationLease.obligationId !== cleanupLease.obligationId || operationLease.pressActionId !== cleanupLease.pressActionId || operationLease.pressGeneration !== cleanupLease.pressGeneration) issue(`${path}.args.lease`, "lease-mismatch", "Cue release must exactly match cleanup authority lease"); }
  else if (action === "deck.jog") { const r = object(value, path, ["kind", "action", "deckId", "args"]); literal(r.kind, "relative", `${path}.kind`); const deckId = id(r.deckId, `${path}.deckId`); const a = object(r.args, `${path}.args`, ["unit", "delta"]); literal(a.unit, "beats", `${path}.args.unit`); const delta = number(a.delta, `${path}.args.delta`); if (delta === 0 || delta < -ACTION_LIMITS.maxRelativeJogBeats || delta > ACTION_LIMITS.maxRelativeJogBeats) issue(`${path}.args.delta`, "out-of-range", "Jog delta must be nonzero and bounded"); target(deckId, [`deck:${deckId}:jog`, `deck:${deckId}:transport`], true); }
  else issue(`${path}.action`, "unsupported-action", "Unknown semantic action");
  if (authorityKind === "release-cleanup" && action !== "deck.cue_release") issue(path, "invalid-authority-combination", "Cleanup authority can only release a cue lease");
}

/** Parses one closed F06 semantic action without reading or mutating external state. */
export function validateSemanticAction(input: unknown): ValidationResult<SemanticAction> {
  try {
    const r = object(external(input), "$", ["sessionId", "actionId", "sequence", "schemaVersion", "timing", "preconditions", "authority", "operation"]);
    id(r.sessionId, "$.sessionId"); const actionId = id(r.actionId, "$.actionId"); safeInteger(r.sequence, "$.sequence"); literal(r.schemaVersion, 1, "$.schemaVersion");
    const timingRecord = object(r.timing, "$.timing", ["clockId", "requestedAtMs", "notBeforeMs", "dispatchByMs", "observeByMs"]);
    id(timingRecord.clockId, "$.timing.clockId"); const requestedAt = time(timingRecord.requestedAtMs, "$.timing.requestedAtMs"); const notBefore = time(timingRecord.notBeforeMs, "$.timing.notBeforeMs"); const dispatchBy = time(timingRecord.dispatchByMs, "$.timing.dispatchByMs"); const observeBy = time(timingRecord.observeByMs, "$.timing.observeByMs");
    if (requestedAt > notBefore || notBefore > dispatchBy || dispatchBy > observeBy || dispatchBy - requestedAt > ACTION_LIMITS.maxDispatchHorizonMs || observeBy - requestedAt > ACTION_LIMITS.maxObservationHorizonMs) issue("$.timing", "invalid-timing-order", "Timing order or horizon is invalid");
    const decks = freshness(r.preconditions, "$.preconditions");
    const freshnessRecord = r.preconditions as JsonObject;
    if (time(freshnessRecord.stateObservedAtMs, "$.preconditions.stateObservedAtMs") > requestedAt) issue("$.preconditions.stateObservedAtMs", "invalid-state-time", "State observation cannot follow the request");
    const conditionMap = conditions(freshnessRecord.conditions, "$.preconditions.conditions", new Set(decks.keys()));
    const auth = authority(r.authority, "$.authority");
    operation(r.operation, "$.operation", decks, conditionMap, auth.ownership, actionId, auth.kind, auth.cleanupLease, { notBefore, dispatchBy, observeBy });
    return accepted(r as unknown as SemanticAction);
  } catch (error) { return rejected(error); }
}

const profileFields = ["profileId", "profileRevision", "host", "version", "buildId", "platform", "skinId", "skinRevision", "configurationId"];
const catalogContextFields = ["sessionId", "hostInstanceId", "connectionGeneration", "capabilityRevision", "profile"];
const stateContextFields = [...catalogContextFields, "clockId", "streamId", "streamGeneration"];
const envelopeFields = [...stateContextFields, "schemaVersion", "messageId", "sequence", "producedAtMs", "stateRevision", "kind", "snapshotId"];
const units = new Set(["normalized", "beats", "seconds", "bpm", "decibels", "ratio"]);

function canonical(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
  if (value && typeof value === "object") return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonical((value as JsonObject)[key])}`).join(",")}}`;
  return JSON.stringify(value);
}

function context(value: JsonObject, path: string, stream = true): void {
  for (const key of ["sessionId", "hostInstanceId"]) id(value[key], `${path}.${key}`);
  for (const key of ["connectionGeneration", "capabilityRevision"]) safeInteger(value[key], `${path}.${key}`);
  if (stream) {
    id(value.clockId, `${path}.clockId`); id(value.streamId, `${path}.streamId`);
    safeInteger(value.streamGeneration, `${path}.streamGeneration`);
  }
  const p = object(value.profile, `${path}.profile`, profileFields);
  for (const key of ["profileId", "buildId", "skinId", "skinRevision", "configurationId"]) id(p[key], `${path}.profile.${key}`);
  safeInteger(p.profileRevision, `${path}.profile.profileRevision`);
  literal(p.host, "mixxx", `${path}.profile.host`);
  if (!string(p.version, `${path}.profile.version`).trim()) issue(path, "invalid-profile", "Host version must be nonempty");
  oneOf(p.platform, new Set(["macos", "windows", "linux"]), `${path}.profile.platform`);
}

function sameStreamEpoch(a: JsonObject, b: JsonObject): boolean {
  return ["sessionId", "hostInstanceId", "connectionGeneration", "clockId", "streamId", "streamGeneration"].every((key) => a[key] === b[key]);
}

function sameContext(a: JsonObject, b: JsonObject, stream = true): boolean {
  return (stream ? stateContextFields : catalogContextFields).every((key) => canonical(a[key]) === canonical(b[key]));
}

function capabilityId(value: unknown, path: string): string {
  const result = id(value, path);
  if (!result.startsWith("mixxx.") || result.length === 6) issue(path, "invalid-capability-id", "Capability requires a nonempty mixxx. suffix");
  return result;
}

function instance(value: unknown, path: string): JsonObject {
  const i = object(value, path, ["instanceId", "generation", "kind", "parent", "definitionId"]);
  id(i.instanceId, `${path}.instanceId`); safeInteger(i.generation, `${path}.generation`);
  oneOf(i.kind, featureKinds, `${path}.kind`); id(i.definitionId, `${path}.definitionId`);
  if (i.parent !== null) {
    const p = object(i.parent, `${path}.parent`, ["instanceId", "generation"]);
    id(p.instanceId, `${path}.parent.instanceId`); safeInteger(p.generation, `${path}.parent.generation`);
  }
  return i;
}

function target(value: unknown, path: string): CapabilityReference {
  const r = object(value, path, ["capabilityId", "instance"]);
  capabilityId(r.capabilityId, `${path}.capabilityId`);
  if (r.instance !== null) instance(r.instance, `${path}.instance`);
  return r as unknown as CapabilityReference;
}

function targetKey(value: CapabilityReference): string {
  return canonical([value.capabilityId, value.instance?.instanceId ?? null]);
}

function deckRef(value: unknown, path: string): JsonObject {
  const r = object(value, path, ["deckId", "deckGeneration"]);
  id(r.deckId, `${path}.deckId`); safeInteger(r.deckGeneration, `${path}.deckGeneration`);
  return r;
}

function positiveAge(value: unknown, path: string): number {
  const result = time(value, path);
  if (result === 0) issue(path, "invalid-max-age", "Maximum age must be positive");
  return result;
}

function valueShape(value: unknown, path: string): void {
  const kind = (value as JsonObject)?.kind;
  if (kind === "number") {
    const r = object(value, path, ["kind", "unit", "minimum", "maximum", "step", "tolerance", "neutralValue", "mappingId"]);
    oneOf(r.unit, units, `${path}.unit`); id(r.mappingId, `${path}.mappingId`);
    const min = number(r.minimum, `${path}.minimum`), max = number(r.maximum, `${path}.maximum`);
    if (min > max || number(r.tolerance, `${path}.tolerance`) < 0) issue(path, "invalid-value-range", "Range and tolerance are inconsistent");
    if (r.unit === "normalized" && (min < 0 || max > 1)) issue(path, "invalid-value-range", "Normalized bounds must be in [0,1]");
    if (r.step !== null && number(r.step, `${path}.step`) <= 0) issue(path, "invalid-step", "Quantization step must be positive");
    if (r.neutralValue !== null) { const neutral = number(r.neutralValue, `${path}.neutralValue`); if (neutral < min || neutral > max) issue(path, "invalid-neutral", "Neutral must be in range"); }
  } else if (kind === "enum") {
    const r = object(value, path, ["kind", "values"]); nonemptyIds(r.values, `${path}.values`, VALIDATION_LIMITS.maxStateEntries);
  } else {
    const r = object(value, path, ["kind"]);
    oneOf(r.kind, new Set(["boolean", "track-identity", "occurrence-identity"]), `${path}.kind`);
  }
}

function readRules(value: unknown, path: string): void {
  const kind = (value as JsonObject)?.kind;
  if (kind !== "state") {
    const r = object(value, path, ["kind", "reason"]);
    oneOf(r.kind, new Set(["unresolved", "not-readable"]), `${path}.kind`);
    if (!string(r.reason, `${path}.reason`).trim()) issue(path, "empty-reason", "A reason is required");
    return;
  }
  const r = object(value, path, ["kind", "value", "delivery", "maxAgeMs", "existence"]);
  valueShape(r.value, `${path}.value`);
  oneOf(r.delivery, new Set(["poll", "change-events", "poll-and-change-events"]), `${path}.delivery`);
  positiveAge(r.maxAgeMs, `${path}.maxAgeMs`); literal(r.existence, "explicit-presence-required", `${path}.existence`);
}

interface StateReferences {
  catalog: JsonObject;
  entries: Map<string, JsonObject>;
  decks: Map<string, JsonObject>;
  retained: Set<string>;
}

function retainedIds(value: unknown, path: string, refs: StateReferences): string[] {
  const ids = nonemptyIds(value, path);
  if (ids.some((entry) => !refs.retained.has(entry))) issue(path, "unresolved-evidence", "Evidence must resolve in the trusted retained-evidence index");
  return ids;
}

function presence(value: unknown, path: string, refs: StateReferences): void {
  if ((value as JsonObject)?.status === "unknown") {
    const r = object(value, path, ["status", "reason"]);
    if (!string(r.reason, `${path}.reason`).trim()) issue(path, "empty-reason", "Unknown presence needs a reason");
  } else {
    const r = object(value, path, ["status", "evidenceIds"]);
    oneOf(r.status, new Set(["present", "absent"]), `${path}.status`);
    retainedIds(r.evidenceIds, `${path}.evidenceIds`, refs);
  }
}

function referencesData(value: unknown): StateReferences {
  const c = object(external(value), "$references.catalog", [...catalogContextFields, "schemaVersion", "catalogId", "instances", "entries", "decks", "retainedEvidenceIds"]);
  context(c, "$references.catalog", false); literal(c.schemaVersion, 1, "$references.catalog.schemaVersion"); id(c.catalogId, "$references.catalog.catalogId");
  const retained = array(c.retainedEvidenceIds, "$references.catalog.retainedEvidenceIds").map((v, i) => id(v, `$references.catalog.retainedEvidenceIds[${i}]`));
  if (new Set(retained).size !== retained.length) issue("$references.catalog", "duplicate", "Retained evidence IDs must be unique");
  const refs: StateReferences = { catalog: c, entries: new Map(), decks: new Map(), retained: new Set(retained) };
  const instances = new Map<string, JsonObject>();
  for (const [index, raw] of array(c.instances, "$references.catalog.instances").entries()) {
    const path = `$references.catalog.instances[${index}]`, i = instance(raw, path), key = String(i.instanceId);
    if (instances.has(key)) issue(path, "duplicate-instance", "One current incarnation per instance ID is required");
    instances.set(key, i);
  }
  for (const i of instances.values()) {
    const seen = new Set<string>([String(i.instanceId)]);
    let cursor = i;
    while (cursor.parent !== null) {
      const parent = cursor.parent as JsonObject, p = instances.get(String(parent.instanceId));
      if (!p || p.generation !== parent.generation) issue("$references.catalog.instances", "instance-parent-mismatch", "Parent must be a current discovered incarnation");
      if (seen.has(String(p.instanceId))) issue("$references.catalog.instances", "instance-cycle", "Instance parent graph must be acyclic");
      seen.add(String(p.instanceId)); cursor = p;
    }
  }
  for (const [index, raw] of array(c.decks, "$references.catalog.decks").entries()) {
    const path = `$references.catalog.decks[${index}]`, r = object(raw, path, ["deckId", "deckGeneration", "availability", "maxAgeMs"]);
    id(r.deckId, `${path}.deckId`); safeInteger(r.deckGeneration, `${path}.deckGeneration`);
    positiveAge(r.maxAgeMs, `${path}.maxAgeMs`); presence(r.availability, `${path}.availability`, refs);
    if (refs.decks.has(String(r.deckId))) issue(path, "duplicate-deck", "One current incarnation per deck ID is required");
    refs.decks.set(String(r.deckId), r);
  }
  const definitions = new Map<string, string>();
  for (const [index, raw] of array(c.entries, "$references.catalog.entries").entries()) {
    const path = `$references.catalog.entries[${index}]`, r = object(raw, path, ["target", "read", "availability", "applicableDeck"]);
    const t = target(r.target, `${path}.target`), key = targetKey(t);
    if (refs.entries.has(key)) issue(path, "duplicate-reading", "Catalog target resolutions must be unique");
    if (t.instance && canonical(instances.get(t.instance.instanceId)) !== canonical(t.instance)) issue(path, "catalog-instance-mismatch", "Target must exactly match current instance including definition and parent");
    readRules(r.read, `${path}.read`); presence(r.availability, `${path}.availability`, refs);
    const definition = canonical({ read: r.read, instances: t.instance === null ? "singleton" : "dynamic" });
    const existingDefinition = definitions.get(t.capabilityId);
    if (existingDefinition !== undefined && existingDefinition !== definition) issue(path, "catalog-definition-conflict", "One canonical capability cannot resolve to conflicting definitions");
    definitions.set(t.capabilityId, definition);
    if (r.applicableDeck !== null) {
      const d = deckRef(r.applicableDeck, `${path}.applicableDeck`), current = refs.decks.get(String(d.deckId));
      if (!current || current.deckGeneration !== d.deckGeneration) issue(path, "catalog-deck-mismatch", "Applicable deck must resolve to the current incarnation");
    }
    refs.entries.set(key, r);
  }
  return refs;
}

function evidence(value: unknown, path: string, state: JsonObject, stale: boolean, refs: StateReferences, streamGap: boolean): JsonObject {
  const r = object(value, path, ["observationId", "hostInstanceId", "connectionGeneration", "stateRevision", "clockId", "observedAtMs", "receivedAtMs", "validUntilMs", "source", "attribution"]);
  for (const key of ["observationId", "hostInstanceId", "clockId"]) id(r[key], `${path}.${key}`);
  safeInteger(r.connectionGeneration, `${path}.connectionGeneration`); safeInteger(r.stateRevision, `${path}.stateRevision`);
  const sameEpoch = r.hostInstanceId === state.hostInstanceId && r.connectionGeneration === state.connectionGeneration && r.clockId === state.clockId;
  if (!stale && !sameEpoch) issue(path, "context-mismatch", "Current observation must match host, connection and clock");
  const observed = time(r.observedAtMs, `${path}.observedAtMs`), received = time(r.receivedAtMs, `${path}.receivedAtMs`), valid = time(r.validUntilMs, `${path}.validUntilMs`);
  if (observed > received || observed >= valid) issue(path, "invalid-evidence-times", "Evidence timestamps are inconsistent");
  if ((sameEpoch && !streamGap && Number(r.stateRevision) > Number(state.stateRevision)) || (r.clockId === state.clockId && received > Number(state.producedAtMs))) issue(path, "future-evidence", "Comparable evidence cannot be newer than the message");
  if (!stale && Number(state.producedAtMs) >= valid) issue(path, "expired-observation", "Current observations must remain valid at production");
  if ((r.source as JsonObject)?.kind === "host-reconciled") {
    const source = object(r.source, `${path}.source`, ["kind", "eventIds"]); retainedIds(source.eventIds, `${path}.source.eventIds`, refs);
  } else {
    const source = object(r.source, `${path}.source`, ["kind", "eventId"]);
    oneOf(source.kind, new Set(["host-read", "host-feedback"]), `${path}.source.kind`);
    retainedIds([source.eventId], `${path}.source.eventId`, refs);
  }
  attribution(r.attribution, `${path}.attribution`);
  const actor = r.attribution as JsonObject;
  if (actor.actor === "human") retainedIds([actor.evidenceEventId], `${path}.attribution.evidenceEventId`, refs);
  return r;
}

function observedValue(value: unknown, path: string, shape?: JsonObject): void {
  const kind = (value as JsonObject)?.kind;
  const r = object(value, path, kind === "number" ? ["kind", "value", "unit"] : ["kind", "value"]);
  if (kind === "boolean") bool(r.value, `${path}.value`);
  else if (kind === "number") {
    const v = number(r.value, `${path}.value`); oneOf(r.unit, units, `${path}.unit`);
    if (r.unit === "normalized" && (v < 0 || v > 1)) issue(path, "catalog-range-mismatch", "Normalized values must be in [0,1]");
  } else if (kind === "enum") id(r.value, `${path}.value`);
  else if (kind === "track-identity") track(r.value, `${path}.value`);
  else if (kind === "occurrence-identity") occurrence(r.value, `${path}.value`);
  else issue(path, "invalid-value-kind", "Unknown observed value kind");
  if (!shape) return;
  if (kind !== shape.kind) issue(path, "catalog-value-kind-mismatch", "Reading kind must match current catalog");
  if (kind === "number") {
    if (r.unit !== shape.unit) issue(path, "catalog-unit-mismatch", "Reading unit must match current catalog");
    if (Number(r.value) < Number(shape.minimum) || Number(r.value) > Number(shape.maximum)) issue(path, "catalog-range-mismatch", "Reading is outside catalog bounds");
  }
  if (kind === "enum" && !(shape.values as string[]).includes(String(r.value))) issue(path, "catalog-enum-mismatch", "Reading is not a declared enum choice");
}

interface ObservationRecord { value: unknown; evidence: JsonObject; stale: boolean }
function observation(value: unknown, path: string, state: JsonObject, refs: StateReferences, availability: JsonObject, validateValue: (raw: unknown, path: string, historical: boolean) => void, maxAge: number | null): ObservationRecord | null {
  const status = (value as JsonObject)?.status;
  if (status === "observed" || status === "stale") {
    const stale = status === "stale";
    const r = object(value, path, stale ? ["status", "lastKnown", "reason"] : ["status", "value", "evidence"]);
    if (stale) oneOf(r.reason, stateReasons, `${path}.reason`);
    const last = stale ? object(r.lastKnown, `${path}.lastKnown`, ["value", "evidence"]) : r;
    validateValue(last.value, stale ? `${path}.lastKnown.value` : `${path}.value`, stale && r.reason === "profile-changed");
    const ev = evidence(last.evidence, `${path}.evidence`, state, stale, refs, stale && r.reason === "stream-gap");
    if (!stale && availability.status !== "present") issue(path, "presence-required", "Current values require explicit present evidence");
    if (maxAge !== null && !(stale && r.reason === "profile-changed") && Number(ev.validUntilMs) - Number(ev.observedAtMs) > maxAge) issue(path, "catalog-age-mismatch", "Lifetime exceeds catalog maximum age");
    return { value: last.value, evidence: ev, stale };
  }
  if (status === "missing") {
    const r = object(value, path, ["status", "reason", "presenceEvidenceIds"]);
    oneOf(r.reason, new Set(["control-absent", "instance-absent"]), `${path}.reason`);
    const ids = retainedIds(r.presenceEvidenceIds, `${path}.presenceEvidenceIds`, refs);
    if (availability.status !== "absent" || ids.some((entry) => !(availability.evidenceIds as string[]).includes(entry))) issue(path, "absence-required", "Missing observations require this target's confirmed absence evidence");
  } else if (status === "unknown") {
    const r = object(value, path, ["status", "reason"]); oneOf(r.reason, unknownReasons, `${path}.reason`);
  } else if (status === "uncertain") {
    const r = object(value, path, ["status", "reason", "evidenceIds"]); oneOf(r.reason, uncertainReasons, `${path}.reason`); retainedIds(r.evidenceIds, `${path}.evidenceIds`, refs);
  } else issue(path, "invalid-observation", "Unknown observation status");
  return null;
}

interface RememberedObservation { payload: string; context: string; stale: boolean }
interface Projection { decks: Map<string, JsonObject>; readings: Map<string, JsonObject>; observations: Map<string, RememberedObservation> }
function rememberObservation(record: ObservationRecord | null, owner: unknown, projection: Projection, path: string, state: JsonObject): void {
  if (!record) return;
  const key = canonical([record.evidence.hostInstanceId, record.evidence.connectionGeneration, record.evidence.observationId]);
  const payload = canonical({ owner, value: record.value, evidence: record.evidence });
  const previous = projection.observations.get(key);
  const contextKey = canonical(stateContextFields.map((field) => state[field]));
  if (previous !== undefined && previous.payload !== payload) issue(path, "observation-conflict", "Observation identity cannot be relabeled or refreshed");
  if (previous && !record.stale && (previous.stale || previous.context !== contextKey)) issue(path, "observation-resurrection", "Invalidated or old-context evidence cannot become current without a fresh observation identity");
  projection.observations.set(key, { payload, context: contextKey, stale: record.stale });
}

function validateProjection(state: JsonObject, refs: StateReferences, projection: Projection): void {
  if (projection.decks.size > VALIDATION_LIMITS.maxStateEntries || projection.readings.size > VALIDATION_LIMITS.maxStateEntries) issue("$", "array-too-large", "Candidate projection exceeds the collection limit");
  const candidate = { ...Object.fromEntries(envelopeFields.map((key) => [key, state[key]])), kind: "snapshot", replacement: "entire-context", decks: [...projection.decks.values()], readings: [...projection.readings.values()] };
  external(candidate);
  for (const [key, raw] of projection.decks) {
    const path = `$.decks.${key}`, r = object(raw, path, ["deckId", "deckGeneration", "current"]);
    const declared = refs.decks.get(id(r.deckId, `${path}.deckId`)); safeInteger(r.deckGeneration, `${path}.deckGeneration`);
    if (!declared || declared.deckGeneration !== r.deckGeneration) issue(path, "catalog-deck-mismatch", "Deck must match current catalog incarnation");
    const record = observation(r.current, `${path}.current`, state, refs, declared.availability as JsonObject, (rawValue, valuePath) => {
      deckPrecondition(rawValue, valuePath);
      const pre = rawValue as JsonObject;
      if (pre.deckId !== r.deckId || ((r.current as JsonObject).status === "observed" && pre.deckGeneration !== r.deckGeneration)) issue(valuePath, "deck-context-mismatch", "Deck observation must match its enclosing identity");
    }, Number(declared.maxAgeMs));
    rememberObservation(record, { deckId: r.deckId, deckGeneration: record && (record.value as JsonObject).deckGeneration }, projection, path, state);
  }
  for (const [key, raw] of projection.readings) {
    const path = `$.readings.${key}`, r = object(raw, path, ["target", "deck", "observation"]), t = target(r.target, `${path}.target`), rules = refs.entries.get(targetKey(t));
    if (!rules || canonical(rules.target) !== canonical(t)) issue(path, "unresolved-capability-reference", "Target must resolve exactly in the current catalog");
    const status = (r.observation as JsonObject)?.status, stale = status === "stale", applicable = rules.applicableDeck as JsonObject | null;
    if (applicable === null) {
      if (r.deck !== null) issue(path, "reading-deck-mismatch", "Independent control requires null deck context");
    } else {
      if (r.deck === null) issue(path, "reading-deck-mismatch", "Deck-associated control cannot omit its deck");
      let pre: JsonObject;
      if ((r.deck as JsonObject)?.kind === "known") {
        const d = object(r.deck, `${path}.deck`, ["kind", "precondition"]); deckPrecondition(d.precondition, `${path}.deck.precondition`); pre = d.precondition as JsonObject;
      } else {
        const d = object(r.deck, `${path}.deck`, ["kind", "deckId", "deckGeneration"]); literal(d.kind, "unknown", `${path}.deck.kind`);
        id(d.deckId, `${path}.deck.deckId`); safeInteger(d.deckGeneration, `${path}.deck.deckGeneration`); pre = d;
        if (status === "observed") issue(path, "unknown-deck-observed", "Unknown binding cannot carry a current value");
      }
      if (pre.deckId !== applicable.deckId || (!stale && pre.deckGeneration !== applicable.deckGeneration)) issue(path, "reading-deck-mismatch", "Reading deck must match catalog applicability");
      if (!stale) {
        const current = projection.decks.get(String(pre.deckId));
        if (!current || current.deckGeneration !== pre.deckGeneration) issue(path, "reading-deck-mismatch", "Reading references a removed or replaced deck");
        if ((r.deck as JsonObject).kind === "known") {
          const observed = current.current as JsonObject;
          if (observed.status !== "observed" || canonical(observed.value) !== canonical(pre)) issue(path, "reading-binding-mismatch", "Known reading binding must equal the actual current deck binding");
        }
      }
    }
    const read = rules.read as JsonObject;
    if (status === "observed" && read.kind !== "state") issue(path, "not-readable", "Current capability does not declare readable state");
    const record = observation(r.observation, `${path}.observation`, state, refs, rules.availability as JsonObject,
      (v, p, historical) => observedValue(v, p, read.kind === "state" && !historical ? read.value as JsonObject : undefined), read.kind === "state" ? Number(read.maxAgeMs) : null);
    rememberObservation(record, { target: r.target, deck: r.deck }, projection, path, state);
  }
}

function snapshotProjection(state: JsonObject): Projection {
  const projection: Projection = { decks: new Map(), readings: new Map(), observations: new Map() };
  for (const [index, raw] of array(state.decks, "$.decks").entries()) {
    const r = object(raw, `$.decks[${index}]`, ["deckId", "deckGeneration", "current"]), key = id(r.deckId, `$.decks[${index}].deckId`);
    if (projection.decks.has(key)) issue("$.decks", "duplicate-deck", "One entry per deck ID is allowed, regardless of generation");
    projection.decks.set(key, r);
  }
  for (const [index, raw] of array(state.readings, "$.readings").entries()) {
    const r = object(raw, `$.readings[${index}]`, ["target", "deck", "observation"]), key = targetKey(target(r.target, `$.readings[${index}].target`));
    if (projection.readings.has(key)) issue("$.readings", "duplicate-reading", "One entry per canonical target and instance ID is allowed");
    projection.readings.set(key, r);
  }
  return projection;
}

function envelope(raw: unknown, path: string): JsonObject {
  const kind = (raw as JsonObject)?.kind;
  const r = object(raw, path, kind === "snapshot" ? [...envelopeFields, "replacement", "decks", "readings"] : kind === "delta" ? [...envelopeFields, "baseRevision", "previousSequence", "changes"] : issue(path, "invalid-state-kind", "Expected a state snapshot or delta"));
  context(r, path); literal(r.schemaVersion, 1, `${path}.schemaVersion`);
  for (const key of ["messageId", "snapshotId"]) id(r[key], `${path}.${key}`);
  for (const key of ["sequence", "stateRevision"]) safeInteger(r[key], `${path}.${key}`);
  time(r.producedAtMs, `${path}.producedAtMs`);
  if (kind === "snapshot") literal(r.replacement, "entire-context", `${path}.replacement`);
  return r;
}

function deckTransition(previous: JsonObject, next: JsonObject, path: string): void {
  if (Number(next.deckGeneration) < Number(previous.deckGeneration)) issue(path, "deck-generation-regression", "Deck incarnation cannot decrease in the current host");
  if (next.deckGeneration !== previous.deckGeneration) return;
  const oldObservation = previous.current as JsonObject, newObservation = next.current as JsonObject;
  const oldValue = oldObservation.status === "observed" ? oldObservation.value : oldObservation.status === "stale" ? (oldObservation.lastKnown as JsonObject).value : null;
  if (!oldValue || newObservation.status !== "observed") return;
  const old = oldValue as JsonObject, value = newObservation.value as JsonObject;
  if (old.deckGeneration !== next.deckGeneration) return;
  if (Number(value.trackGeneration) < Number(old.trackGeneration)) issue(path, "track-generation-regression", "Track generation cannot decrease in a deck incarnation");
  const oldBinding = old.binding as JsonObject, nextBinding = value.binding as JsonObject;
  const trackChanged = oldBinding.kind !== nextBinding.kind || canonical(oldBinding.track) !== canonical(nextBinding.track);
  if (trackChanged && Number(value.trackGeneration) <= Number(old.trackGeneration)) issue(path, "track-generation-required", "Changed loaded track identity requires a new track generation");
}

function applyCandidateChanges(state: JsonObject, refs: StateReferences, projection: Projection): void {
  const changed = new Set<string>();
  for (const [index, raw] of array(state.changes, "$.changes").entries()) {
    const path = `$.changes[${index}]`, kind = (raw as JsonObject)?.kind;
    let key: string;
    if (kind === "replace-deck") {
      const r = object(raw, path, ["kind", "deck"]), d = object(r.deck, `${path}.deck`, ["deckId", "deckGeneration", "current"]);
      const deckId = id(d.deckId, `${path}.deck.deckId`), previous = projection.decks.get(deckId);
      key = `deck:${deckId}`;
      if (previous) deckTransition(previous, d, path);
      projection.decks.set(deckId, d);
    } else if (kind === "remove-deck") {
      const r = object(raw, path, ["kind", "deckId", "deckGeneration", "evidenceIds"]), deckId = id(r.deckId, `${path}.deckId`);
      safeInteger(r.deckGeneration, `${path}.deckGeneration`); retainedIds(r.evidenceIds, `${path}.evidenceIds`, refs); key = `deck:${deckId}`;
      if (projection.decks.get(deckId)?.deckGeneration !== r.deckGeneration) issue(path, "remove-missing-incarnation", "Removal requires the exact existing deck incarnation");
      projection.decks.delete(deckId);
    } else if (kind === "replace-reading" || kind === "remove-reading") {
      const r = object(raw, path, kind === "replace-reading" ? ["kind", "reading"] : ["kind", "target", "evidenceIds"]);
      const read = kind === "replace-reading" ? object(r.reading, `${path}.reading`, ["target", "deck", "observation"]) : r;
      const t = target(read.target, `${path}.target`), entryKey = targetKey(t); key = `reading:${entryKey}`;
      if (kind === "replace-reading") projection.readings.set(entryKey, read);
      else {
        retainedIds(r.evidenceIds, `${path}.evidenceIds`, refs);
        if (canonical(projection.readings.get(entryKey)?.target) !== canonical(t)) issue(path, "remove-missing-incarnation", "Removal requires the exact existing reading incarnation");
        projection.readings.delete(entryKey);
      }
    } else issue(path, "invalid-change", "Unknown state change");
    if (changed.has(key)) issue(path, "duplicate-change", "A transaction cannot change the same key twice");
    changed.add(key);
  }
}

/** Validates a pure candidate projection; accepted data does not mutate or install state. */
export function validateObservedStateMessage(input: unknown, references?: StateValidationReferences): ValidationResult<ObservedStateMessage> {
  try {
    const r = envelope(external(input), "$");
    const referenceData = references === undefined ? undefined : referenceBundle(references);
    if (r.kind === "delta") {
      const base = safeInteger(r.baseRevision, "$.baseRevision"), previous = safeInteger(r.previousSequence, "$.previousSequence");
      if (r.sequence !== previous + 1 || r.stateRevision !== base + 1) issue("$", "invalid-delta-lineage", "Delta requires immediate safe sequence and revision lineage");
      if (!referenceData || !Object.hasOwn(referenceData, "baseline")) issue("$", "baseline-required", "A delta requires the full current snapshot projection");
    }
    if (!referenceData) issue("$", "catalog-required", "State admission requires trusted catalog reference data");
    const referenceFields = ["catalog"];
    if (Object.hasOwn(referenceData, "baseline")) referenceFields.push("baseline");
    if (Object.hasOwn(referenceData, "baselineCatalog")) referenceFields.push("baselineCatalog");
    const referenceObject = object(referenceData, "$references", referenceFields);
    if (referenceObject.baselineCatalog !== undefined && referenceObject.baseline === undefined) issue("$references", "baseline-required", "A historical catalog requires its complete baseline");
    const refs = referencesData(freezeCopy(external(referenceObject.catalog)));
    if (!sameContext(r, refs.catalog, false)) issue("$", "catalog-context-mismatch", "Full message profile and context must match the current catalog");
    let baseline: JsonObject | undefined;
    let previousProjection: Projection | undefined;
    if (referenceObject.baseline !== undefined) {
      baseline = envelope(freezeCopy(external(referenceObject.baseline)), "$references.baseline");
      if (baseline.kind !== "snapshot") issue("$references.baseline", "baseline-required", "Baseline must contain the full snapshot projection");
      if (r.kind === "delta" && (!sameContext(r, baseline) || r.snapshotId !== baseline.snapshotId || r.baseRevision !== baseline.stateRevision || r.previousSequence !== baseline.sequence || Number(r.producedAtMs) < Number(baseline.producedAtMs))) issue("$", "baseline-mismatch", "Delta must exactly match full baseline context and lineage");
      const suppliedHistorical = referenceObject.baselineCatalog === undefined ? undefined : referencesData(referenceObject.baselineCatalog);
      const baselineRefs = sameContext(baseline, refs.catalog, false) ? refs : suppliedHistorical ?? refs;
      if (!sameContext(baseline, baselineRefs.catalog, false)) issue("$references.baseline", "baseline-catalog-required", "Full baseline validation requires its exact catalog context");
      previousProjection = snapshotProjection(baseline); validateProjection(baseline, baselineRefs, previousProjection);
      const sameHost = r.sessionId === baseline.sessionId && r.hostInstanceId === baseline.hostInstanceId;
      if (sameHost && Number(r.connectionGeneration) < Number(baseline.connectionGeneration)) issue("$", "context-generation-regression", "Connection generation cannot regress for the same host");
      if (sameHost && r.connectionGeneration === baseline.connectionGeneration) {
        if (Number(r.capabilityRevision) < Number(baseline.capabilityRevision)) issue("$", "context-generation-regression", "Capability revision cannot regress in one connection");
        if (r.streamId === baseline.streamId && Number(r.streamGeneration) < Number(baseline.streamGeneration)) issue("$", "context-generation-regression", "A stream generation cannot move backward");
        const oldProfile = baseline.profile as JsonObject, nextProfile = r.profile as JsonObject;
        if (nextProfile.profileId === oldProfile.profileId && Number(nextProfile.profileRevision) < Number(oldProfile.profileRevision)) issue("$", "context-generation-regression", "Profile revision cannot regress for the same profile");
      }
      if (sameStreamEpoch(r, baseline)) {
        if (r.messageId === baseline.messageId) issue("$", "message-id-conflict", "A new state message cannot reuse the last accepted message ID");
        if (r.kind === "snapshot" && (r.snapshotId === baseline.snapshotId || Number(r.sequence) <= Number(baseline.sequence) || Number(r.stateRevision) <= Number(baseline.stateRevision) || Number(r.producedAtMs) < Number(baseline.producedAtMs))) issue("$", "snapshot-lineage", "Replacement requires a new snapshot ID and newer sequence/revision");
      }
    }

    const projection = r.kind === "snapshot" ? snapshotProjection(r) : previousProjection!;
    if (r.kind === "delta") applyCandidateChanges(r, refs, projection);
    if (r.kind === "snapshot" && previousProjection) {
      projection.observations = previousProjection.observations;
      for (const [key, deck] of projection.decks) {
        const previous = previousProjection.decks.get(key);
        if (previous && baseline?.hostInstanceId === r.hostInstanceId) deckTransition(previous, deck, `$.decks.${key}`);
      }
    }
    validateProjection(r, refs, projection);
    return accepted(r as unknown as ObservedStateMessage);
  } catch (error) { return rejected(error); }
}

function accepted<T>(value: T): ValidationResult<T> { return { ok: true, value: freezeCopy(value) }; }
function rejected(error: unknown): ValidationResult<never> { return { ok: false, errors: [error instanceof Invalid ? error.detail : { path: "$", code: "validation-error", message: "Validation failed" }] }; }
function freezeCopy<T>(value: T): T { return deepFreeze(structuredClone(value)); }
function deepFreeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value as Record<string, unknown>)) deepFreeze(child); } return value; }

export function validateActionOutcome(input: unknown): ValidationResult<ActionOutcome> {
  try {
    const raw = external(input);
    if (raw === null || typeof raw !== "object" || Array.isArray(raw)) issue("$", "expected-object", "Expected an action outcome");
    const status = string((raw as JsonObject).status, "$.status");
    const base = ["sessionId", "actionId", "sequence", "schemaVersion", "eventId", "clockId", "atMs", "status"];
    const r = object(raw, "$", status === "requested" ? base
      : status === "sent" ? [...base, "attemptId", "transportMessageIds"]
        : status === "accepted" ? [...base, "attemptId", "hostReceiptId"]
          : status === "observed" ? [...base, "observation", "condition", "correlation", "attribution"]
            : status === "uncertain" ? [...base, "attemptId", "reason"]
              : status === "rejected" ? [...base, "stage", "reason"]
                : status === "cancelled" ? [...base, "reason"]
                  : status === "expired" ? [...base, "phase"]
                    : issue("$.status", "invalid-outcome-status", "Unknown action outcome status"));
    for (const key of ["sessionId", "actionId", "eventId", "clockId"] as const) id(r[key], `$.${key}`); safeInteger(r.sequence, "$.sequence"); literal(r.schemaVersion, 1, "$.schemaVersion"); time(r.atMs, "$.atMs");
    if (status === "sent") { id(r.attemptId, "$.attemptId"); nonemptyIds(r.transportMessageIds, "$.transportMessageIds", ACTION_LIMITS.maxTransportMessageIds); }
    else if (status === "accepted") { id(r.attemptId, "$.attemptId"); id(r.hostReceiptId, "$.hostReceiptId"); }
    else if (status === "observed") { const o = object(r.observation, "$.observation", ["observationId", "hostInstanceId", "connectionGeneration", "stateRevision"]); id(o.observationId, "$.observation.observationId"); id(o.hostInstanceId, "$.observation.hostInstanceId"); safeInteger(o.connectionGeneration, "$.observation.connectionGeneration"); safeInteger(o.stateRevision, "$.observation.stateRevision"); oneOf(r.condition, new Set(["satisfied", "not-satisfied"]), "$.condition"); if ((r.correlation as JsonObject).kind === "state-only") object(r.correlation, "$.correlation", ["kind"]); else { const c = object(r.correlation, "$.correlation", ["kind", "hostReceiptId"]); literal(c.kind, "request-linked", "$.correlation.kind"); id(c.hostReceiptId, "$.correlation.hostReceiptId"); } attribution(r.attribution, "$.attribution"); }
    else if (status === "uncertain") { if (r.attemptId !== null) id(r.attemptId, "$.attemptId"); oneOf(r.reason, new Set(["send-result-unknown", "acceptance-missing", "observation-timeout", "feedback-lost", "ambiguous-correlation", "release-unconfirmed"]), "$.reason"); }
    else if (status === "rejected") { oneOf(r.stage, new Set(["validation", "authority", "host"]), "$.stage"); oneOf(r.reason, new Set(["invalid-data", "unsupported-action", "stale-context", "precondition-failed", "authority-denied", "host-rejected"]), "$.reason"); }
    else if (status === "cancelled") oneOf(r.reason, new Set(["disarm", "mode-changed", "human-takeover", "manual-stop", "track-changed", "plan-replaced", "connection-lost", "operator-cancelled"]), "$.reason");
    else if (status === "expired") oneOf(r.phase, new Set(["dispatch", "observation"]), "$.phase");
    return accepted(r as unknown as ActionOutcome);
  } catch (error) { return rejected(error); }
}

/** Validates a stored press cleanup record without emitting a release. */
export function validateMomentaryReleaseObligation(input: unknown): ValidationResult<MomentaryReleaseObligation> {
  try {
    const r = object(external(input), "$", ["obligationId", "pressActionId", "pressGeneration", "sessionId", "hostInstanceId", "connectionGeneration", "deck", "control", "clockId", "releaseByMs", "evidence"]);
    for (const key of ["obligationId", "pressActionId", "sessionId", "hostInstanceId", "clockId"] as const) id(r[key], `$.${key}`); safeInteger(r.pressGeneration, "$.pressGeneration"); safeInteger(r.connectionGeneration, "$.connectionGeneration"); if (deckPrecondition(r.deck, "$.deck").binding !== "loaded") issue("$.deck", "invalid-release-binding", "A release obligation requires the pressed loaded track"); literal(r.control, "cue", "$.control"); time(r.releaseByMs, "$.releaseByMs");
    if ((r.evidence as JsonObject).kind === "sent-unconfirmed") { const e = object(r.evidence, "$.evidence", ["kind", "attemptId"]); id(e.attemptId, "$.evidence.attemptId"); } else { const e = object(r.evidence, "$.evidence", ["kind", "hostReceiptId"]); literal(e.kind, "acknowledged-active", "$.evidence.kind"); id(e.hostReceiptId, "$.evidence.hostReceiptId"); }
    return accepted(r as unknown as MomentaryReleaseObligation);
  } catch (error) { return rejected(error); }
}

// End of autonomously AI-generated validator.
