// This test was autonomously generated by an AI agent at the user's request.
import assert from "node:assert/strict";
import test from "node:test";

import { VALIDATION_LIMITS, validateActionOutcome, validateMomentaryReleaseObligation, validateObservedStateMessage, validateSemanticAction } from "../../core/validate.ts";

function action(): Record<string, unknown> {
  return {
    sessionId: "session1", actionId: "action1", sequence: 1, schemaVersion: 1,
    timing: { clockId: "clock1", requestedAtMs: 100, notBeforeMs: 100, dispatchByMs: 200, observeByMs: 300 },
    preconditions: {
      hostInstanceId: "host1", connectionGeneration: 1, capabilityRevision: 1, snapshotId: "snapshot1", stateRevision: 1,
      stateObservedAtMs: 99, maxStateAgeMs: 1000,
      decks: [{ deckId: "deck1", deckGeneration: 1, trackGeneration: 1, binding: { kind: "loaded", track: { libraryId: "library1", trackId: "track1" }, occurrence: null } }],
      conditions: [],
    },
    authority: {
      kind: "performance", mode: "AIOnly", modeGeneration: 1, armingGeneration: 1, authorityRevision: 1,
      planId: "plan1", planRevision: 1, cancellationGroupId: "cancel1", cancellationGeneration: 1, transition: null,
      ownership: [{ resource: { kind: "deck", deckId: "deck1", control: "transport" }, ownershipGeneration: 1, grantId: "grant1" }],
    },
    operation: { kind: "desired-state", action: "deck.set_playing", deckId: "deck1", args: { playing: true } },
  };
}

function snapshot(readings: unknown[] = []): Record<string, unknown> {
  return {
    sessionId: "session1", hostInstanceId: "host1", connectionGeneration: 1, capabilityRevision: 1,
    profile: { profileId: "profile1", profileRevision: 1, host: "mixxx", version: "2.5", buildId: "build1", platform: "macos", skinId: "skin1", skinRevision: "skinrev1", configurationId: "config1" },
    clockId: "clock1", streamId: "stream1", streamGeneration: 1, schemaVersion: 1, messageId: "message1", sequence: 1,
    producedAtMs: 200, stateRevision: 1, kind: "snapshot", snapshotId: "snapshot1", replacement: "entire-context", decks: [], readings,
  };
}

function failure(result: ReturnType<typeof validateSemanticAction> | ReturnType<typeof validateObservedStateMessage>, code: string): void {
  assert.equal(result.ok, false);
  if (!result.ok) assert.equal(result.errors[0]?.code, code);
}

test("accepts a bounded closed action and returns an isolated frozen copy", () => {
  const input = action();
  const result = validateSemanticAction(input);
  assert.equal(result.ok, true);
  if (!result.ok) return;
  assert.notEqual(result.value, input);
  assert.equal(Object.isFrozen(result.value), true);
  (input.operation as { args: { playing: boolean } }).args.playing = false;
  assert.equal(result.value.operation.action, "deck.set_playing");
  assert.equal((result.value.operation.args as { playing: boolean }).playing, true);
});

test("rejects unknown operations, fields, malformed IDs, generations, and numeric bounds", () => {
  const unknown = action(); (unknown.operation as { action: string }).action = "deck.set_sync_enabled";
  failure(validateSemanticAction(unknown), "unsupported-action");
  const extra = action(); extra.script = "process.exit()";
  failure(validateSemanticAction(extra), "unknown-field");
  const invalidId = action(); invalidId.sessionId = "../session";
  failure(validateSemanticAction(invalidId), "invalid-id");
  const absentGeneration = action(); delete (absentGeneration.preconditions as Record<string, unknown>).connectionGeneration;
  failure(validateSemanticAction(absentGeneration), "missing-field");
  const nonFinite = action(); ((nonFinite.operation as { args: { playing: boolean } }).args as unknown as { playing: number }).playing = Number.NaN;
  failure(validateSemanticAction(nonFinite), "non-finite");
  const horizon = action(); ((horizon.timing as Record<string, unknown>).observeByMs) = 120_101;
  failure(validateSemanticAction(horizon), "invalid-timing-order");
  const missingTrackGeneration = action(); delete ((missingTrackGeneration.preconditions as { decks: Record<string, unknown>[] }).decks[0] as Record<string, unknown>).trackGeneration;
  failure(validateSemanticAction(missingTrackGeneration), "missing-field");
});

test("accepts every frozen operation only with its matching resources, conditions, and lease", () => {
  const cases: Array<(value: Record<string, unknown>) => void> = [
    (value) => { value.operation = { kind: "desired-state", action: "deck.set_parameter", deckId: "deck1", args: { parameter: "volume", normalizedValue: 0.5 } }; (value.authority as { ownership: unknown[] }).ownership = [{ resource: { kind: "deck-parameter", deckId: "deck1", parameter: "volume" }, ownershipGeneration: 1, grantId: "grant1" }]; },
    (value) => { value.operation = { kind: "desired-state", action: "mixer.set_parameter", args: { parameter: "crossfader", normalizedValue: 0.5 } }; (value.authority as { ownership: unknown[] }).ownership = [{ resource: { kind: "mixer-parameter", parameter: "crossfader" }, ownershipGeneration: 1, grantId: "grant1" }]; },
    (value) => { value.operation = { kind: "trigger", action: "deck.cue_goto", deckId: "deck1", args: { marker: "main" } }; (value.preconditions as { conditions: unknown[] }).conditions = [{ kind: "cue-available", deckId: "deck1", marker: "main" }]; (value.authority as { ownership: unknown[] }).ownership = ["cue", "jog", "transport"].map((control) => ({ resource: { kind: "deck", deckId: "deck1", control }, ownershipGeneration: 1, grantId: `grant-${control}` })); },
    (value) => { value.operation = { kind: "trigger", action: "deck.load_track", deckId: "deck1", args: { track: { libraryId: "library2", trackId: "track2" }, occurrence: { setId: "set1", occurrenceId: "occurrence1", generation: 1 } } }; (value.preconditions as { conditions: unknown[] }).conditions = [{ kind: "deck-silent", deckId: "deck1" }]; (value.authority as { ownership: unknown[] }).ownership = ["track", "transport", "cue", "jog"].map((control) => ({ resource: { kind: "deck", deckId: "deck1", control }, ownershipGeneration: 1, grantId: `grant-${control}` })); },
    (value) => { value.operation = { kind: "momentary", action: "deck.cue_press", deckId: "deck1", args: { marker: "main", lease: { obligationId: "obligation1", pressActionId: "action1", pressGeneration: 1 }, releaseByMs: 250 } }; (value.preconditions as { conditions: unknown[] }).conditions = [{ kind: "cue-available", deckId: "deck1", marker: "main" }]; (value.authority as { ownership: unknown[] }).ownership = ["cue", "jog", "transport"].map((control) => ({ resource: { kind: "deck", deckId: "deck1", control }, ownershipGeneration: 1, grantId: `grant-${control}` })); },
    (value) => { value.operation = { kind: "relative", action: "deck.jog", deckId: "deck1", args: { unit: "beats", delta: -0.25 } }; (value.authority as { ownership: unknown[] }).ownership = ["jog", "transport"].map((control) => ({ resource: { kind: "deck", deckId: "deck1", control }, ownershipGeneration: 1, grantId: `grant-${control}` })); },
    (value) => { value.authority = { kind: "release-cleanup", lease: { obligationId: "obligation1", pressActionId: "action1", pressGeneration: 1 } }; value.operation = { kind: "momentary", action: "deck.cue_release", deckId: "deck1", args: { marker: "main", lease: { obligationId: "obligation1", pressActionId: "action1", pressGeneration: 1 } } }; },
  ];
  for (const configure of cases) {
    const candidate = action(); configure(candidate);
    assert.equal(validateSemanticAction(candidate).ok, true);
  }
  const contradictory = action(); (contradictory.preconditions as { conditions: unknown[] }).conditions = [{ kind: "deck-playing", deckId: "deck1", playing: true }, { kind: "deck-playing", deckId: "deck1", playing: false }];
  failure(validateSemanticAction(contradictory), "conflicting-condition");
  const badRelease = action(); badRelease.authority = { kind: "release-cleanup", lease: { obligationId: "obligation1", pressActionId: "action1", pressGeneration: 1 } }; badRelease.operation = { kind: "momentary", action: "deck.cue_release", deckId: "deck1", args: { marker: "main", lease: { obligationId: "obligation1", pressActionId: "action1", pressGeneration: 2 } } };
  failure(validateSemanticAction(badRelease), "lease-mismatch");
});

test("rejects unsafe payloads before semantic admission", () => {
  failure(validateSemanticAction(JSON.stringify(action()) + " ".repeat(VALIDATION_LIMITS.maxTransportBytes)), "payload-too-large");
  const recursive: Record<string, unknown> = action(); recursive.loop = recursive;
  failure(validateSemanticAction(recursive), "recursive");
  const deep: Record<string, unknown> = action(); let cursor: Record<string, unknown> = deep;
  for (let index = 0; index <= VALIDATION_LIMITS.maxDepth; index += 1) { cursor.child = {}; cursor = cursor.child as Record<string, unknown>; }
  failure(validateSemanticAction(deep), "too-deep");
  let getterRead = false;
  const accessor = action();
  Object.defineProperty(accessor, "script", { enumerable: true, get: () => { getterRead = true; return "anything"; } });
  failure(validateSemanticAction(accessor), "non-json");
  assert.equal(getterRead, false);
});

test("validates structurally complete empty snapshots without changing any state", () => {
  const input = snapshot();
  const result = validateObservedStateMessage(input);
  assert.equal(result.ok, true);
  if (result.ok) assert.equal(result.value.kind, "snapshot");
});

test("requires current catalog resolution for readings and checks its declared value", () => {
  const observed = {
    target: { capabilityId: "mixxx.deck.playing", instance: null }, deck: null,
    observation: {
      status: "observed", value: { kind: "boolean", value: false },
      evidence: { observationId: "observation1", hostInstanceId: "host1", connectionGeneration: 1, stateRevision: 1, clockId: "clock1", observedAtMs: 100, receivedAtMs: 150, validUntilMs: 160, source: { kind: "host-read", eventId: "event1" }, attribution: { actor: "unknown" } },
    },
  };
  failure(validateObservedStateMessage(snapshot([observed])), "unresolved-capability-reference");
  const accepted = validateObservedStateMessage(snapshot([observed]), { resolveCapability: () => ({ value: { kind: "boolean" }, maxAgeMs: 100 }) });
  assert.equal(accepted.ok, true);
  const wrong = structuredClone(observed); (wrong.observation as { value: Record<string, unknown> }).value = { kind: "number", value: 0, unit: "normalized" };
  failure(validateObservedStateMessage(snapshot([wrong]), { resolveCapability: () => ({ value: { kind: "boolean" }, maxAgeMs: 100 }) }), "catalog-value-kind-mismatch");
});

test("rejects state extras, absent generations, conflicting changes, and invalid delta lineage", () => {
  const extra = snapshot(); extra.functionName = "anything";
  failure(validateObservedStateMessage(extra), "unknown-field");
  const absent = snapshot(); delete absent.connectionGeneration;
  failure(validateObservedStateMessage(absent), "missing-field");
  const delta: Record<string, unknown> = { ...snapshot(), kind: "delta", baseRevision: 1, previousSequence: 1, sequence: 4, stateRevision: 2, changes: [] };
  delete delta.replacement; delete delta.decks; delete delta.readings;
  failure(validateObservedStateMessage(delta), "invalid-delta-lineage");
});

test("admits only a delta bound to the caller's immutable baseline", () => {
  const delta: Record<string, unknown> = { ...snapshot(), kind: "delta", baseRevision: 1, previousSequence: 1, sequence: 2, stateRevision: 2, changes: [] };
  delete delta.replacement; delete delta.decks; delete delta.readings;
  const references = {
    resolveCapability: () => undefined,
    baseline: { snapshotId: "snapshot1", stateRevision: 1, sequence: 1, sessionId: "session1", hostInstanceId: "host1", connectionGeneration: 1, capabilityRevision: 1, clockId: "clock1", streamId: "stream1", streamGeneration: 1 },
  };
  assert.equal(validateObservedStateMessage(delta, references).ok, true);
  failure(validateObservedStateMessage(delta, { ...references, baseline: { ...references.baseline, sequence: 0 } }), "baseline-mismatch");
});

test("accepts every F06 outcome status and both release-obligation evidence forms", () => {
  const base = { sessionId: "session1", actionId: "action1", sequence: 1, schemaVersion: 1, eventId: "event1", clockId: "clock1", atMs: 100 };
  const outcomes = [
    { ...base, status: "requested" },
    { ...base, status: "sent", attemptId: "attempt1", transportMessageIds: ["message1"] },
    { ...base, status: "accepted", attemptId: "attempt1", hostReceiptId: "receipt1" },
    { ...base, status: "observed", observation: { observationId: "observation1", hostInstanceId: "host1", connectionGeneration: 1, stateRevision: 1 }, condition: "satisfied", correlation: { kind: "state-only" }, attribution: { actor: "unknown" } },
    { ...base, status: "uncertain", attemptId: null, reason: "feedback-lost" },
    { ...base, status: "rejected", stage: "host", reason: "host-rejected" },
    { ...base, status: "cancelled", reason: "disarm" },
    { ...base, status: "expired", phase: "observation" },
  ];
  for (const outcome of outcomes) assert.equal(validateActionOutcome(outcome).ok, true);
  assert.equal(validateActionOutcome({ ...base, status: "sent", attemptId: "attempt1", transportMessageIds: [] }).ok, false);
  const obligation = { obligationId: "obligation1", pressActionId: "action1", pressGeneration: 1, sessionId: "session1", hostInstanceId: "host1", connectionGeneration: 1, deck: { deckId: "deck1", deckGeneration: 1, trackGeneration: 1, binding: { kind: "loaded", track: { libraryId: "library1", trackId: "track1" }, occurrence: null } }, control: "cue", clockId: "clock1", releaseByMs: 200 };
  assert.equal(validateMomentaryReleaseObligation({ ...obligation, evidence: { kind: "sent-unconfirmed", attemptId: "attempt1" } }).ok, true);
  assert.equal(validateMomentaryReleaseObligation({ ...obligation, evidence: { kind: "acknowledged-active", hostReceiptId: "receipt1" } }).ok, true);
  assert.equal(validateMomentaryReleaseObligation({ ...obligation, evidence: { kind: "other" } }).ok, false);
});

test("rejects hidden hooks, symbol keys and broad objects without executing them", () => {
  let invoked = false;
  const hidden = action();
  Object.defineProperty(hidden, "toJSON", { value: () => { invoked = true; return action(); } });
  failure(validateSemanticAction(hidden), "non-json");
  assert.equal(invoked, false);
  const symbol = action(); Object.defineProperty(symbol, Symbol("hidden"), { value: 1 });
  failure(validateSemanticAction(symbol), "non-json");
  const broad = Object.fromEntries(Array.from({ length: 65 }, (_, i) => [`field${i}`, 0]));
  failure(validateSemanticAction(broad), "too-many-keys");
  failure(validateSemanticAction("[".repeat(33) + "0" + "]".repeat(33)), "too-deep");
  failure(validateSemanticAction({ ...action(), actionId: "action1\n" }), "invalid-id");
});

test("accepts the exact transport byte boundary and a parameter on a known empty deck", () => {
  const json = JSON.stringify(action());
  const padded = json + " ".repeat(VALIDATION_LIMITS.maxTransportBytes - new TextEncoder().encode(json).length);
  assert.equal(validateSemanticAction(padded).ok, true);
  failure(validateSemanticAction(padded + " "), "payload-too-large");
  const empty = action();
  (empty.preconditions as { decks: Record<string, unknown>[] }).decks[0]!.binding = { kind: "empty" };
  empty.operation = { kind: "desired-state", action: "deck.set_parameter", deckId: "deck1", args: { parameter: "volume", normalizedValue: 0 } };
  (empty.authority as { ownership: unknown[] }).ownership = [{ resource: { kind: "deck-parameter", deckId: "deck1", parameter: "volume" }, ownershipGeneration: 1, grantId: "g1" }];
  assert.equal(validateSemanticAction(empty).ok, true);
});

// End of autonomously AI-generated test.
