// This test was autonomously generated by an AI agent at the user's request.
import assert from "node:assert/strict";
import test from "node:test";

import type { StateValidationReferences } from "../../core/validate.ts";
import { VALIDATION_LIMITS, validateActionOutcome, validateMomentaryReleaseObligation, validateObservedStateMessage, validateSemanticAction } from "../../core/validate.ts";

function action(): Record<string, unknown> {
  return {
    sessionId: "session1", actionId: "action1", sequence: 1, schemaVersion: 1,
    timing: { clockId: "clock1", requestedAtMs: 100, notBeforeMs: 100, dispatchByMs: 200, observeByMs: 300 },
    preconditions: {
      hostInstanceId: "host1", connectionGeneration: 1, capabilityRevision: 1, snapshotId: "snapshot1", stateRevision: 1,
      stateObservedAtMs: 99, maxStateAgeMs: 1000,
      decks: [{ deckId: "deck1", deckGeneration: 1, trackGeneration: 1, binding: { kind: "loaded", track: { libraryId: "library1", trackId: "track1" }, occurrence: null } }],
      conditions: [],
    },
    authority: {
      kind: "performance", mode: "AIOnly", modeGeneration: 1, armingGeneration: 1, authorityRevision: 1,
      planId: "plan1", planRevision: 1, cancellationGroupId: "cancel1", cancellationGeneration: 1, transition: null,
      ownership: [{ resource: { kind: "deck", deckId: "deck1", control: "transport" }, ownershipGeneration: 1, grantId: "grant1" }],
    },
    operation: { kind: "desired-state", action: "deck.set_playing", deckId: "deck1", args: { playing: true } },
  };
}

function snapshot(readings: unknown[] = []): Record<string, unknown> {
  return {
    sessionId: "session1", hostInstanceId: "host1", connectionGeneration: 1, capabilityRevision: 1,
    profile: { profileId: "profile1", profileRevision: 1, host: "mixxx", version: "2.5", buildId: "build1", platform: "macos", skinId: "skin1", skinRevision: "skinrev1", configurationId: "config1" },
    clockId: "clock1", streamId: "stream1", streamGeneration: 1, schemaVersion: 1, messageId: "message1", sequence: 1,
    producedAtMs: 200, stateRevision: 1, kind: "snapshot", snapshotId: "snapshot1", replacement: "entire-context", decks: [], readings,
  };
}

function failure(result: ReturnType<typeof validateSemanticAction> | ReturnType<typeof validateObservedStateMessage>, code: string): void {
  assert.equal(result.ok, false);
  if (!result.ok) assert.equal(result.errors[0]?.code, code);
}

test("accepts a bounded closed action and returns an isolated frozen copy", () => {
  const input = action();
  const result = validateSemanticAction(input);
  assert.equal(result.ok, true);
  if (!result.ok) return;
  assert.notEqual(result.value, input);
  assert.equal(Object.isFrozen(result.value), true);
  (input.operation as { args: { playing: boolean } }).args.playing = false;
  assert.equal(result.value.operation.action, "deck.set_playing");
  assert.equal((result.value.operation.args as { playing: boolean }).playing, true);
});

test("rejects unknown operations, fields, malformed IDs, generations, and numeric bounds", () => {
  const unknown = action(); (unknown.operation as { action: string }).action = "deck.set_sync_enabled";
  failure(validateSemanticAction(unknown), "unsupported-action");
  const extra = action(); extra.script = "process.exit()";
  failure(validateSemanticAction(extra), "unknown-field");
  const invalidId = action(); invalidId.sessionId = "../session";
  failure(validateSemanticAction(invalidId), "invalid-id");
  const absentGeneration = action(); delete (absentGeneration.preconditions as Record<string, unknown>).connectionGeneration;
  failure(validateSemanticAction(absentGeneration), "missing-field");
  const nonFinite = action(); ((nonFinite.operation as { args: { playing: boolean } }).args as unknown as { playing: number }).playing = Number.NaN;
  failure(validateSemanticAction(nonFinite), "non-finite");
  const horizon = action(); ((horizon.timing as Record<string, unknown>).observeByMs) = 120_101;
  failure(validateSemanticAction(horizon), "invalid-timing-order");
  const missingTrackGeneration = action(); delete ((missingTrackGeneration.preconditions as { decks: Record<string, unknown>[] }).decks[0] as Record<string, unknown>).trackGeneration;
  failure(validateSemanticAction(missingTrackGeneration), "missing-field");
});

test("accepts every frozen operation only with its matching resources, conditions, and lease", () => {
  const cases: Array<(value: Record<string, unknown>) => void> = [
    (value) => { value.operation = { kind: "desired-state", action: "deck.set_parameter", deckId: "deck1", args: { parameter: "volume", normalizedValue: 0.5 } }; (value.authority as { ownership: unknown[] }).ownership = [{ resource: { kind: "deck-parameter", deckId: "deck1", parameter: "volume" }, ownershipGeneration: 1, grantId: "grant1" }]; },
    (value) => { value.operation = { kind: "desired-state", action: "mixer.set_parameter", args: { parameter: "crossfader", normalizedValue: 0.5 } }; (value.authority as { ownership: unknown[] }).ownership = [{ resource: { kind: "mixer-parameter", parameter: "crossfader" }, ownershipGeneration: 1, grantId: "grant1" }]; },
    (value) => { value.operation = { kind: "trigger", action: "deck.cue_goto", deckId: "deck1", args: { marker: "main" } }; (value.preconditions as { conditions: unknown[] }).conditions = [{ kind: "cue-available", deckId: "deck1", marker: "main" }]; (value.authority as { ownership: unknown[] }).ownership = ["cue", "jog", "transport"].map((control) => ({ resource: { kind: "deck", deckId: "deck1", control }, ownershipGeneration: 1, grantId: `grant-${control}` })); },
    (value) => { value.operation = { kind: "trigger", action: "deck.load_track", deckId: "deck1", args: { track: { libraryId: "library2", trackId: "track2" }, occurrence: { setId: "set1", occurrenceId: "occurrence1", generation: 1 } } }; (value.preconditions as { conditions: unknown[] }).conditions = [{ kind: "deck-silent", deckId: "deck1" }]; (value.authority as { ownership: unknown[] }).ownership = ["track", "transport", "cue", "jog"].map((control) => ({ resource: { kind: "deck", deckId: "deck1", control }, ownershipGeneration: 1, grantId: `grant-${control}` })); },
    (value) => { value.operation = { kind: "momentary", action: "deck.cue_press", deckId: "deck1", args: { marker: "main", lease: { obligationId: "obligation1", pressActionId: "action1", pressGeneration: 1 }, releaseByMs: 250 } }; (value.preconditions as { conditions: unknown[] }).conditions = [{ kind: "cue-available", deckId: "deck1", marker: "main" }]; (value.authority as { ownership: unknown[] }).ownership = ["cue", "jog", "transport"].map((control) => ({ resource: { kind: "deck", deckId: "deck1", control }, ownershipGeneration: 1, grantId: `grant-${control}` })); },
    (value) => { value.operation = { kind: "relative", action: "deck.jog", deckId: "deck1", args: { unit: "beats", delta: -0.25 } }; (value.authority as { ownership: unknown[] }).ownership = ["jog", "transport"].map((control) => ({ resource: { kind: "deck", deckId: "deck1", control }, ownershipGeneration: 1, grantId: `grant-${control}` })); },
    (value) => { value.authority = { kind: "release-cleanup", lease: { obligationId: "obligation1", pressActionId: "action1", pressGeneration: 1 } }; value.operation = { kind: "momentary", action: "deck.cue_release", deckId: "deck1", args: { marker: "main", lease: { obligationId: "obligation1", pressActionId: "action1", pressGeneration: 1 } } }; },
  ];
  for (const configure of cases) {
    const candidate = action(); configure(candidate);
    assert.equal(validateSemanticAction(candidate).ok, true);
  }
  const contradictory = action(); (contradictory.preconditions as { conditions: unknown[] }).conditions = [{ kind: "deck-playing", deckId: "deck1", playing: true }, { kind: "deck-playing", deckId: "deck1", playing: false }];
  failure(validateSemanticAction(contradictory), "conflicting-condition");
  const badRelease = action(); badRelease.authority = { kind: "release-cleanup", lease: { obligationId: "obligation1", pressActionId: "action1", pressGeneration: 1 } }; badRelease.operation = { kind: "momentary", action: "deck.cue_release", deckId: "deck1", args: { marker: "main", lease: { obligationId: "obligation1", pressActionId: "action1", pressGeneration: 2 } } };
  failure(validateSemanticAction(badRelease), "lease-mismatch");
});

test("rejects unsafe payloads before semantic admission", () => {
  failure(validateSemanticAction(JSON.stringify(action()) + " ".repeat(VALIDATION_LIMITS.maxTransportBytes)), "payload-too-large");
  const recursive: Record<string, unknown> = action(); recursive.loop = recursive;
  failure(validateSemanticAction(recursive), "recursive");
  const deep: Record<string, unknown> = action(); let cursor: Record<string, unknown> = deep;
  for (let index = 0; index <= VALIDATION_LIMITS.maxDepth; index += 1) { cursor.child = {}; cursor = cursor.child as Record<string, unknown>; }
  failure(validateSemanticAction(deep), "too-deep");
  let getterRead = false;
  const accessor = action();
  Object.defineProperty(accessor, "script", { enumerable: true, get: () => { getterRead = true; return "anything"; } });
  failure(validateSemanticAction(accessor), "non-json");
  assert.equal(getterRead, false);
});

test("accepts every F06 outcome status and both release-obligation evidence forms", () => {
  const base = { sessionId: "session1", actionId: "action1", sequence: 1, schemaVersion: 1, eventId: "event1", clockId: "clock1", atMs: 100 };
  const outcomes = [
    { ...base, status: "requested" },
    { ...base, status: "sent", attemptId: "attempt1", transportMessageIds: ["message1"] },
    { ...base, status: "accepted", attemptId: "attempt1", hostReceiptId: "receipt1" },
    { ...base, status: "observed", observation: { observationId: "observation1", hostInstanceId: "host1", connectionGeneration: 1, stateRevision: 1 }, condition: "satisfied", correlation: { kind: "state-only" }, attribution: { actor: "unknown" } },
    { ...base, status: "uncertain", attemptId: null, reason: "feedback-lost" },
    { ...base, status: "rejected", stage: "host", reason: "host-rejected" },
    { ...base, status: "cancelled", reason: "disarm" },
    { ...base, status: "expired", phase: "observation" },
  ];
  for (const outcome of outcomes) assert.equal(validateActionOutcome(outcome).ok, true);
  assert.equal(validateActionOutcome({ ...base, status: "sent", attemptId: "attempt1", transportMessageIds: [] }).ok, false);
  const obligation = { obligationId: "obligation1", pressActionId: "action1", pressGeneration: 1, sessionId: "session1", hostInstanceId: "host1", connectionGeneration: 1, deck: { deckId: "deck1", deckGeneration: 1, trackGeneration: 1, binding: { kind: "loaded", track: { libraryId: "library1", trackId: "track1" }, occurrence: null } }, control: "cue", clockId: "clock1", releaseByMs: 200 };
  assert.equal(validateMomentaryReleaseObligation({ ...obligation, evidence: { kind: "sent-unconfirmed", attemptId: "attempt1" } }).ok, true);
  assert.equal(validateMomentaryReleaseObligation({ ...obligation, evidence: { kind: "acknowledged-active", hostReceiptId: "receipt1" } }).ok, true);
  assert.equal(validateMomentaryReleaseObligation({ ...obligation, evidence: { kind: "other" } }).ok, false);
});

test("rejects hidden hooks, symbol keys and broad objects without executing them", () => {
  let invoked = false;
  const hidden = action();
  Object.defineProperty(hidden, "toJSON", { value: () => { invoked = true; return action(); } });
  failure(validateSemanticAction(hidden), "non-json");
  assert.equal(invoked, false);
  const inheritedArrayHook: unknown[] = [];
  Object.setPrototypeOf(inheritedArrayHook, Object.assign(Object.create(Array.prototype), { toJSON: () => { invoked = true; return []; } }));
  failure(validateSemanticAction({ ...action(), payload: inheritedArrayHook }), "non-json");
  assert.equal(invoked, false);
  const symbol = action(); Object.defineProperty(symbol, Symbol("hidden"), { value: 1 });
  failure(validateSemanticAction(symbol), "non-json");
  const broad = Object.fromEntries(Array.from({ length: 65 }, (_, i) => [`field${i}`, 0]));
  failure(validateSemanticAction(broad), "too-many-keys");
  failure(validateSemanticAction("[".repeat(33) + "0" + "]".repeat(33)), "too-deep");
  failure(validateSemanticAction({ ...action(), actionId: "action1\n" }), "invalid-id");
});

test("accepts the exact transport byte boundary and a parameter on a known empty deck", () => {
  const json = JSON.stringify(action());
  const padded = json + " ".repeat(VALIDATION_LIMITS.maxTransportBytes - new TextEncoder().encode(json).length);
  assert.equal(validateSemanticAction(padded).ok, true);
  failure(validateSemanticAction(padded + " "), "payload-too-large");
  const empty = action();
  (empty.preconditions as { decks: Record<string, unknown>[] }).decks[0]!.binding = { kind: "empty" };
  empty.operation = { kind: "desired-state", action: "deck.set_parameter", deckId: "deck1", args: { parameter: "volume", normalizedValue: 0 } };
  (empty.authority as { ownership: unknown[] }).ownership = [{ resource: { kind: "deck-parameter", deckId: "deck1", parameter: "volume" }, ownershipGeneration: 1, grantId: "g1" }];
  assert.equal(validateSemanticAction(empty).ok, true);
});



// Deliberately mutable untrusted test records permit malformed admission fixtures.
type TestRecord = Record<string, any>;
function stateFixture(): { state: TestRecord; refs: TestRecord } {
  const state = snapshot() as TestRecord;
  const precondition = { deckId: "deck1", deckGeneration: 1, trackGeneration: 1, binding: { kind: "loaded", track: { libraryId: "library1", trackId: "track1" }, occurrence: null } };
  const evidence = (observationId: string) => ({ observationId, hostInstanceId: "host1", connectionGeneration: 1, stateRevision: 1, clockId: "clock1", observedAtMs: 100, receivedAtMs: 150, validUntilMs: 300, source: { kind: "host-read", eventId: "event1" }, attribution: { actor: "unknown" } });
  const instance = { instanceId: "instance1", generation: 1, kind: "deck", parent: null, definitionId: "deck-definition" };
  const target = { capabilityId: "mixxx.deck.playing", instance };
  state.decks = [{ deckId: "deck1", deckGeneration: 1, current: { status: "observed", value: precondition, evidence: evidence("deck-observation") } }];
  state.readings = [{ target, deck: { kind: "known", precondition: structuredClone(precondition) }, observation: { status: "observed", value: { kind: "boolean", value: false }, evidence: evidence("play-observation") } }];
  const refs = { catalog: {
    sessionId: state.sessionId, hostInstanceId: state.hostInstanceId, connectionGeneration: 1, capabilityRevision: 1, profile: structuredClone(state.profile), schemaVersion: 1, catalogId: "catalog1",
    instances: [structuredClone(instance)], retainedEvidenceIds: ["event1", "presence1", "absence1", "remove1"],
    decks: [{ deckId: "deck1", deckGeneration: 1, availability: { status: "present", evidenceIds: ["presence1"] }, maxAgeMs: 500 }],
    entries: [{ target: structuredClone(target), read: { kind: "state", value: { kind: "boolean" }, delivery: "poll", maxAgeMs: 500, existence: "explicit-presence-required" }, availability: { status: "present", evidenceIds: ["presence1"] }, applicableDeck: { deckId: "deck1", deckGeneration: 1 } }],
  } };
  return { state, refs };
}
function stateResult(f: ReturnType<typeof stateFixture>) {
  return validateObservedStateMessage(f.state, f.refs as StateValidationReferences);
}
function deltaFixture() {
  const f = stateFixture();
  f.refs.baseline = structuredClone(f.state);
  f.state = { ...f.state, kind: "delta", messageId: "message2", stateRevision: 2, sequence: 2, baseRevision: 1, previousSequence: 1, producedAtMs: 220, changes: [] };
  delete f.state.replacement; delete f.state.decks; delete f.state.readings;
  return f;
}
function success(f: ReturnType<typeof stateFixture>) {
  const result = stateResult(f);
  assert.equal(result.ok, true, JSON.stringify(result));
  return result;
}

test("admits real loaded and empty deck observations with exact binding and presence", () => {
  const loaded = stateFixture(); success(loaded);
  const empty = stateFixture(); empty.state.decks[0].current.value.binding = { kind: "empty" };
  empty.state.readings[0].deck.precondition.binding = { kind: "empty" }; success(empty);
  const noEntries = stateFixture(); noEntries.state.decks = []; noEntries.state.readings = []; success(noEntries);
  failure(validateObservedStateMessage(snapshot()), "catalog-required");
});

test("accepts stale old host/connection/clock evidence without treating foreign times as current", () => {
  const f = stateFixture();
  for (const owner of [f.state.decks[0], f.state.readings[0]]) {
    const key = owner.current ? "current" : "observation", old = owner[key];
    old.evidence.hostInstanceId = "old-host"; old.evidence.connectionGeneration = 99; old.evidence.clockId = "old-clock";
    old.evidence.stateRevision = 900; old.evidence.observedAtMs = 9000; old.evidence.receivedAtMs = 9001; old.evidence.validUntilMs = 9100;
    owner[key] = { status: "stale", lastKnown: { value: old.value, evidence: old.evidence }, reason: "connection-changed" };
  }
  success(f);
  const invalid = stateFixture(); invalid.state.readings[0].observation.evidence.clockId = "old-clock";
  failure(stateResult(invalid), "context-mismatch");
});

test("requires exact full current catalog profile, target, instance, parents and definitions", () => {
  const cases: Array<[string, (f: ReturnType<typeof stateFixture>) => void]> = [
    ["catalog-context-mismatch", f => { f.state.profile.buildId = "other-build"; }],
    ["catalog-context-mismatch", f => { f.state.profile.configurationId = "other-config"; }],
    ["catalog-context-mismatch", f => { f.state.capabilityRevision = 2; }],
    ["unresolved-capability-reference", f => { f.state.readings[0].target.instance.generation = 2; }],
    ["unresolved-capability-reference", f => { f.state.readings[0].target.instance.definitionId = "other-definition"; }],
    ["unresolved-capability-reference", f => { f.state.readings[0].target.instance.parent = { instanceId: "ghost", generation: 1 }; }],
    ["unresolved-capability-reference", f => { f.state.readings[0].target.capabilityId = "mixxx.unknown"; }],
    ["invalid-capability-id", f => { f.state.readings[0].target.capabilityId = "mixxx."; }],
    ["catalog-instance-mismatch", f => { f.refs.catalog.entries[0].target.instance.definitionId = "forged"; }],
    ["instance-parent-mismatch", f => { f.refs.catalog.instances[0].parent = { instanceId: "ghost", generation: 1 }; }],
    ["instance-cycle", f => { f.refs.catalog.instances[0].parent = { instanceId: "instance1", generation: 1 }; }],
    ["duplicate-instance", f => { f.refs.catalog.instances.push({ ...f.refs.catalog.instances[0], generation: 2 }); }],
    ["catalog-deck-mismatch", f => { f.refs.catalog.entries[0].applicableDeck.deckGeneration = 2; }],
  ];
  for (const [code, mutate] of cases) { const f = stateFixture(); mutate(f); failure(stateResult(f), code); }
});

test("requires target-specific presence and retained evidence; missing never becomes zero", () => {
  const absent = stateFixture(); absent.refs.catalog.entries[0].availability = { status: "absent", evidenceIds: ["absence1"] };
  absent.state.readings[0].observation = { status: "missing", reason: "control-absent", presenceEvidenceIds: ["absence1"] }; success(absent);
  for (const availability of [{ status: "unknown", reason: "not probed" }, { status: "absent", evidenceIds: ["absence1"] }]) {
    const f = stateFixture(); f.refs.catalog.entries[0].availability = availability; failure(stateResult(f), "presence-required");
  }
  const wrong = structuredClone(absent); wrong.state.readings[0].observation.presenceEvidenceIds = ["presence1"]; failure(stateResult(wrong), "absence-required");
  const missing = stateFixture(); missing.refs.catalog.entries[0].availability.evidenceIds = []; failure(stateResult(missing), "empty-array");
  const unresolved = stateFixture(); unresolved.state.readings[0].observation.evidence.source.eventId = "missing-event"; failure(stateResult(unresolved), "unresolved-evidence");
});

test("checks readable kinds, numeric units/ranges/tolerances and enum choices", () => {
  const numberFixture = () => {
    const f = stateFixture(); f.refs.catalog.entries[0].read.value = { kind: "number", unit: "normalized", minimum: 0, maximum: 1, step: null, tolerance: 0.01, neutralValue: 0.5, mappingId: "volume-mapping" };
    f.state.readings[0].observation.value = { kind: "number", unit: "normalized", value: 0.5 }; return f;
  };
  success(numberFixture());
  const cases: Array<[string, (f: ReturnType<typeof stateFixture>) => void]> = [
    ["catalog-unit-mismatch", f => { f.state.readings[0].observation.value.unit = "beats"; }],
    ["catalog-range-mismatch", f => { f.state.readings[0].observation.value.value = 1.01; }],
    ["invalid-value-range", f => { f.refs.catalog.entries[0].read.value.maximum = 2; }],
    ["invalid-value-range", f => { f.refs.catalog.entries[0].read.value.minimum = 2; }],
    ["invalid-value-range", f => { f.refs.catalog.entries[0].read.value.tolerance = -1; }],
    ["invalid-step", f => { f.refs.catalog.entries[0].read.value.step = 0; }],
    ["invalid-neutral", f => { f.refs.catalog.entries[0].read.value.neutralValue = -1; }],
    ["invalid-enum", f => { f.refs.catalog.entries[0].read.value.unit = "hz"; }],
  ];
  for (const [code, mutate] of cases) { const f = numberFixture(); mutate(f); failure(stateResult(f), code); }
  const en = stateFixture(); en.refs.catalog.entries[0].read.value = { kind: "enum", values: ["off", "on"] }; en.state.readings[0].observation.value = { kind: "enum", value: "off" }; success(en);
  en.state.readings[0].observation.value.value = "other"; failure(stateResult(en), "catalog-enum-mismatch");
  en.refs.catalog.entries[0].read.value.values = ["off", "off"]; failure(stateResult(en), "duplicate");
  en.refs.catalog.entries[0].read.value.values = []; failure(stateResult(en), "empty-array");
  const unreadable = stateFixture(); unreadable.refs.catalog.entries[0].read = { kind: "not-readable", reason: "no feedback" }; failure(stateResult(unreadable), "not-readable");
});

test("rejects deck/precondition mismatches, missing applicability and conflicting snapshot keys", () => {
  const cases: Array<[string, (f: ReturnType<typeof stateFixture>) => void]> = [
    ["deck-context-mismatch", f => { f.state.decks[0].current.value.deckId = "deck2"; }],
    ["catalog-deck-mismatch", f => { f.state.decks[0].deckGeneration = 2; }],
    ["reading-deck-mismatch", f => { f.state.readings[0].deck = null; }],
    ["reading-deck-mismatch", f => { f.state.readings[0].deck.precondition.deckGeneration = 2; }],
    ["reading-binding-mismatch", f => { f.state.readings[0].deck.precondition.trackGeneration = 2; }],
    ["reading-binding-mismatch", f => { f.state.readings[0].deck.precondition.binding.track.trackId = "track2"; }],
    ["unknown-deck-observed", f => { f.state.readings[0].deck = { kind: "unknown", deckId: "deck1", deckGeneration: 1 }; }],
    ["duplicate-deck", f => { f.state.decks.push({ ...f.state.decks[0], deckGeneration: 2 }); }],
    ["duplicate-reading", f => { f.state.readings.push(structuredClone(f.state.readings[0])); }],
  ];
  for (const [code, mutate] of cases) { const f = stateFixture(); mutate(f); failure(stateResult(f), code); }
});

test("delta validates full immutable baseline and untouched observations without refreshing them", () => {
  const f = deltaFixture(), before = JSON.stringify(f.refs.baseline);
  const result = success(f);
  assert.equal(JSON.stringify(f.refs.baseline), before);
  if (result.ok) { assert.equal(Object.isFrozen(result.value), true); assert.equal(Object.isFrozen(result.value.profile), true); }
  f.state.producedAtMs = 300; failure(stateResult(f), "expired-observation");
  const profile = deltaFixture(); profile.state.profile.skinRevision = "other"; failure(stateResult(profile), "catalog-context-mismatch");
  const baseline = deltaFixture(); baseline.refs.baseline.profile.skinRevision = "other"; failure(stateResult(baseline), "baseline-mismatch");
  const sequence = deltaFixture(); sequence.state.sequence = 4; failure(stateResult(sequence), "invalid-delta-lineage");
  const absent = deltaFixture(); delete absent.refs.baseline; failure(stateResult(absent), "baseline-required");
  const missingState = deltaFixture(); delete missingState.refs.baseline.readings; failure(stateResult(missingState), "missing-field");
});

test("atomic track replacement rejects untouched old bindings but accepts complete safe replacement", () => {
  const f = deltaFixture(), newDeck = structuredClone(f.refs.baseline.decks[0]);
  newDeck.current.value.trackGeneration = 2; newDeck.current.value.binding.track.trackId = "track2";
  newDeck.current.evidence.observationId = "deck-observation2"; newDeck.current.evidence.stateRevision = 2;
  f.state.changes = [{ kind: "replace-deck", deck: newDeck }];
  failure(stateResult(f), "reading-binding-mismatch");
  const reading = structuredClone(f.refs.baseline.readings[0]); reading.deck.precondition = structuredClone(newDeck.current.value);
  reading.observation.evidence.observationId = "play-observation2"; reading.observation.evidence.stateRevision = 2;
  f.state.changes.push({ kind: "replace-reading", reading }); success(f);
  const before = JSON.stringify(f.refs.baseline); success(f); assert.equal(JSON.stringify(f.refs.baseline), before);
  const relabel = structuredClone(f); relabel.state.changes[1].reading.observation.evidence.observationId = "play-observation"; relabel.state.changes[1].reading.observation.evidence.stateRevision = 1; failure(stateResult(relabel), "observation-conflict");
  const generation = structuredClone(f); generation.state.changes[0].deck.current.value.trackGeneration = 1; failure(stateResult(generation), "track-generation-required");
});

test("atomic removal requires exact existing entries and removal/invalidation of dependent readings", () => {
  const f = deltaFixture(); f.state.changes = [{ kind: "remove-deck", deckId: "deck1", deckGeneration: 1, evidenceIds: ["remove1"] }];
  failure(stateResult(f), "reading-deck-mismatch");
  f.state.changes.push({ kind: "remove-reading", target: structuredClone(f.refs.baseline.readings[0].target), evidenceIds: ["remove1"] }); success(f);
  const wrong = structuredClone(f); wrong.state.changes[1].target.instance.generation = 2; failure(stateResult(wrong), "remove-missing-incarnation");
  const nonexistent = deltaFixture(); nonexistent.state.changes = [{ kind: "remove-deck", deckId: "ghost", deckGeneration: 1, evidenceIds: ["remove1"] }]; failure(stateResult(nonexistent), "remove-missing-incarnation");
  const duplicate = deltaFixture(); duplicate.state.changes = [{ kind: "replace-deck", deck: structuredClone(duplicate.refs.baseline.decks[0]) }, { kind: "remove-deck", deckId: "deck1", deckGeneration: 1, evidenceIds: ["remove1"] }]; failure(stateResult(duplicate), "duplicate-change");
  const stale = deltaFixture(); const reading = structuredClone(stale.refs.baseline.readings[0]);
  reading.observation = { status: "stale", reason: "identity-changed", lastKnown: { value: reading.observation.value, evidence: reading.observation.evidence } };
  stale.state.changes = [{ kind: "remove-deck", deckId: "deck1", deckGeneration: 1, evidenceIds: ["remove1"] }, { kind: "replace-reading", reading }]; success(stale);
});

test("replacement snapshots enforce lineage and preserve immutable observation identities", () => {
  const f = stateFixture(); f.refs.baseline = structuredClone(f.state);
  f.state.snapshotId = "snapshot2"; f.state.messageId = "message2"; f.state.sequence = 3; f.state.stateRevision = 3; success(f);
  f.state.readings[0].observation.evidence.validUntilMs = 350; failure(stateResult(f), "observation-conflict");
  const reused = stateFixture(); reused.refs.baseline = structuredClone(reused.state); reused.state.messageId = "message2"; reused.state.sequence = 2; reused.state.stateRevision = 2; failure(stateResult(reused), "snapshot-lineage");
  const message = deltaFixture(); message.state.messageId = "message1"; failure(stateResult(message), "message-id-conflict");
});



test("unknown, uncertain, independent singleton and resolved parent instances remain admissible", () => {
  const unknown = stateFixture(); unknown.state.decks[0].current = { status: "unknown", reason: "identity-unresolved" };
  unknown.state.readings[0].deck = { kind: "unknown", deckId: "deck1", deckGeneration: 1 };
  unknown.state.readings[0].observation = { status: "unknown", reason: "not-observed" }; success(unknown);
  unknown.state.readings[0].observation = { status: "uncertain", reason: "binding-ambiguous", evidenceIds: ["event1"] }; success(unknown);
  const independent = stateFixture(); independent.state.readings[0].target.instance = null; independent.state.readings[0].deck = null;
  independent.refs.catalog.entries[0].target.instance = null; independent.refs.catalog.entries[0].applicableDeck = null; success(independent);
  const parent = stateFixture(); const outer = { instanceId: "parent", generation: 2, kind: "effect-unit", definitionId: "rack", parent: null };
  parent.refs.catalog.instances.push(outer);
  for (const instance of [parent.state.readings[0].target.instance, parent.refs.catalog.entries[0].target.instance, parent.refs.catalog.instances[0]]) instance.parent = { instanceId: "parent", generation: 2 };
  success(parent);
  parent.refs.catalog.instances[1].generation = 3; failure(stateResult(parent), "instance-parent-mismatch");
});

test("state and trusted reference data reject hidden execution hooks and duplicate JSON keys", () => {
  const f = stateFixture(); let read = false;
  Object.defineProperty(f.refs, "baseline", { enumerable: true, get: () => { read = true; return f.state; } });
  failure(stateResult(f), "non-json"); assert.equal(read, false);
  const json = JSON.stringify(action());
  failure(validateSemanticAction(json.replace('"sequence":1', '"sequence":0,"sequence":1')), "duplicate-json-key");
  failure(validateSemanticAction(json.replace('"sequence":1', '"seq\\u0075ence":0,"sequence":1')), "duplicate-json-key");
  const data = stateFixture(); data.state.kind = "requested-state"; failure(stateResult(data), "invalid-state-kind");
  const extra = stateFixture(); extra.state.readings[0].observation.value.script = "arbitrary"; failure(stateResult(extra), "unknown-field");
});

test("same-context snapshot replacement also checks track generations and unchanged evidence", () => {
  const f = stateFixture(); f.refs.baseline = structuredClone(f.state);
  f.state.snapshotId = "snapshot2"; f.state.messageId = "message2"; f.state.sequence = 2; f.state.stateRevision = 2;
  f.state.decks[0].current.value.binding.track.trackId = "track2";
  f.state.decks[0].current.evidence.observationId = "deck2";
  f.state.readings = [];
  failure(stateResult(f), "track-generation-required");
  f.state.decks[0].current.value.trackGeneration = 2; success(f);
  f.state.decks[0].current.value.trackGeneration = 0; failure(stateResult(f), "track-generation-regression");
});

test("freshness and observation identity checks include profile-change history and delta failures", () => {
  const f = stateFixture(); f.state.readings[0].observation.evidence.receivedAtMs = 201; failure(stateResult(f), "future-evidence");
  f.state.readings[0].observation.evidence.receivedAtMs = 150; f.state.readings[0].observation.evidence.validUntilMs = 601; failure(stateResult(f), "catalog-age-mismatch");
  const historical = stateFixture(); const old = historical.state.readings[0].observation;
  historical.state.readings[0].observation = { status: "stale", reason: "profile-changed", lastKnown: { value: { kind: "number", unit: "ratio", value: 2 }, evidence: old.evidence } }; success(historical);
  const failureCase = deltaFixture(); const before = structuredClone(failureCase.refs);
  failureCase.state.changes = [{ kind: "remove-deck", deckId: "deck1", deckGeneration: 1, evidenceIds: ["remove1"] }]; failure(stateResult(failureCase), "reading-deck-mismatch");
  assert.deepEqual(failureCase.refs, before); assert.equal(Object.isFrozen(failureCase.refs.baseline), false);
  const duplicateDefinition = stateFixture(); const entry = structuredClone(duplicateDefinition.refs.catalog.entries[0]); entry.target.instance = null; duplicateDefinition.refs.catalog.entries.push(entry); failure(stateResult(duplicateDefinition), "catalog-definition-conflict");
});



test("context-changing snapshots require the old catalog for full baseline validation and fresh current evidence", () => {
  const f = stateFixture(); f.refs.baseline = structuredClone(f.state); f.refs.baselineCatalog = structuredClone(f.refs.catalog);
  f.state.profile.skinRevision = "skinrev2"; f.refs.catalog.profile.skinRevision = "skinrev2";
  f.state.capabilityRevision = 2; f.refs.catalog.capabilityRevision = 2;
  f.state.snapshotId = "snapshot2"; f.state.messageId = "message2"; f.state.sequence = 2; f.state.stateRevision = 2;
  failure(stateResult(f), "observation-resurrection");
  for (const owner of [f.state.decks[0], f.state.readings[0]]) {
    const key = owner.current ? "current" : "observation", old = owner[key];
    owner[key] = { status: "stale", reason: "profile-changed", lastKnown: { value: old.value, evidence: old.evidence } };
  }
  success(f);
  const noOldCatalog = structuredClone(f); delete noOldCatalog.refs.baselineCatalog; failure(stateResult(noOldCatalog), "baseline-catalog-required");
  const resurrect = deltaFixture(); const old = resurrect.refs.baseline.readings[0].observation;
  resurrect.refs.baseline.readings[0].observation = { status: "stale", reason: "stream-gap", lastKnown: { value: old.value, evidence: old.evidence } };
  resurrect.state.changes = [{ kind: "replace-reading", reading: { ...resurrect.refs.baseline.readings[0], observation: old } }]; failure(stateResult(resurrect), "observation-resurrection");
});

test("instance replacement requires a new catalog snapshot and never accepts old target incarnations", () => {
  const delta = deltaFixture(); const wrong = structuredClone(delta.refs.baseline.readings[0]); wrong.target.instance.generation = 2;
  delta.state.changes = [{ kind: "replace-reading", reading: wrong }]; failure(stateResult(delta), "unresolved-capability-reference");
  const next = stateFixture(); next.refs.baseline = structuredClone(next.state); next.refs.baselineCatalog = structuredClone(next.refs.catalog);
  next.state.capabilityRevision = 2; next.refs.catalog.capabilityRevision = 2;
  next.state.snapshotId = "snapshot2"; next.state.messageId = "message2"; next.state.sequence = 2; next.state.stateRevision = 2;
  next.refs.catalog.instances[0].generation = 2; next.refs.catalog.entries[0].target.instance.generation = 2;
  next.refs.catalog.instances[0].definitionId = "new-definition"; next.refs.catalog.entries[0].target.instance.definitionId = "new-definition";
  next.state.decks[0].current.evidence.observationId = "new-deck-observation";
  failure(stateResult(next), "unresolved-capability-reference");
  next.state.readings[0].target = structuredClone(next.refs.catalog.entries[0].target);
  next.state.readings[0].observation.evidence.observationId = "new-read-observation"; success(next);
});



test("candidate projection must fit admission capacity even when baseline and delta individually fit", () => {
  const f = deltaFixture(), retained = Array.from({ length: 64 }, (_, i) => `event${String(i).padStart(3, "0")}${"x".repeat(112)}`);
  f.refs.catalog.retainedEvidenceIds.push(...retained);
  f.refs.catalog.entries = []; f.refs.catalog.instances = [];
  f.refs.baseline.readings = []; f.state.changes = [];
  for (let i = 0; i < 10; i += 1) {
    const model = stateFixture(), reading = model.state.readings[0], rules = model.refs.catalog.entries[0];
    reading.target = { capabilityId: `mixxx.control${i}`, instance: null }; reading.deck = null;
    reading.observation.evidence.observationId = `reading${i}`;
    reading.observation.evidence.source = { kind: "host-reconciled", eventIds: retained };
    rules.target = structuredClone(reading.target); rules.applicableDeck = null;
    f.refs.catalog.entries.push(rules);
    if (i < 4) f.refs.baseline.readings.push(reading);
    else f.state.changes.push({ kind: "replace-reading", reading });
  }
  assert.ok(new TextEncoder().encode(JSON.stringify(f.refs)).length < VALIDATION_LIMITS.maxTransportBytes);
  assert.ok(new TextEncoder().encode(JSON.stringify(f.state)).length < VALIDATION_LIMITS.maxTransportBytes);
  failure(stateResult(f), "payload-too-large");
});



test("catalog changes cannot reset sequence counters inside an unchanged stream epoch", () => {
  const f = stateFixture(); f.refs.baseline = structuredClone(f.state); f.refs.baselineCatalog = structuredClone(f.refs.catalog);
  f.state.capabilityRevision = 2; f.refs.catalog.capabilityRevision = 2;
  f.state.snapshotId = "snapshot2"; f.state.messageId = "message2"; f.state.decks = []; f.state.readings = [];
  failure(stateResult(f), "snapshot-lineage");
  f.state.sequence = 2; f.state.stateRevision = 2; success(f);
  const reset = structuredClone(f); reset.state.streamGeneration = 2; reset.state.sequence = 0; reset.state.stateRevision = 0; success(reset);
  const regression = structuredClone(f); regression.state.streamGeneration = 0; failure(stateResult(regression), "context-generation-regression");
});

test("stream resets retain explicitly stale evidence without comparing old revision counters", () => {
  const f = stateFixture(); f.refs.baseline = structuredClone(f.state);
  f.state.snapshotId = "snapshot2"; f.state.messageId = "message2"; f.state.streamGeneration = 2;
  f.state.sequence = 0; f.state.stateRevision = 0; f.state.producedAtMs = 220;
  for (const entry of [f.state.decks[0], f.state.readings[0]]) {
    const key = "current" in entry ? "current" : "observation", previous = entry[key];
    entry[key] = { status: "stale", lastKnown: { value: previous.value, evidence: previous.evidence }, reason: "stream-gap" };
  }
  success(f);
  const current = structuredClone(f), remembered = current.state.decks[0].current.lastKnown;
  current.state.decks[0].current = { status: "observed", ...remembered };
  failure(stateResult(current), "future-evidence");
  const altered = structuredClone(f); altered.state.readings[0].observation.lastKnown.evidence.stateRevision = 900;
  failure(stateResult(altered), "observation-conflict");
  const futureTime = structuredClone(f); futureTime.state.readings[0].observation.lastKnown.evidence.receivedAtMs = 221;
  failure(stateResult(futureTime), "future-evidence");
  const ordinaryStale = structuredClone(f); ordinaryStale.state.decks[0].current.reason = "age-expired";
  failure(stateResult(ordinaryStale), "future-evidence");
  const following = structuredClone(f); following.refs.baseline = structuredClone(f.state);
  following.state = { ...following.state, kind: "delta", messageId: "message3", sequence: 1, stateRevision: 1, producedAtMs: 230, baseRevision: 0, previousSequence: 0, changes: [] };
  delete following.state.replacement; delete following.state.decks; delete following.state.readings;
  success(following);
});



test("reference components have independent byte/node budgets with a guarded fixed wrapper", () => {
  const f = deltaFixture(), retained = Array.from({ length: 64 }, (_, i) => `event${String(i).padStart(3, "0")}${"x".repeat(112)}`);
  f.refs.catalog.retainedEvidenceIds.push(...retained);
  f.refs.catalog.entries = []; f.refs.catalog.instances = []; f.refs.baseline.readings = [];
  let additional: TestRecord | undefined;
  for (let i = 0; i < 8; i += 1) {
    const model = stateFixture(), reading = model.state.readings[0], rules = model.refs.catalog.entries[0];
    reading.target = { capabilityId: `mixxx.control${i}`, instance: null }; reading.deck = null;
    reading.observation.evidence.observationId = `reading${i}`;
    reading.observation.evidence.source = { kind: "host-reconciled", eventIds: retained };
    rules.target = structuredClone(reading.target); rules.applicableDeck = null; f.refs.catalog.entries.push(rules);
    if (i < 7) f.refs.baseline.readings.push(reading); else additional = reading;
  }
  const size = (value: unknown) => new TextEncoder().encode(JSON.stringify(value)).length;
  assert.ok(size(f.refs.baseline) < VALIDATION_LIMITS.maxTransportBytes);
  assert.ok(size(f.refs.catalog) < VALIDATION_LIMITS.maxTransportBytes);
  assert.ok(size(f.refs) > VALIDATION_LIMITS.maxTransportBytes);
  success(f);
  f.refs.baselineCatalog = structuredClone(f.refs.catalog); success(f);
  const overflow = structuredClone(f); overflow.refs.baseline.readings.push(additional);
  assert.ok(size(overflow.refs.baseline) > VALIDATION_LIMITS.maxTransportBytes);
  failure(stateResult(overflow), "payload-too-large");
  const wrapper = stateFixture(); let invoked = false;
  Object.defineProperty(wrapper.refs, "baselineCatalog", { enumerable: true, get: () => { invoked = true; return wrapper.refs.catalog; } });
  failure(stateResult(wrapper), "non-json"); assert.equal(invoked, false);
  const symbol = stateFixture(); Object.defineProperty(symbol.refs, Symbol("hidden"), { value: 1 }); failure(stateResult(symbol), "non-json");
});



test("reconciled occurrence association preserves track generation but invalidates old reading bindings", () => {
  const f = deltaFixture(), deck = structuredClone(f.refs.baseline.decks[0]);
  deck.current.value.binding.occurrence = { setId: "set1", occurrenceId: "occurrence1", generation: 1 };
  deck.current.evidence.observationId = "associated-deck";
  deck.current.evidence.source = { kind: "host-reconciled", eventIds: ["event1"] };
  f.state.changes = [{ kind: "replace-deck", deck }]; failure(stateResult(f), "reading-binding-mismatch");
  const reading = structuredClone(f.refs.baseline.readings[0]); reading.deck.precondition = structuredClone(deck.current.value);
  reading.observation.evidence.observationId = "associated-reading";
  f.state.changes.push({ kind: "replace-reading", reading }); success(f);
  assert.equal(deck.current.value.trackGeneration, f.refs.baseline.decks[0].current.value.trackGeneration);
});

// End of autonomously AI-generated test.

type Mutable<T> = { -readonly [K in keyof T]: Mutable<T[K]> };
type SyncFixture = Mutable<import("../../core/actions.ts").SyncSemanticAction>;
function syncAction(count = 2): SyncFixture {
  const base = action();
  let serial = 0;
  const expected = <T extends boolean | number | import("../../core/actions.ts").SyncMode>(value: T) => ({ value, observationId: `sync-observation-${serial++}` });
  const participants = Array.from({ length: count }, (_, i) => ({
    deckId: `deck${i + 1}`, syncEnabled: expected(false), syncMode: expected("none" as const),
    playing: expected(false), audible: expected(false), passthrough: expected(false as const), vinylControl: expected(false as const), quantize: expected(true),
    eligibility: { kind: "loaded" as const, syncEligible: expected(true as const), beatGridReady: expected(true as const), fileBpm: expected(120), effectiveBpm: expected(120), rateRatio: expected(1), beatPhase: expected(0) },
  }));
  return {
    ...base, schemaVersion: 2,
    preconditions: { ...(base.preconditions as SyncFixture["preconditions"]),
      decks: participants.map(({ deckId }) => ({ deckId, deckGeneration: 1, trackGeneration: 1, binding: { kind: "loaded", track: { libraryId: "library1", trackId: `track-${deckId}` }, occurrence: null } })),
      conditions: [{ kind: "sync-context", topologyEvidenceId: "topology1", topologyRevision: 1, participants,
        leader: { kind: "none" }, leaderObservationId: "leader-observation", internalClockBpm: expected(120), pendingSyncChange: expected(false as const),
        effectPolicy: { policyId: "policy1", maxTempoChangeRatio: 0.06, maxPhaseDisplacementBeats: 0 },
      }],
    },
    authority: { ...(base.authority as SyncFixture["authority"]), ownership: [
      ...participants.map(({ deckId }) => ({ resource: { kind: "deck-sync" as const, deckId }, ownershipGeneration: 1, grantId: `grant-${deckId}` })),
      { resource: { kind: "sync-engine" }, ownershipGeneration: 1, grantId: "grant-engine" },
    ] },
    operation: { kind: "desired-state", action: "deck.set_sync_enabled", deckId: "deck1", args: { enabled: true } },
  } as SyncFixture;
}

test("sync v2 admits both desired booleans, one to sixteen participants and immutable JSON copies", () => {
  for (const count of [1, 2, 16]) for (const enabled of [false, true]) {
    const input = syncAction(count); input.operation.args.enabled = enabled;
    const result = validateSemanticAction(JSON.stringify(input));
    assert.equal(result.ok, true, JSON.stringify(result));
    if (result.ok && result.value.schemaVersion === 2) {
      assert.equal(Object.isFrozen(result.value.preconditions.conditions[0].participants[0]?.eligibility), true);
      input.operation.args.enabled = !enabled;
      assert.equal(result.value.operation.args.enabled, enabled);
    }
  }
  const largest = JSON.stringify(syncAction(16), (key, value: unknown) =>
    key.endsWith("Id") && typeof value === "string" ? value.padEnd(128, "x") : value);
  assert.ok(Buffer.byteLength(largest) <= VALIDATION_LIMITS.maxTransportBytes);
  assert.equal(validateSemanticAction(largest).ok, true);
  failure(validateSemanticAction(syncAction(17)), "array-too-large");
});

test("sync versions cannot reinterpret legacy actions, resources, cleanup authority or arbitrary operations", () => {
  assert.equal(validateSemanticAction({ ...action(), schemaVersion: 2 }).ok, false);
  assert.equal(validateSemanticAction({ ...syncAction(), schemaVersion: 1 }).ok, false);
  for (const version of [0, 3, "2", null]) failure(validateSemanticAction({ ...syncAction(), schemaVersion: version }), "invalid-literal");
  const bad = syncAction(); bad.authority.ownership = (action().authority as SyncFixture["authority"]).ownership;
  assert.equal(validateSemanticAction(bad).ok, false);
  failure(validateSemanticAction({ ...syncAction(), authority: { kind: "release-cleanup", lease: { obligationId: "lease1", pressActionId: "press1", pressGeneration: 1 } } }), "invalid-authority-combination");
  for (const operation of [
    { ...syncAction().operation, action: "deck.beatsync" },
    { ...syncAction().operation, args: { enabled: 127 } },
    { ...syncAction().operation, args: { enabled: true, bpm: 120 } },
    { ...syncAction().operation, kind: "trigger" },
  ]) assert.equal(validateSemanticAction({ ...syncAction(), operation }).ok, false);
});

test("sync rejects missing, duplicate and unrelated roster, guard and grant entries", () => {
  const mutations: Array<(s: SyncFixture) => void> = [
    s => { s.preconditions.conditions = [] as unknown as SyncFixture["preconditions"]["conditions"]; },
    s => { s.preconditions.conditions.push(structuredClone(s.preconditions.conditions[0])); },
    s => { s.preconditions.conditions[0].participants = []; },
    s => { s.preconditions.conditions[0].participants.pop(); },
    s => { s.preconditions.conditions[0].participants[1]!.deckId = "deck1"; },
    s => { s.preconditions.conditions[0].participants[1]!.deckId = "deck3"; },
    s => { s.preconditions.decks.pop(); },
    s => { s.preconditions.decks[0]!.trackGeneration = -1; },
    s => { s.preconditions.conditions[0].topologyRevision = 1.5; },
    s => { s.operation.deckId = "deck3"; },
    s => { s.authority.ownership.pop(); },
    s => { s.authority.ownership[0]!.resource = { kind: "deck-sync", deckId: "deck3" }; },
    s => { s.authority.ownership.push(structuredClone(s.authority.ownership[0]!)); },
    s => { s.authority.ownership[0]!.ownershipGeneration = -1; },
    s => { s.authority.mode = "PlaylistOnly" as "B2B"; },
  ];
  for (const [index, mutate] of mutations.entries()) {
    const s = syncAction(); mutate(s); assert.equal(validateSemanticAction(s).ok, false, `mutation ${index}`);
  }
});

test("sync validates empty peers without invented BPM data and requires a loaded target", () => {
  const s = syncAction(); const peer = s.preconditions.conditions[0].participants[1]!;
  s.preconditions.decks[1]!.binding = { kind: "empty" };
  peer.eligibility = { kind: "empty", syncEligible: { value: false, observationId: "empty-observation" } };
  assert.equal(validateSemanticAction(s).ok, true);
  for (const field of ["playing", "audible", "syncEnabled"] as const) {
    const bad = structuredClone(s); bad.preconditions.conditions[0].participants[1]![field].value = true;
    assert.equal(validateSemanticAction(bad).ok, false);
  }
  s.operation.deckId = "deck2";
  failure(validateSemanticAction(s), "unknown-or-empty-binding");
  const mismatch = syncAction(); mismatch.preconditions.decks[1]!.binding = { kind: "empty" };
  assert.equal(validateSemanticAction(mismatch).ok, false);
});

test("sync requires consistent leader modes and distinct observations for every fact", () => {
  const s = syncAction(); const guard = s.preconditions.conditions[0];
  guard.participants[0]!.syncEnabled.value = true; guard.participants[0]!.syncMode.value = "leader-soft";
  guard.leader = { kind: "deck", deckId: "deck1" };
  assert.equal(validateSemanticAction(s).ok, true);
  guard.participants[0]!.syncMode.value = "leader-explicit";
  assert.equal(validateSemanticAction(s).ok, true);
  for (const leader of [{ kind: "none" }, { kind: "internal-clock" }, { kind: "deck", deckId: "deck2" }, { kind: "deck", deckId: "deck3" }] as const) {
    const bad = structuredClone(s); bad.preconditions.conditions[0].leader = leader;
    failure(validateSemanticAction(bad), "sync-leader-mismatch");
  }
  guard.participants[1]!.syncEnabled.value = true; guard.participants[1]!.syncMode.value = "leader-soft";
  failure(validateSemanticAction(s), "sync-leader-mismatch");
  const modes = syncAction(); modes.preconditions.conditions[0].participants[0]!.syncMode.value = "follower";
  failure(validateSemanticAction(modes), "sync-mode-mismatch");
  modes.preconditions.conditions[0].participants[0]!.syncEnabled.value = true;
  modes.preconditions.conditions[0].leader = { kind: "internal-clock" };
  assert.equal(validateSemanticAction(modes).ok, true);
  const duplicate = syncAction(); duplicate.preconditions.conditions[0].participants[1]!.playing.observationId = duplicate.preconditions.conditions[0].leaderObservationId;
  failure(validateSemanticAction(duplicate), "duplicate-observation");
  const crossDeck = syncAction(); crossDeck.preconditions.conditions[0].participants[1]!.quantize.observationId = crossDeck.preconditions.conditions[0].participants[0]!.quantize.observationId;
  failure(validateSemanticAction(crossDeck), "duplicate-observation");
});

test("sync guards enforce closed boolean, numeric, policy and observation bounds", () => {
  const s = syncAction(); const g = s.preconditions.conditions[0];
  for (const field of ["passthrough", "vinylControl"] as const) {
    const bad = structuredClone(s); Object.assign(bad.preconditions.conditions[0].participants[0]![field], { value: true });
    assert.equal(validateSemanticAction(bad).ok, false);
  }
  for (const [field, values] of Object.entries({ fileBpm: [0, -1, 1001], effectiveBpm: [0, 1001], rateRatio: [0, 4.001], beatPhase: [-0.01, 1] })) {
    for (const value of values) {
      const bad = structuredClone(s); const eligibility = bad.preconditions.conditions[0].participants[0]!.eligibility;
      Object.assign((eligibility as unknown as Record<string, object>)[field]!, { value });
      failure(validateSemanticAction(bad), "out-of-range");
    }
  }
  for (const [field, max] of [["maxTempoChangeRatio", 3], ["maxPhaseDisplacementBeats", 1]] as const) {
    for (const value of [0, max]) { g.effectPolicy[field] = value; assert.equal(validateSemanticAction(s).ok, true); }
    for (const value of [-0.01, max + 0.01]) { const bad = structuredClone(s); bad.preconditions.conditions[0].effectPolicy[field] = value; failure(validateSemanticAction(bad), "out-of-range"); }
  }
  for (const mutate of [
    (x: SyncFixture) => Object.assign(x.preconditions.conditions[0].pendingSyncChange, { value: true }),
    (x: SyncFixture) => Object.assign(x.preconditions.conditions[0].participants[0]!.playing, { fake: true }),
    (x: SyncFixture) => { x.preconditions.conditions[0].leaderObservationId = "bad\n"; },
    (x: SyncFixture) => { x.preconditions.conditions[0].internalClockBpm.value = 0; },
    (x: SyncFixture) => { x.preconditions.conditions[0].effectPolicy.maxTempoChangeRatio = Number.NaN; },
  ]) { const bad = syncAction(); mutate(bad); assert.equal(validateSemanticAction(bad).ok, false); }
});

test("v2 outcomes retain all existing status meanings without granting registry or host authority", () => {
  const base = { sessionId: "session1", actionId: "sync1", sequence: 1, schemaVersion: 2, eventId: "event1", clockId: "clock1", atMs: 100 };
  for (const variant of [
    { status: "requested" }, { status: "sent", attemptId: "attempt1", transportMessageIds: ["m1"] },
    { status: "accepted", attemptId: "attempt1", hostReceiptId: "receipt1" },
    { status: "observed", observation: { observationId: "obs1", hostInstanceId: "host1", connectionGeneration: 1, stateRevision: 1 }, condition: "satisfied", correlation: { kind: "state-only" }, attribution: { actor: "unknown" } },
    { status: "uncertain", attemptId: null, reason: "feedback-lost" }, { status: "rejected", stage: "host", reason: "host-rejected" },
    { status: "cancelled", reason: "human-takeover" }, { status: "expired", phase: "observation" },
  ]) {
    assert.equal(validateActionOutcome({ ...base, ...variant }).ok, true);
    assert.equal(validateActionOutcome({ ...base, ...variant, schemaVersion: 3 }).ok, false);
    assert.equal(validateActionOutcome({ ...base, ...variant, success: true }).ok, false);
  }
});
