// This file was autonomously generated by an AI agent at the user's request.

import assert from "node:assert/strict";
import test from "node:test";

import {
  BoundedEventBuffer,
  redactArtifactManifest,
} from "../../diagnostics/events.ts";
import type {
  CommandSentEvent,
  DiagnosticEventBase,
  HostObservedEvent,
  RawRecordedEvent,
  UiObservedEvent,
  AudioObservedEvent,
} from "../../diagnostics/events.ts";

const host = {
  hostInstanceId: "host-1",
  connectionGeneration: 2,
  profileId: "latenight",
  profileRevision: 3,
  capabilityRevision: 4,
  stateRevision: 5,
};

function base(eventId: string, atMs: number): DiagnosticEventBase {
  return {
    schemaVersion: 1,
    eventId,
    context: { sessionId: "session-1", correlationId: "correlation-1", host },
    localClockDomainId: "clock-local",
    atMs,
    capturedAtMs: atMs,
    sourceTimestamp: null,
  };
}

function raw(eventId: string, atMs: number, bytes: readonly number[] = [0x90, 60, 127]): RawRecordedEvent {
  return { ...base(eventId, atMs), kind: "raw-recorded", source: "physical-controller-midi", bytes, artifact: null };
}

test("preserves offered event order and distinguishes observed evidence sources", () => {
  const command: CommandSentEvent = {
    ...base("command-1", 10),
    kind: "command-sent",
    actionId: "action-1",
    attemptId: "attempt-1",
    transportMessageIds: ["midi-1"],
  };
  const observed: HostObservedEvent = {
    ...base("host-1", 11),
    kind: "host-observed",
    observationId: "observation-1",
    observationStatus: "recorded",
    evidenceEventIds: ["feedback-1"],
  };
  const ui: UiObservedEvent = {
    ...base("ui-1", 12),
    kind: "ui-observed",
    surfaceId: "mixxx-window",
    renderRevision: 1,
    observationStatus: "reported",
    artifact: null,
  };
  const audio: AudioObservedEvent = {
    ...base("audio-1", 13),
    kind: "audio-observed",
    sampleOffset: 480,
    observationStatus: "captured",
    artifact: { artifactId: "audio-artifact-1", manifestRevision: 1 },
  };

  const buffer = new BoundedEventBuffer(8);
  for (const event of [command, observed, ui, audio]) assert.equal(buffer.offer(event).status, "accepted");

  const drained = buffer.drain();
  assert.deepEqual(drained.events.map(({ captureSequence }) => captureSequence), [0, 1, 2, 3]);
  assert.deepEqual(drained.events.map(({ event }) => event.kind), ["command-sent", "host-observed", "ui-observed", "audio-observed"]);
  assert.deepEqual(drained.gaps, []);
});

test("reports bounded-buffer overflow as an explicit capture gap", () => {
  const buffer = new BoundedEventBuffer(2);
  assert.equal(buffer.offer(raw("one", 1)).status, "accepted");
  assert.equal(buffer.offer(raw("two", 2)).status, "accepted");
  assert.equal(buffer.offer(raw("three", 3)).status, "dropped");
  assert.equal(buffer.offer(raw("four", 4)).status, "dropped");

  const firstDrain = buffer.drain(1);
  assert.deepEqual(firstDrain.events.map(({ captureSequence }) => captureSequence), [0]);
  assert.deepEqual(firstDrain.gaps, [{
    firstDroppedCaptureSequence: 2,
    lastDroppedCaptureSequence: 3,
    droppedEventCount: 2,
    contiguous: true,
  }]);
  assert.equal(firstDrain.status.queuedEventCount, 1);
  assert.equal(firstDrain.status.droppedEventCount, 2);

  const secondDrain = buffer.drain();
  assert.deepEqual(secondDrain.events.map(({ captureSequence }) => captureSequence), [1]);
  assert.deepEqual(secondDrain.gaps, []);
});

test("copies and freezes events before accepting them", () => {
  const bytes = [0x90, 60, 127];
  const event = raw("copy", 20, bytes);
  const buffer = new BoundedEventBuffer(1);
  buffer.offer(event);

  bytes[0] = 0;
  host.profileId = "changed-after-offer";

  const captured = buffer.drain().events[0];
  assert.ok(captured);
  assert.equal(captured.event.context.host.profileId, "latenight");
  assert.equal((captured.event as RawRecordedEvent).bytes[0], 0x90);
  assert.equal(Object.isFrozen(captured), true);
  assert.equal(Object.isFrozen((captured.event as RawRecordedEvent).bytes), true);

  host.profileId = "latenight";
});

test("rejects invalid buffer limits and keeps admission atomic after validation or clone failure", () => {
  assert.throws(() => new BoundedEventBuffer(0), RangeError);
  assert.throws(() => new BoundedEventBuffer(1.5), RangeError);

  const buffer = new BoundedEventBuffer(2);
  const before = buffer.status();
  assert.throws(() => buffer.offer({ ...raw("extra-header", 1), extraHeader: true } as unknown as RawRecordedEvent), RangeError);
  assert.deepEqual(buffer.status(), before);
  assert.throws(() => buffer.offer({ ...raw("extra-payload", 1), extraFunction: () => undefined } as unknown as RawRecordedEvent), RangeError);
  assert.deepEqual(buffer.status(), before);
  assert.throws(() => buffer.offer(new Proxy(raw("proxy", 1), {}) as RawRecordedEvent));
  assert.deepEqual(buffer.status(), before);

  assert.throws(() => buffer.offer({ ...raw("bad-time", 1), atMs: Number.NaN }), RangeError);
  assert.throws(() => buffer.offer(raw("bad-byte-low", 1, [-1])), RangeError);
  assert.throws(() => buffer.offer(raw("bad-byte-high", 1, [300])), RangeError);
  assert.throws(() => buffer.offer(raw("oversized-bytes", 1, Array.from({ length: 1_025 }, () => 1))), RangeError);
  assert.throws(() => buffer.offer(raw("x".repeat(129), 1)), RangeError);
  assert.deepEqual(buffer.status(), before);

  assert.equal(buffer.offer(raw("later", 30)).status, "accepted");
  const earlierObserved = {
    ...raw("earlier-observed", 10),
    capturedAtMs: 31,
    sourceTimestamp: { clockDomainId: "host-clock", value: 4 },
  };
  assert.equal(buffer.offer(earlierObserved).status, "accepted");
  assert.throws(() => buffer.offer({ ...raw("late-capture", 32), capturedAtMs: 30 }), RangeError);
  assert.throws(() => buffer.drain(-1), RangeError);
});

test("redacts unnecessary artifact paths and metadata while retaining safe provenance", () => {
  const manifest = redactArtifactManifest({
    schemaVersion: 1,
    artifactId: "artifact-1",
    revision: 1,
    kind: "audio-capture",
    recordedAtMs: 50,
    clockDomainId: "audio-clock",
    opaqueLocalReference: "artifact-ref-1",
    absolutePath: "/Users/example/Music/private.wav",
    deviceIdentifier: "USB-Controller-serial-123",
    metadata: {
      contentType: "audio/wav",
      byteLength: 4_096,
      fileName: "private.wav",
      note: "operator note",
    },
  });

  assert.equal(Object.hasOwn(manifest, "absolutePath"), false);
  assert.equal(Object.hasOwn(manifest, "deviceIdentifier"), false);
  assert.deepEqual(manifest.metadata, { contentType: "audio/wav", byteLength: 4_096 });
  assert.deepEqual(manifest.redaction.removedFields, ["absolute-path", "device-identifier", "file-name", "note"]);
});

test("rejects accessors and malformed opaque IDs without invoking or mutating capture", () => {
  const buffer = new BoundedEventBuffer(2);
  const before = buffer.status();
  let invoked = false;
  const event = raw("event1", 10);
  Object.defineProperty(event, "kind", { enumerable: true, get: () => { invoked = true; return "raw-recorded"; } });
  assert.throws(() => buffer.offer(event));
  assert.equal(invoked, false);
  assert.deepEqual(buffer.status(), before);
  for (const eventId of ["event1\n", "../private", "bad id"]) {
    assert.throws(() => buffer.offer(raw(eventId, 10)));
    assert.deepEqual(buffer.status(), before);
  }
  const hidden = raw("event1", 10);
  Object.defineProperty(hidden, "extra", { value: "hidden" });
  assert.throws(() => buffer.offer(hidden));
  assert.deepEqual(buffer.status(), before);
});

// End of autonomously AI-generated file.
