// This file was autonomously generated by an AI agent at the user's request.

import assert from "node:assert/strict";
import test from "node:test";

import {
  PortNameCollisionError,
  openVirtualMidiConnection,
} from "../../midi/connection.ts";
import type {
  MidiConnectionBinding,
  NativeInputHandle,
  NativeOutputHandle,
  TransportLoss,
} from "../../midi/connection.ts";

class FakeInput implements NativeInputHandle {
  readonly ignoredTypes: [boolean, boolean, boolean][] = [];
  readonly openedNames: string[] = [];
  destroyCount = 0;
  closeCount = 0;
  listenerCount = 0;
  open = false;
  throwOnDestroy = false;
  private listener: ((deltaTimeSeconds: number, bytes: number[]) => void) | undefined;
  private readonly names: readonly string[];

  constructor(names: readonly string[] = []) {
    this.names = names;
  }

  getPortCount(): number { return this.names.length; }
  getPortName(index: number): string { return this.names[index] ?? ""; }
  isPortOpen(): boolean { return this.open; }
  ignoreTypes(sysex: boolean, timing: boolean, activeSensing: boolean): void { this.ignoredTypes.push([sysex, timing, activeSensing]); }
  on(_event: "message", listener: (deltaTimeSeconds: number, bytes: number[]) => void): void { this.listener = listener; this.listenerCount += 1; }
  removeListener(_event: "message", listener: (deltaTimeSeconds: number, bytes: number[]) => void): void { if (this.listener === listener) this.listener = undefined; }
  openVirtualPort(name: string): void { this.openedNames.push(name); this.open = true; }
  closePort(): void { this.closeCount += 1; this.open = false; }
  destroy(): void {
    this.destroyCount += 1;
    if (this.throwOnDestroy) throw new Error("input destroy failed");
  }
  emit(deltaTimeSeconds: number, bytes: number[]): void { this.listener?.(deltaTimeSeconds, bytes); }
}

class FakeOutput implements NativeOutputHandle {
  readonly openedNames: string[] = [];
  readonly sent: number[][] = [];
  destroyCount = 0;
  closeCount = 0;
  open = false;
  throwOnOpen = false;
  throwOnSend = false;
  private readonly names: readonly string[];

  constructor(names: readonly string[] = []) {
    this.names = names;
  }

  getPortCount(): number { return this.names.length; }
  getPortName(index: number): string { return this.names[index] ?? ""; }
  isPortOpen(): boolean { return this.open; }
  openVirtualPort(name: string): void {
    if (this.throwOnOpen) throw new Error("output open failed");
    this.openedNames.push(name);
    this.open = true;
  }
  closePort(): void { this.closeCount += 1; this.open = false; }
  destroy(): void { this.destroyCount += 1; }
  sendMessage(bytes: number[]): void {
    if (this.throwOnSend) throw new Error("send failed");
    this.sent.push([...bytes]);
  }
}

function binding(input: FakeInput, output: FakeOutput): MidiConnectionBinding {
  return {
    Input: class { constructor() { return input; } } as unknown as new () => NativeInputHandle,
    Output: class { constructor() { return output; } } as unknown as new () => NativeOutputHandle,
  };
}

function options(losses: TransportLoss[], feedback: number[][]) {
  return {
    portName: "AI DJ",
    onFeedback: (message: { readonly bytes: readonly number[] }) => feedback.push([...message.bytes]),
    onTransportLoss: (loss: TransportLoss) => losses.push(loss),
  };
}

test("opens separate same-name virtual directions, enables SysEx, copies feedback, and closes idempotently", () => {
  const input = new FakeInput();
  const output = new FakeOutput();
  const losses: TransportLoss[] = [];
  const feedback: number[][] = [];
  const connection = openVirtualMidiConnection(binding(input, output), options(losses, feedback));

  assert.deepEqual(input.ignoredTypes, [[false, true, true]]);
  assert.deepEqual(input.openedNames, ["AI DJ"]);
  assert.deepEqual(output.openedNames, ["AI DJ"]);
  input.emit(0.5, [0xf0, 0x7d, 0x01, 0xf7]);
  assert.deepEqual(feedback, [[0xf0, 0x7d, 0x01, 0xf7]]);
  assert.deepEqual(output.sent, []);

  connection.close();
  connection.close();
  assert.equal(connection.status, "closed");
  assert.equal(input.closeCount, 1);
  assert.equal(output.closeCount, 1);
  assert.equal(input.destroyCount, 1);
  assert.equal(output.destroyCount, 1);
  assert.equal(losses.length, 0);
  input.emit(0, [0xf0, 0x7d, 0x02, 0xf7]);
  assert.equal(feedback.length, 1);
});

test("cleans up the first direction when the second virtual port fails", () => {
  const input = new FakeInput();
  const output = new FakeOutput();
  output.throwOnOpen = true;
  const losses: TransportLoss[] = [];

  assert.throws(() => openVirtualMidiConnection(binding(input, output), options(losses, [])), /output open failed/);
  assert.equal(input.closeCount, 1);
  assert.equal(input.destroyCount, 1);
  assert.equal(output.destroyCount, 1);
  assert.equal(losses[0]?.reason, "startup-failed");
});

test("rejects external duplicate names before opening either direction", () => {
  const input = new FakeInput(["AI DJ"]);
  const output = new FakeOutput();
  const losses: TransportLoss[] = [];

  assert.throws(
    () => openVirtualMidiConnection(binding(input, output), options(losses, [])),
    (error: unknown) => error instanceof PortNameCollisionError && error.direction === "input",
  );
  assert.deepEqual(input.openedNames, []);
  assert.deepEqual(output.openedNames, []);
  assert.equal(input.destroyCount, 1);
  assert.equal(output.destroyCount, 1);
});

test("surfaces command-send transport loss and still cleans up both directions", () => {
  const input = new FakeInput();
  const output = new FakeOutput();
  output.throwOnSend = true;
  const losses: TransportLoss[] = [];
  const connection = openVirtualMidiConnection(binding(input, output), options(losses, []));

  assert.throws(() => connection.send([0xb0, 0x77, 0x2a]), /send failed/);
  assert.equal(connection.status, "lost");
  assert.equal(losses[0]?.reason, "send-failed");
  connection.close();
  assert.equal(input.destroyCount, 1);
  assert.equal(output.destroyCount, 1);
});

test("snapshots options and does not repeat disposal after a cleanup failure", () => {
  const input = new FakeInput();
  input.throwOnDestroy = true;
  const output = new FakeOutput();
  const losses: TransportLoss[] = [];
  const feedback: number[][] = [];
  const mutableOptions = options(losses, feedback);
  const connection = openVirtualMidiConnection(binding(input, output), mutableOptions);

  mutableOptions.portName = "renamed after open";
  assert.equal(connection.portName, "AI DJ");
  assert.throws(() => connection.close(), /input destroy failed/);
  assert.equal(connection.status, "lost");
  assert.equal(losses.at(-1)?.reason, "close-failed");
  assert.equal(input.destroyCount, 1);
  assert.equal(output.destroyCount, 1);
  connection.close();
  assert.equal(input.destroyCount, 1);
  assert.equal(output.destroyCount, 1);
  input.emit(0, [0xf0, 0x7d, 0x02, 0xf7]);
  assert.deepEqual(feedback, []);
});

test("rejects oversized external port inventories before opening", () => {
  const input = new FakeInput(Array.from({ length: 1_025 }, (_, index) => `port-${index}`));
  const output = new FakeOutput();
  const losses: TransportLoss[] = [];

  assert.throws(() => openVirtualMidiConnection(binding(input, output), options(losses, [])), /port count is invalid/);
  assert.deepEqual(input.openedNames, []);
  assert.deepEqual(output.openedNames, []);
  assert.equal(input.destroyCount, 1);
  assert.equal(output.destroyCount, 1);
});

// End of autonomously AI-generated file.
