// This file was autonomously generated by an AI agent at the user's request.
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

import { decodeConventionalFeedback } from "../../midi/conventional-decode.ts";

test("decodes all frozen feedback families and attaches only local unknown provenance", () => {
  const play = decodeConventionalFeedback([0xb8, 0x20, 0x7f], 101);
  assert.deepEqual(play, {
    kind: "value", controlId: "deck-1.play", capabilityId: "mixxx.deck.playing", deck: 1,
    meaning: "host-control-state", value: true, packet: [0xb8, 0x20, 0x7f],
    provenance: { receivedAtMs: 101, actor: "unknown", correlation: "none", hostObservation: "unproven" },
  });
  assert.equal(Object.isFrozen(play), true);
  if (play !== null) {
    assert.equal(Object.isFrozen(play.packet), true);
    assert.equal(Object.isFrozen(play.provenance), true);
  }
  assert.deepEqual(decodeConventionalFeedback([0xb9, 0x21, 64], 102), {
    kind: "value", controlId: "deck-2.volume", capabilityId: "mixxx.deck.volume", deck: 2,
    meaning: "host-control-state", value: 64 / 127, packet: [0xb9, 0x21, 64],
    provenance: { receivedAtMs: 102, actor: "unknown", correlation: "none", hostObservation: "unproven" },
  });
  assert.equal(decodeConventionalFeedback([0xba, 0x24, 64], 103)?.kind, "value");
  const crossfader = decodeConventionalFeedback([0xba, 0x24, 64], 103);
  assert.equal(crossfader?.kind, "value");
  if (crossfader?.kind === "value") assert.equal(crossfader.value, 0.5);
  const cue = decodeConventionalFeedback([0xb8, 0x23, 0x7f], 104);
  assert.equal(cue?.kind, "value");
  if (cue?.kind === "value") assert.equal(cue.meaning, "control-signal-only");
  const sync = decodeConventionalFeedback([0xb9, 0x22, 0], 105);
  assert.equal(sync?.kind, "value");
  if (sync?.kind === "value") assert.equal(sync.controlId, "deck-2.sync");
});

test("decodes exact presence values and never turns unknown or unavailable into zero", () => {
  assert.equal(decodeConventionalFeedback([0xb8, 0x71, 0], 1)?.kind, "presence");
  const unavailable = decodeConventionalFeedback([0xb8, 0x71, 0], 1);
  const unknown = decodeConventionalFeedback([0xb8, 0x71, 64], 2);
  const present = decodeConventionalFeedback([0xb8, 0x71, 127], 3);
  if (unavailable?.kind === "presence") assert.equal(unavailable.presence, "unavailable");
  if (unknown?.kind === "presence") assert.equal(unknown.presence, "unknown");
  if (present?.kind === "presence") assert.equal(present.presence, "present");
  assert.equal(decodeConventionalFeedback([0xb8, 0x71, 1], 4), null);
});

test("ignores malformed, irrelevant, noncanonical boolean, and all command/release packets", () => {
  assert.equal(decodeConventionalFeedback([0xb8, 0x20], 1), null);
  assert.equal(decodeConventionalFeedback([0xb8, 0x20, 0, 0], 1), null);
  assert.equal(decodeConventionalFeedback([0xb8, 0x20, 64], 1), null);
  assert.equal(decodeConventionalFeedback([0xb8, 0x7f, 0], 1), null);
  assert.equal(decodeConventionalFeedback([0xf8, 0, 0], 1), null);
  assert.equal(decodeConventionalFeedback([0x90, 0x23, 127], 1), null);
  assert.equal(decodeConventionalFeedback([0x90, 0x23, 0], 1), null);
  assert.equal(decodeConventionalFeedback([0x80, 0x23, 0], 1), null);
  assert.equal(decodeConventionalFeedback([0x81, 0x23, 127], 1), null);
  assert.equal(decodeConventionalFeedback([0xb8, 0x20, 128], 1), null);
});

test("requires bounded monotonic receipt time and has no externally visible side effects", () => {
  assert.throws(() => decodeConventionalFeedback([0xb8, 0x20, 0], Number.NaN), RangeError);
  assert.throws(() => decodeConventionalFeedback([0xb8, 0x20, 0], -1), RangeError);
  const input = [0xb8, 0x20, 0x7f];
  const decoded = decodeConventionalFeedback(input, 9);
  input[2] = 0;
  assert.equal(decoded?.kind, "value");
  if (decoded?.kind === "value") {
    assert.equal(decoded.value, true);
    assert.equal("requestId" in decoded, false);
    assert.equal("actionId" in decoded, false);
    assert.equal("lease" in decoded, false);
  }
});

test("matches every checked-in F09 feedback, presence, vector, and cue-release route", () => {
  const profile = JSON.parse(readFileSync(new URL("../../hosts/mixxx/conventional-profile.json", import.meta.url), "utf8")) as {
    controls: Array<{
      id: string;
      capabilityId: string;
      deck: 1 | 2 | null;
      command: { status: number; address: number; releaseStatus: number | null };
      feedback: { status: number; address: number; encoding: string; meaning: "host-control-state" | "control-signal-only" };
      presence: { status: number; address: number };
      examples: Array<{ decodedValue: number; feedbackBytes: [number, number, number] }>;
    }>;
  };
  assert.equal(profile.controls.length, 9);
  for (const control of profile.controls) {
    for (const vector of control.examples) {
      const decoded = decodeConventionalFeedback(vector.feedbackBytes, 100);
      assert.equal(decoded?.kind, "value", control.id);
      if (decoded?.kind !== "value") continue;
      assert.equal(decoded.controlId, control.id);
      assert.equal(decoded.capabilityId, control.capabilityId);
      assert.equal(decoded.deck, control.deck);
      assert.equal(decoded.meaning, control.feedback.meaning);
      const expected = control.feedback.encoding === "boolean-0-127"
        ? vector.decodedValue !== 0
        : vector.decodedValue;
      assert.equal(decoded.value, expected);
    }
    for (const [data, presence] of [[0, "unavailable"], [64, "unknown"], [127, "present"]] as const) {
      const decoded = decodeConventionalFeedback([control.presence.status, control.presence.address, data], 101);
      assert.equal(decoded?.kind, "presence", control.id);
      if (decoded?.kind !== "presence") continue;
      assert.equal(decoded.controlId, control.id);
      assert.equal(decoded.capabilityId, control.capabilityId);
      assert.equal(decoded.deck, control.deck);
      assert.equal(decoded.presence, presence);
    }
    if (!control.id.endsWith(".cue")) continue;
    for (const velocity of [0, 64, 127]) {
      assert.equal(decodeConventionalFeedback([control.command.status, control.command.address, velocity], 102), null, `${control.id} note-on ${velocity}`);
      assert.equal(decodeConventionalFeedback([control.command.releaseStatus ?? 0, control.command.address, velocity], 103), null, `${control.id} note-off ${velocity}`);
    }
  }
});

// End of autonomously AI-generated file.
