// This file was autonomously generated by an AI agent at the user's request.

import assert from "node:assert/strict";
import test from "node:test";

import {
  EndpointSelectionError,
  createMidiPortEnumerator,
  resolveExactEndpoints,
} from "../../midi/ports.ts";
import type { EnumeratedMidiHandle, MidiEnumerationBinding } from "../../midi/ports.ts";

class FakeHandle implements EnumeratedMidiHandle {
  destroyCount = 0;
  private readonly names: () => readonly string[];

  constructor(names: () => readonly string[]) {
    this.names = names;
  }

  getPortCount(): number {
    return this.names().length;
  }

  getPortName(index: number): string {
    const name = this.names()[index];
    if (name === undefined) throw new RangeError(`missing fake port ${index}`);
    return name;
  }

  destroy(): void {
    this.destroyCount += 1;
  }
}

function fakeBinding(
  inputNames: () => readonly string[],
  outputNames: () => readonly string[],
): { readonly binding: MidiEnumerationBinding; readonly inputs: readonly FakeHandle[]; readonly outputs: readonly FakeHandle[] } {
  const inputs: FakeHandle[] = [];
  const outputs: FakeHandle[] = [];
  return {
    binding: {
      Input: class extends FakeHandle {
        constructor() {
          super(inputNames);
          inputs.push(this);
        }
      },
      Output: class extends FakeHandle {
        constructor() {
          super(outputNames);
          outputs.push(this);
        }
      },
    },
    inputs,
    outputs,
  };
}

test("enumerates zero ports without opening them and destroys both enumeration handles", () => {
  const fake = fakeBinding(() => [], () => []);
  const inventory = createMidiPortEnumerator(fake.binding).enumerate();

  assert.deepEqual(inventory, { inputs: [], outputs: [] });
  assert.equal(fake.inputs.length, 1);
  assert.equal(fake.outputs.length, 1);
  assert.equal(fake.inputs[0]?.destroyCount, 1);
  assert.equal(fake.outputs[0]?.destroyCount, 1);
});

test("rejects missing and duplicate exact endpoint names", () => {
  const fake = fakeBinding(
    () => ["AI DJ", "AI DJ"],
    () => ["Other"],
  );
  const enumerator = createMidiPortEnumerator(fake.binding);

  assert.throws(
    () => resolveExactEndpoints(enumerator, { commandOutputName: "AI DJ", feedbackInputName: "AI DJ" }),
    (error: unknown) => error instanceof EndpointSelectionError && error.kind === "missing" && error.direction === "output",
  );
  assert.throws(
    () => resolveExactEndpoints(enumerator, { commandOutputName: "Other", feedbackInputName: "AI DJ" }),
    (error: unknown) => error instanceof EndpointSelectionError && error.kind === "ambiguous" && error.direction === "input",
  );
});

test("resolves fresh endpoint indexes after the binding reorders ports", () => {
  let inputs = ["AI DJ", "Controller"];
  let outputs = ["AI DJ", "Controller"];
  const fake = fakeBinding(() => inputs, () => outputs);
  const enumerator = createMidiPortEnumerator(fake.binding);

  const first = resolveExactEndpoints(enumerator, { commandOutputName: "AI DJ", feedbackInputName: "AI DJ" });
  inputs = ["Controller", "AI DJ"];
  outputs = ["Controller", "AI DJ"];
  const second = resolveExactEndpoints(enumerator, { commandOutputName: "AI DJ", feedbackInputName: "AI DJ" });

  assert.equal(first.commandOutput.enumerationIndex, 0);
  assert.equal(first.feedbackInput.enumerationIndex, 0);
  assert.equal(second.commandOutput.enumerationIndex, 1);
  assert.equal(second.feedbackInput.enumerationIndex, 1);
  assert.equal(fake.inputs.length, 2);
  assert.equal(fake.outputs.length, 2);
});

test("destroys created handles when enumeration or cleanup raises", () => {
  const inputs: ThrowingCountHandle[] = [];
  const outputs: FakeHandle[] = [];
  const binding: MidiEnumerationBinding = {
    Input: class extends ThrowingCountHandle {
      constructor() {
        super(() => ["AI DJ"]);
        inputs.push(this);
      }
    },
    Output: class extends FakeHandle {
      constructor() {
        super(() => ["AI DJ"]);
        outputs.push(this);
      }
    },
  };

  assert.throws(() => createMidiPortEnumerator(binding).enumerate(), /input count failed/);
  assert.equal(inputs[0]?.destroyCount, 1);
  assert.equal(outputs[0]?.destroyCount, 1);

  const cleanup = fakeBinding(() => ["AI DJ"], () => ["AI DJ"]);
  const firstInput = cleanup.binding.Input;
  cleanup.binding.Input = class extends firstInput {
    destroy(): void {
      super.destroy();
      throw new Error("input cleanup failed");
    }
  };
  assert.throws(() => createMidiPortEnumerator(cleanup.binding).enumerate(), /input cleanup failed/);
  assert.equal(cleanup.inputs[0]?.destroyCount, 1);
  assert.equal(cleanup.outputs[0]?.destroyCount, 1);
});

class ThrowingCountHandle extends FakeHandle {
  getPortCount(): number {
    throw new Error("input count failed");
  }
}

// End of autonomously AI-generated file.
