// This file was autonomously generated by an AI agent at the user's request.

import { MIDI_PORT_LIMITS } from "./ports.ts";

export const MIDI_CONNECTION_LIMITS = {
  maxMessageBytes: 1_024,
  maxPortNameUtf8Bytes: 256,
} as const;

export type TransportLossReason = "startup-failed" | "send-failed" | "close-failed";

export interface TransportLoss {
  readonly reason: TransportLossReason;
  readonly error: unknown;
}

export interface FeedbackMessage {
  readonly deltaTimeSeconds: number;
  readonly bytes: readonly number[];
}

export interface VirtualPortConnectionOptions {
  readonly portName: string;
  readonly onFeedback: (message: FeedbackMessage) => void;
  readonly onTransportLoss: (loss: TransportLoss) => void;
}

export interface NativeInputHandle {
  getPortCount(): number;
  getPortName(index: number): string;
  isPortOpen(): boolean;
  ignoreTypes(sysex: boolean, timing: boolean, activeSensing: boolean): void;
  on(event: "message", listener: (deltaTimeSeconds: number, bytes: number[]) => void): unknown;
  removeListener(event: "message", listener: (deltaTimeSeconds: number, bytes: number[]) => void): unknown;
  closePort(): void;
  destroy(): void;
  openVirtualPort(name: string): void;
}

export interface NativeOutputHandle {
  getPortCount(): number;
  getPortName(index: number): string;
  isPortOpen(): boolean;
  closePort(): void;
  destroy(): void;
  openVirtualPort(name: string): void;
  sendMessage(bytes: number[]): void;
}

export interface MidiConnectionBinding {
  Input: new () => NativeInputHandle;
  Output: new () => NativeOutputHandle;
}

export interface VirtualMidiConnection {
  readonly portName: string;
  readonly status: "open" | "closed" | "lost";
  send(bytes: readonly number[]): void;
  close(): void;
}

export class PortNameCollisionError extends Error {
  readonly direction: "input" | "output";
  readonly portName: string;

  constructor(direction: "input" | "output", portName: string) {
    super(`external ${direction} endpoint already uses ${JSON.stringify(portName)}`);
    this.name = "PortNameCollisionError";
    this.direction = direction;
    this.portName = portName;
  }
}

export function openVirtualMidiConnection(
  binding: MidiConnectionBinding,
  options: VirtualPortConnectionOptions,
): VirtualMidiConnection {
  const stableOptions = snapshotOptions(options);
  assertPortName(stableOptions.portName);
  let input: NativeInputHandle | undefined;
  let output: NativeOutputHandle | undefined;
  let feedbackListener: ((deltaTimeSeconds: number, bytes: number[]) => void) | undefined;
  const feedbackGate = { accepting: true };
  let primaryError: unknown;

  try {
    input = new binding.Input();
    output = new binding.Output();
    assertNoExternalName(input, "input", stableOptions.portName);
    assertNoExternalName(output, "output", stableOptions.portName);

    input.ignoreTypes(false, true, true);
    feedbackListener = (deltaTimeSeconds, bytes) => {
      if (!feedbackGate.accepting) return;
      if (!isValidMessage(bytes)) return;
      stableOptions.onFeedback(Object.freeze({
        deltaTimeSeconds,
        bytes: Object.freeze([...bytes]),
      }));
    };
    input.on("message", feedbackListener);
    input.openVirtualPort(stableOptions.portName);
    output.openVirtualPort(stableOptions.portName);

    return new NativeVirtualMidiConnection(input, output, feedbackListener, feedbackGate, stableOptions);
  } catch (error) {
    primaryError = error;
    throw error;
  } finally {
    if (primaryError !== undefined) {
      feedbackGate.accepting = false;
      const cleanupErrors = disposeHandles(input, output, feedbackListener);
      const reported = cleanupErrors.length === 0
        ? primaryError
        : new AggregateError([primaryError, ...cleanupErrors], "MIDI connection startup cleanup failed");
      reportTransportLoss(stableOptions, { reason: "startup-failed", error: reported });
      if (cleanupErrors.length > 0) throw reported;
    }
  }
}

export async function openNativeVirtualMidiConnection(
  options: VirtualPortConnectionOptions,
): Promise<VirtualMidiConnection> {
  const midi = await import("@julusian/midi");
  return openVirtualMidiConnection({ Input: midi.Input, Output: midi.Output }, options);
}

class NativeVirtualMidiConnection implements VirtualMidiConnection {
  #status: "open" | "closed" | "lost" = "open";
  #closeAttempted = false;
  private readonly input: NativeInputHandle;
  private readonly output: NativeOutputHandle;
  private readonly feedbackListener: (deltaTimeSeconds: number, bytes: number[]) => void;
  private readonly feedbackGate: { accepting: boolean };
  private readonly options: VirtualPortConnectionOptions;

  constructor(
    input: NativeInputHandle,
    output: NativeOutputHandle,
    feedbackListener: (deltaTimeSeconds: number, bytes: number[]) => void,
    feedbackGate: { accepting: boolean },
    options: VirtualPortConnectionOptions,
  ) {
    this.input = input;
    this.output = output;
    this.feedbackListener = feedbackListener;
    this.feedbackGate = feedbackGate;
    this.options = options;
  }

  get portName(): string {
    return this.options.portName;
  }

  get status(): "open" | "closed" | "lost" {
    return this.#status;
  }

  send(bytes: readonly number[]): void {
    if (this.#status !== "open") throw new Error("MIDI transport is not open");
    assertMessage(bytes);
    try {
      this.output.sendMessage([...bytes]);
    } catch (error) {
      this.#status = "lost";
      reportTransportLoss(this.options, { reason: "send-failed", error });
      throw error;
    }
  }

  close(): void {
    if (this.#closeAttempted) return;
    this.#closeAttempted = true;
    this.feedbackGate.accepting = false;
    const cleanupErrors = disposeHandles(this.input, this.output, this.feedbackListener);
    this.#status = cleanupErrors.length === 0 ? "closed" : "lost";
    if (cleanupErrors.length > 0) {
      const error = cleanupErrors.length === 1
        ? cleanupErrors[0]
        : new AggregateError(cleanupErrors, "MIDI connection cleanup failed");
      reportTransportLoss(this.options, { reason: "close-failed", error });
      throw error;
    }
  }
}

function assertNoExternalName(
  handle: Pick<NativeInputHandle, "getPortCount" | "getPortName"> | Pick<NativeOutputHandle, "getPortCount" | "getPortName">,
  direction: "input" | "output",
  requestedName: string,
): void {
  const count = handle.getPortCount();
  if (!Number.isSafeInteger(count) || count < 0 || count > MIDI_PORT_LIMITS.maxPortsPerDirection) {
    throw new RangeError(`${direction} port count is invalid`);
  }
  for (let index = 0; index < count; index += 1) {
    if (handle.getPortName(index) === requestedName) throw new PortNameCollisionError(direction, requestedName);
  }
}

function disposeHandles(
  input: NativeInputHandle | undefined,
  output: NativeOutputHandle | undefined,
  feedbackListener: ((deltaTimeSeconds: number, bytes: number[]) => void) | undefined,
): readonly unknown[] {
  const errors: unknown[] = [];
  if (input !== undefined && feedbackListener !== undefined) {
    try {
      input.removeListener("message", feedbackListener);
    } catch (error) {
      errors.push(error);
    }
  }
  for (const handle of [output, input]) {
    if (handle === undefined) continue;
    try {
      if (handle.isPortOpen()) handle.closePort();
    } catch (error) {
      errors.push(error);
    }
    try {
      handle.destroy();
    } catch (error) {
      errors.push(error);
    }
  }
  return errors;
}

function assertPortName(portName: string): void {
  if (portName.length === 0) throw new RangeError("portName must not be empty");
  if (new TextEncoder().encode(portName).byteLength > MIDI_CONNECTION_LIMITS.maxPortNameUtf8Bytes) {
    throw new RangeError(`portName exceeds ${MIDI_CONNECTION_LIMITS.maxPortNameUtf8Bytes} UTF-8 bytes`);
  }
}

function snapshotOptions(options: VirtualPortConnectionOptions): VirtualPortConnectionOptions {
  if (typeof options.onFeedback !== "function" || typeof options.onTransportLoss !== "function") {
    throw new TypeError("connection callbacks must be functions");
  }
  return Object.freeze({
    portName: options.portName,
    onFeedback: options.onFeedback,
    onTransportLoss: options.onTransportLoss,
  });
}

function isValidMessage(bytes: readonly number[]): boolean {
  try {
    assertMessage(bytes);
    return true;
  } catch {
    return false;
  }
}

function assertMessage(bytes: readonly number[]): void {
  if (bytes.length === 0 || bytes.length > MIDI_CONNECTION_LIMITS.maxMessageBytes) {
    throw new RangeError(`MIDI message must contain 1 to ${MIDI_CONNECTION_LIMITS.maxMessageBytes} bytes`);
  }
  for (const byte of bytes) {
    if (!Number.isSafeInteger(byte) || byte < 0 || byte > 255) throw new RangeError("MIDI bytes must be integers from 0 to 255");
  }
}

function reportTransportLoss(options: VirtualPortConnectionOptions, loss: TransportLoss): void {
  try {
    options.onTransportLoss(Object.freeze(loss));
  } catch {}
}

// End of autonomously AI-generated file.
