// This file was autonomously generated by an AI agent at the user's request.
// Pure decoder for the frozen F09 conventional feedback profile; no ports are opened.

export type ConventionalPresence = "unavailable" | "unknown" | "present";
export type ConventionalControlMeaning = "host-control-state" | "control-signal-only";

export interface ConventionalFeedbackProvenance {
  readonly receivedAtMs: number;
  readonly actor: "unknown";
  readonly correlation: "none";
  readonly hostObservation: "unproven";
}

export interface ConventionalValueFeedback {
  readonly kind: "value";
  readonly controlId: string;
  readonly capabilityId: string;
  readonly deck: 1 | 2 | null;
  readonly meaning: ConventionalControlMeaning;
  readonly value: boolean | number;
  readonly packet: readonly [number, number, number];
  readonly provenance: ConventionalFeedbackProvenance;
}

export interface ConventionalPresenceFeedback {
  readonly kind: "presence";
  readonly controlId: string;
  readonly capabilityId: string;
  readonly deck: 1 | 2 | null;
  readonly presence: ConventionalPresence;
  readonly packet: readonly [number, number, number];
  readonly provenance: ConventionalFeedbackProvenance;
}

export type ConventionalFeedback = ConventionalValueFeedback | ConventionalPresenceFeedback;

type Encoding = "boolean" | "volume" | "crossfader";
interface Control {
  readonly id: string;
  readonly capabilityId: string;
  readonly deck: 1 | 2 | null;
  readonly status: number;
  readonly valueAddress: number;
  readonly presenceAddress: number;
  readonly encoding: Encoding;
  readonly meaning: ConventionalControlMeaning;
}

// This is the nine-entry feedback projection of hosts/mixxx/conventional-profile.json.
const controls: readonly Control[] = Object.freeze([
  { id: "deck-1.play", capabilityId: "mixxx.deck.playing", deck: 1, status: 0xb8, valueAddress: 0x20, presenceAddress: 0x70, encoding: "boolean", meaning: "host-control-state" },
  { id: "deck-1.volume", capabilityId: "mixxx.deck.volume", deck: 1, status: 0xb8, valueAddress: 0x21, presenceAddress: 0x71, encoding: "volume", meaning: "host-control-state" },
  { id: "deck-1.cue", capabilityId: "mixxx.deck.main-cue-hold", deck: 1, status: 0xb8, valueAddress: 0x23, presenceAddress: 0x72, encoding: "boolean", meaning: "control-signal-only" },
  { id: "deck-1.sync", capabilityId: "mixxx.deck.sync-enabled", deck: 1, status: 0xb8, valueAddress: 0x22, presenceAddress: 0x73, encoding: "boolean", meaning: "host-control-state" },
  { id: "deck-2.play", capabilityId: "mixxx.deck.playing", deck: 2, status: 0xb9, valueAddress: 0x20, presenceAddress: 0x70, encoding: "boolean", meaning: "host-control-state" },
  { id: "deck-2.volume", capabilityId: "mixxx.deck.volume", deck: 2, status: 0xb9, valueAddress: 0x21, presenceAddress: 0x71, encoding: "volume", meaning: "host-control-state" },
  { id: "deck-2.cue", capabilityId: "mixxx.deck.main-cue-hold", deck: 2, status: 0xb9, valueAddress: 0x23, presenceAddress: 0x72, encoding: "boolean", meaning: "control-signal-only" },
  { id: "deck-2.sync", capabilityId: "mixxx.deck.sync-enabled", deck: 2, status: 0xb9, valueAddress: 0x22, presenceAddress: 0x73, encoding: "boolean", meaning: "host-control-state" },
  { id: "mixer.crossfader", capabilityId: "mixxx.mixer.crossfader", deck: null, status: 0xba, valueAddress: 0x24, presenceAddress: 0x74, encoding: "crossfader", meaning: "host-control-state" },
]);

/**
 * Decodes one incoming feedback packet. Null means that this profile does not
 * admit the packet; no state is changed and no packet is sent.
 */
export function decodeConventionalFeedback(
  input: readonly number[],
  receivedAtMs: number,
): ConventionalFeedback | null {
  assertReceiptTime(receivedAtMs);
  if (input.length !== 3) return null;
  const [status, address, data] = input;
  if (!isStatusByte(status) || !isMidiDataByte(address) || !isMidiDataByte(data)) return null;
  const control = controls.find((candidate) => candidate.status === status && (candidate.valueAddress === address || candidate.presenceAddress === address));
  if (!control) return null;
  const packet = Object.freeze([status, address, data] as [number, number, number]);
  const provenance = Object.freeze({ receivedAtMs, actor: "unknown" as const, correlation: "none" as const, hostObservation: "unproven" as const });
  if (address === control.presenceAddress) {
    const presence = decodePresence(data);
    if (presence === null) return null;
    return Object.freeze({ kind: "presence", controlId: control.id, capabilityId: control.capabilityId, deck: control.deck, presence, packet, provenance });
  }
  const value = decodeValue(control.encoding, data);
  if (value === null) return null;
  return Object.freeze({ kind: "value", controlId: control.id, capabilityId: control.capabilityId, deck: control.deck, meaning: control.meaning, value, packet, provenance });
}

function assertReceiptTime(value: number): void {
  if (!Number.isFinite(value) || value < 0 || value > Number.MAX_SAFE_INTEGER) {
    throw new RangeError("receivedAtMs must be a finite nonnegative monotonic millisecond value");
  }
}

function isStatusByte(value: number | undefined): value is number {
  return typeof value === "number" && Number.isInteger(value) && value >= 0 && value <= 255;
}

function isMidiDataByte(value: number | undefined): value is number {
  return typeof value === "number" && Number.isInteger(value) && value >= 0 && value <= 127;
}

function decodePresence(value: number): ConventionalPresence | null {
  if (value === 0) return "unavailable";
  if (value === 64) return "unknown";
  if (value === 127) return "present";
  return null;
}

function decodeValue(encoding: Encoding, value: number): boolean | number | null {
  if (encoding === "boolean") return value === 0 ? false : value === 127 ? true : null;
  if (encoding === "volume") return value / 127;
  return value <= 64 ? value / 128 : (value - 1) / 126;
}

// End of autonomously AI-generated file.
