// This file was autonomously generated by an AI agent at the user's request.

export type MidiPortDirection = "input" | "output";

export const MIDI_PORT_LIMITS = {
  maxPortsPerDirection: 1_024,
  maxPortNameUtf8Bytes: 256,
} as const;

export interface EnumeratedMidiHandle {
  getPortCount(): number;
  getPortName(index: number): string;
  destroy(): void;
}

export interface MidiEnumerationBinding {
  Input: new () => EnumeratedMidiHandle;
  Output: new () => EnumeratedMidiHandle;
}

export interface MidiPortEnumerator {
  enumerate(): MidiPortInventory;
}

export interface MidiPort {
  readonly direction: MidiPortDirection;
  readonly name: string;
  readonly enumerationIndex: number;
}

export interface MidiPortInventory {
  readonly inputs: readonly MidiPort[];
  readonly outputs: readonly MidiPort[];
}

export interface ExactEndpointSelection {
  readonly commandOutputName: string;
  readonly feedbackInputName: string;
}

export interface ResolvedMidiEndpoints {
  readonly commandOutput: MidiPort;
  readonly feedbackInput: MidiPort;
}

export class EndpointSelectionError extends Error {
  readonly kind: "missing" | "ambiguous";
  readonly direction: MidiPortDirection;
  readonly requestedName: string;
  readonly matches: readonly MidiPort[];

  constructor(
    kind: "missing" | "ambiguous",
    direction: MidiPortDirection,
    requestedName: string,
    matches: readonly MidiPort[],
  ) {
    super(`${direction} endpoint ${JSON.stringify(requestedName)} is ${kind}`);
    this.name = "EndpointSelectionError";
    this.kind = kind;
    this.direction = direction;
    this.requestedName = requestedName;
    this.matches = Object.freeze([...matches]);
  }
}

export function createMidiPortEnumerator(binding: MidiEnumerationBinding): MidiPortEnumerator {
  return Object.freeze({
    enumerate: () => enumerateBindingPorts(binding),
  });
}

export async function createNativeMidiPortEnumerator(): Promise<MidiPortEnumerator> {
  const midi = await import("@julusian/midi");
  return createMidiPortEnumerator({ Input: midi.Input, Output: midi.Output });
}

export function resolveExactEndpoints(
  enumerator: MidiPortEnumerator,
  selection: ExactEndpointSelection,
): ResolvedMidiEndpoints {
  assertExactName(selection.commandOutputName, "commandOutputName");
  assertExactName(selection.feedbackInputName, "feedbackInputName");

  const inventory = enumerator.enumerate();
  return Object.freeze({
    commandOutput: selectExactEndpoint(inventory.outputs, "output", selection.commandOutputName),
    feedbackInput: selectExactEndpoint(inventory.inputs, "input", selection.feedbackInputName),
  });
}

export function enumerateBindingPorts(binding: MidiEnumerationBinding): MidiPortInventory {
  let input: EnumeratedMidiHandle | undefined;
  let output: EnumeratedMidiHandle | undefined;
  let primaryError: unknown;

  try {
    input = new binding.Input();
    output = new binding.Output();
    return freezeInventory({
      inputs: enumerateHandle(input, "input"),
      outputs: enumerateHandle(output, "output"),
    });
  } catch (error) {
    primaryError = error;
    throw error;
  } finally {
    const cleanupErrors = destroyHandles(input, output);
    if (cleanupErrors.length > 0) {
      if (primaryError !== undefined) {
        throw new AggregateError([primaryError, ...cleanupErrors], "MIDI enumeration and cleanup failed");
      }
      if (cleanupErrors.length === 1) throw cleanupErrors[0];
      throw new AggregateError(cleanupErrors, "MIDI enumeration cleanup failed");
    }
  }
}

function enumerateHandle(handle: EnumeratedMidiHandle, direction: MidiPortDirection): readonly MidiPort[] {
  const count = handle.getPortCount();
  if (!Number.isSafeInteger(count) || count < 0 || count > MIDI_PORT_LIMITS.maxPortsPerDirection) {
    throw new RangeError(`${direction} port count is outside the allowed range`);
  }
  const ports: MidiPort[] = [];
  for (let enumerationIndex = 0; enumerationIndex < count; enumerationIndex += 1) {
    const name = handle.getPortName(enumerationIndex);
    assertExactName(name, `${direction}[${enumerationIndex}]`);
    ports.push(Object.freeze({ direction, name, enumerationIndex }));
  }
  return Object.freeze(ports);
}

function selectExactEndpoint(
  ports: readonly MidiPort[],
  direction: MidiPortDirection,
  requestedName: string,
): MidiPort {
  const matches = ports.filter((port) => port.name === requestedName);
  if (matches.length === 0) throw new EndpointSelectionError("missing", direction, requestedName, matches);
  if (matches.length > 1) throw new EndpointSelectionError("ambiguous", direction, requestedName, matches);
  const selected = matches[0];
  if (selected === undefined) throw new Error("exact endpoint selection unexpectedly had no match");
  return selected;
}

function destroyHandles(
  input: EnumeratedMidiHandle | undefined,
  output: EnumeratedMidiHandle | undefined,
): readonly unknown[] {
  const cleanupErrors: unknown[] = [];
  for (const handle of [output, input]) {
    if (handle === undefined) continue;
    try {
      handle.destroy();
    } catch (error) {
      cleanupErrors.push(error);
    }
  }
  return cleanupErrors;
}

function freezeInventory(inventory: MidiPortInventory): MidiPortInventory {
  return Object.freeze({
    inputs: Object.freeze([...inventory.inputs]),
    outputs: Object.freeze([...inventory.outputs]),
  });
}

function assertExactName(name: string, field: string): void {
  if (name.length === 0) throw new RangeError(`${field} must not be empty`);
  if (new TextEncoder().encode(name).byteLength > MIDI_PORT_LIMITS.maxPortNameUtf8Bytes) {
    throw new RangeError(`${field} exceeds ${MIDI_PORT_LIMITS.maxPortNameUtf8Bytes} UTF-8 bytes`);
  }
}

// End of autonomously AI-generated file.
